'use client';
import {useCallback,useEffect,useState} from 'react';
type Job={id:string;platform:string;account_name:string;state:string;current_step?:string;open_tasks:number;updated_at:string};
type Task={id:string;account_name:string;platform:string;task_type:string;instructions:string;due_at?:string};
type Requirement={platform:string;priority?:string;business_use?:string;content_strength?:string;automation_level?:string;manual_prerequisite?:string;publishing_supported:boolean;developer_portal_url?:string;automation_policy:string};
export default function ProvisioningPage(){
 const[data,setData]=useState<{jobs:Job[];humanTasks:Task[];requirements:Requirement[]}>({jobs:[],humanTasks:[],requirements:[]});const[platform,setPlatform]=useState('telegram');const[name,setName]=useState('');const[message,setMessage]=useState('');const[skyvern,setSkyvern]=useState<{healthy:boolean;uiUrl?:string}>({healthy:false});
 const load=useCallback(()=>{void fetch('/api/admin/social/provisioning/skyvern',{cache:'no-store'}).then(r=>r.json()).then(setSkyvern).catch(()=>setSkyvern({healthy:false}));return fetch('/api/admin/social/provisioning',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setMessage(e.message))},[]);useEffect(()=>{void load()},[load]);
 const create=async()=>{setMessage('Creating…');const r=await fetch('/api/admin/social/provisioning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform,accountName:name})});const b=await r.json();setMessage(r.ok?'Provisioning job created.':b.error);if(r.ok){setName('');void load()}};
 const startBrowser=async(id:string)=>{setMessage('Starting guarded Skyvern run…');const r=await fetch(`/api/admin/social/provisioning/${id}/skyvern`,{method:'POST'});const b=await r.json();setMessage(r.ok?`Skyvern run ${b.run.run_id} queued.`:b.error);if(r.ok)void load()};
 return <div className="mx-auto max-w-7xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Social Account Provisioning</h1><p className="text-sm text-gray-600">Prepare accounts and developer access with explicit human checkpoints. CAPTCHA, OTP, 2FA, consent, and identity verification are never bypassed.</p></header>
 <section className={`rounded-xl border p-4 ${skyvern.healthy?'border-green-200 bg-green-50':'border-amber-200 bg-amber-50'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>Skyvern browser worker: {skyvern.healthy?'healthy':'unavailable'}</strong><p className="text-sm text-gray-600">Assisted navigation only; sensitive checkpoints always stop for a human.</p></div>{skyvern.uiUrl&&<a className="rounded border bg-white px-3 py-2 text-sm" href={skyvern.uiUrl} target="_blank" rel="noreferrer">Watch browser live</a>}</div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Start assisted setup</h2><div className="mt-3 flex flex-wrap gap-2"><select aria-label="Platform" className="rounded border p-2" value={platform} onChange={e=>setPlatform(e.target.value)}>{data.requirements.map(r=><option key={r.platform} value={r.platform}>{r.platform.replaceAll('_',' ')}</option>)}</select><input className="min-w-64 rounded border p-2" value={name} onChange={e=>setName(e.target.value)} placeholder="Business / account name"/><button className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50" disabled={!name.trim()||!platform} onClick={create}>Create job</button><span role="status" className="self-center text-sm">{message}</span></div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">28-channel provisioning roadmap</h2><p className="mt-1 text-sm text-gray-600">Automation labels describe supported capability, not permission to bypass ownership, verification, consent, or community rules.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.requirements.map(r=><article key={r.platform} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><strong className="capitalize">{r.platform.replaceAll('_',' ')}</strong><span className={`rounded px-2 py-1 text-xs ${r.priority==='red'?'bg-red-100 text-red-800':r.priority==='orange'?'bg-orange-100 text-orange-800':'bg-yellow-100 text-yellow-800'}`}>{r.automation_level||'assisted'}</span></div><p className="mt-2 text-sm">{r.business_use}</p><p className="mt-1 text-xs text-gray-600">{r.content_strength} · {r.manual_prerequisite}</p><div className="mt-3 flex gap-2"><span className={`text-xs font-medium ${r.publishing_supported?'text-green-700':'text-gray-500'}`}>{r.publishing_supported?'Publishing API':'Manual/assisted'}</span>{r.developer_portal_url&&<a className="text-xs text-indigo-700 underline" href={r.developer_portal_url} target="_blank" rel="noreferrer">Setup portal</a>}</div></article>)}</div></section>
 <div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2 rounded-xl border bg-white p-5"><h2 className="font-semibold">Provisioning jobs</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Account</th><th>Platform</th><th>State</th><th>Human tasks</th><th>Browser</th><th>Updated</th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id} className="border-b"><td className="p-2 font-medium">{j.account_name}</td><td>{j.platform}</td><td><span className="rounded bg-indigo-50 px-2 py-1 text-xs text-indigo-800">{j.state}</span></td><td>{j.open_tasks}</td><td><button className="rounded border px-2 py-1 text-xs disabled:opacity-40" disabled={!skyvern.healthy||!['VALIDATION_PASSED','SIGNUP_STARTED','ACCOUNT_CREATED','DEVELOPER_APP_PENDING','REVIEW_REQUIRED'].includes(j.state)} onClick={()=>startBrowser(j.id)}>Start assisted run</button></td><td>{new Date(j.updated_at).toLocaleString()}</td></tr>)}</tbody></table>{!data.jobs.length&&<p className="py-5 text-gray-500">No provisioning jobs yet.</p>}</div></section>
 <section className="rounded-xl border bg-amber-50 p-5"><h2 className="font-semibold">Human action queue</h2><div className="mt-3 space-y-3">{data.humanTasks.map(t=><article key={t.id} className="rounded border bg-white p-3"><div className="text-xs font-semibold text-amber-800">{t.task_type}</div><div className="font-medium">{t.account_name} · {t.platform}</div><p className="mt-1 text-sm text-gray-600">{t.instructions}</p></article>)}{!data.humanTasks.length&&<p className="text-sm text-gray-600">No security or consent actions are waiting.</p>}</div></section></div>
 <section className="rounded-xl border bg-slate-50 p-5 text-sm"><h2 className="font-semibold">Security boundary</h2><p className="mt-2">Passwords, OTP values, client secrets, access tokens, refresh tokens, 2FA seeds, and recovery codes are not accepted by this control plane. Database records contain only <code>vault://</code> references. OAuth consent remains user-controlled.</p></section></div>}
