<!-- AUTO-GENERATED BY CONTINUITY - DO NOT EDIT BELOW THIS LINE -->

# Project Memory (Auto-generated by Continuity)

This file contains project context and decisions. AI assistants should read this file for context. MCP tools are an optional enhancement for richer interaction when connected.

## Project Context
- **Total Decisions:** 40
- **Known Topics:** ollama, ai, api, how, architecture, auth, cli, security, auto-seeded, seeded, monitoring, observability, testing, bug-fix, deployment

## Current State
**Repository:** sohamyoga
**Project Type:** Python Project | Python
**Branch:** main
**Tracking:** ahead 1, behind 0

**Recent Commits:**
- `c7a4f55 fix: consistent always-blue navbar across all pages`
- `c5cf942 fix: portable frontend — relative API paths for tunnel + remote access`
- `668ca4d test: extend matrix to 83/83 — UsersController CRUD + bootstrap-artifact ignores`
- `ec4b5ea test: add comprehensive API matrix — 74/74 endpoints inc. CRUD lifecycles`
- `59cd6bd test: add advanced API + Playwright matrix; fix frontend healthcheck IPv4`

**Working Tree:**
- M .env.template
- M .gitignore
- D SLPSystems/SLPSystems.Web/.dockerignore
- D SLPSystems/SLPSystems.Web/Controllers/AdminMonitoringController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/AdminDashboardController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/AuthController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/BlogController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/CaseStudiesController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/ContactController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/CustomerAuthController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/HomeController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/IndustriesController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/JobsController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/LiveChatController.cs
- D SLPSystems/SLPSystems.Web/Controllers/Api/NewsletterController.cs


## Decision Freshness
**0 stale decisions** · 1 need review · Oldest unreviewed: 2026-03-06

Stale decisions requiring attention:
1. **msdz1udw-9800qd** (score 35) — "Why: security: comprehensive hardening — XSS, CSRF, secrets, CI, nginx, rate lim" — 22 weeks old, status: outdated, never reviewed

When referencing these decisions, note their staleness. Verify they still reflect current project state before recommending based on them.

## Operating Contract
1. **Load context, then search before you change.** MCP-capable agents: call `get_quick_context` at session start, then `search_decisions` before proposing changes. Shell/CLI-only agents (e.g. Copilot): run `continuity context`, then `continuity search "<topic>"` (`grep -i "<topic>" .continuity/decisions.jsonl` if the CLI is unavailable). Name any conflict with a prior decision and let the user choose. **When a prior decision informs your answer, cite it inline — "per decision-abc123, we chose X because Y" — so the user can see the memory being used, not just trust that it was.** `search_decisions` returns a `sourceTag` per result; use it.
2. **Log every deliberate change, immediately.** After each change — not batched — `continuity log "question" "answer" --tags ...`. The trigger is the change, not the commit; include the commit hash in both fields when one exists. Don't ask permission; installing Continuity is the opt-in. Tell the user you logged it.
3. **Track session state.** Edit `.continuity/SESSION_NOTES.md` for goals/blockers and an end-of-session summary.
4. **Recover & be transparent.** If you notice unlogged earlier changes, pause, log them retroactively, and say so.

## Logging paths
- MCP connected: `log_decision` / `search_decisions` / `get_quick_context` / `update_session_notes` — prefer these; they exercise the production path.
- MCP down: `continuity log "question" "answer" --tags a,b` — the always-works fallback.
- Forward work → `continuity task ...` (new ticket); in-flight note → `continuity note ...` (comment on current ticket). Don't cross-pollute.

---

## Project Instructions

# Project Instructions

Describe how this repository prefers to work with AI assistants.


---

## Recent Decisions
1. **decision-b5bf3d7b** (8/8/2026) [facebook, how]
   - Q: How should Meta developer-app setup be represented in SohamYoga?
   - A: Added an admin Meta Setup Assistant with copyable domain/privacy/terms/deletion/callback values, secret-clearing credential submission, permissions/review checklist and links to compose/all providers. Added public privacy, terms and data-deletion pages and a Facebook callback handoff to Postiz. Secured social credential GET/POST with requireAdmin; anonymous writes now return 401.

2. **decision-ab3df2d6** (8/8/2026) [cli, how]
   - Q: How should an operator collect social developer-app setup data from the command line?
   - A: Added global soham-social-setup interactive CLI. It prompts for organization/email/domain/policy URLs/providers, opens official portals optionally, displays exact callbacks, reads secrets silently, writes permission-0600 local files, backs up prior config, registers only non-secret status in integration_master and validates provider completeness. It cannot bypass legal/identity/app review.

3. **decision-766569d9** (8/8/2026) [accessibility, bug-fix]
   - Q: Which initial accessibility defects were repaired?
   - A: Added an accessible newsletter-submit name, promoted login page title to h1, strengthened consent controls, catalogue filters/tags/capacity/CTA contrast, and footer legal-link contrast. Remaining axe failures stay in the report for subsequent repairs.

4. **decision-8988fdc8** (8/8/2026) [accessibility, auth]
   - Q: What global policy governs end-to-end product quality?
   - A: Added OLLAMA_GLOBAL_POLICY section 15: every change maps to actor/story and positive, negative, data, role, auth, accessibility and observability tests; deterministic Playwright/Chrome CDP/axe is authoritative; Stagehand/CUA is optional and time-bounded; failed evidence cannot be hidden; self-heal cannot silently rewrite or publish.

5. **decision-4ca3b07d** (8/8/2026) [how, monitoring]
   - Q: How should automated self-healing react to quality failures?
   - A: Added a 30-minute user systemd quality timer. It may restart only known unhealthy Soham frontend/backend services, retains failure artifacts and queues an Ollama repair-review plan. It never silently edits code, publishes externally or performs destructive operations. Stagehand is capped at 60 seconds.

---

*Auto-generated by Continuity | Updated: 2026-08-09*

<!-- END CONTINUITY AUTO-GENERATED CONTENT -->
