// SocialContentIdeaJob — Hourly
// Auto-enqueues a fresh marketing_automation_request for every tenant that
// has configured a real marketing_business_profile, so the existing
// MarketingAutomationJob (every 2 min) has something to generate without a
// human manually filling in a campaign brief each time.
//
// Deliberately does NOT invent a discount, price, date, or specific class —
// none of that is real data anywhere in this schema (no seeded
// class_session/service_master rows). Rotates through a small fixed set of
// honest, generic angles grounded only in the tenant's own configured
// audience/value_proposition — the same non-fabrication constraint the
// compliance checker already enforces on the content itself.
//
// Does NOT publish anything. Generated assets land in review_required, same
// as a manually-created campaign — a human still approves before any
// scheduling/publishing step, and publishing itself additionally requires a
// real connected social account, which this job cannot create.

import { Pool } from 'pg';

const db = new Pool({ connectionString: process.env.DATABASE_URL });

const ANGLES = [
  { key: 'welcome', title: 'New Student Welcome', note: 'Welcome newcomers exploring yoga for the first time — no experience necessary.' },
  { key: 'community', title: 'Community Spotlight', note: 'Highlight the sense of community and belonging that comes from practicing together.' },
  { key: 'mindful_movement', title: 'Mindful Movement', note: 'Highlight the strength, flexibility, and mindfulness benefits of regular practice.' },
  { key: 'beginner_friendly', title: 'Beginner Friendly Reminder', note: 'Reassure beginners that every level is welcome, no mat or experience required to start.' },
] as const;

interface ProfileRow {
  tenant_id: string; business_name: string; audience: string; value_proposition: string; website_url: string | null;
}

export async function run(): Promise<void> {
  const profiles = await db.query<ProfileRow>(
    `SELECT tenant_id, business_name, audience, value_proposition, website_url
     FROM marketing_business_profile WHERE business_name <> '' AND audience <> ''`,
  );

  let created = 0;
  for (const profile of profiles.rows) {
    const recent = await db.query(
      `SELECT id FROM marketing_automation_request WHERE tenant_id = $1 AND created_at > now() - INTERVAL '50 minutes' LIMIT 1`,
      [profile.tenant_id],
    );
    if (recent.rows.length) continue; // already has a fresh-enough campaign in flight

    const enabledChannels = await db.query<{ channel: string }>(
      `SELECT channel FROM tenant_channel_config WHERE tenant_id = $1 AND enabled = TRUE`,
      [profile.tenant_id],
    );
    const channels = enabledChannels.rows.map(r => r.channel);
    if (!channels.length) continue; // nothing enabled to generate for

    const cycleCount = await db.query<{ count: string }>(
      `SELECT COUNT(*) FROM marketing_automation_request WHERE tenant_id = $1`,
      [profile.tenant_id],
    );
    const angle = ANGLES[Number(cycleCount.rows[0].count) % ANGLES.length];

    const client = await db.connect();
    try {
      await client.query('BEGIN');
      const result = await client.query<{ id: string }>(
        `INSERT INTO marketing_automation_request
         (tenant_id, title, industry, objective, audience, offer_text, call_to_action, asset_types, channels, status)
         VALUES ($1,$2,'yoga','awareness',$3,$4,$5,$6,$7,'queued') RETURNING id`,
        [profile.tenant_id, angle.title, profile.audience,
          `${angle.note} Value proposition: ${profile.value_proposition}. No specific discount or promotional price — general awareness content only.`,
          profile.website_url ? `Learn more at ${profile.website_url}` : 'Learn more and book a class',
          ['copy', 'static_banner'], channels],
      );
      await client.query(
        `INSERT INTO marketing_workflow_event (tenant_id, request_id, stage, status, actor_type, message)
         VALUES ($1,$2,'brief','queued','system','Auto-generated by SocialContentIdeaJob (hourly rotation)')`,
        [profile.tenant_id, result.rows[0].id],
      );
      await client.query('COMMIT');
      created++;
    } catch (error) {
      await client.query('ROLLBACK');
      console.error(`[social-content-idea] failed for tenant=${profile.tenant_id}:`, error);
    } finally {
      client.release();
    }
  }

  console.log(`[social-content-idea] tenants=${profiles.rows.length} created=${created}`);
  // Do NOT db.end() here — see NotificationRetryJob.ts.
}
