import {NextRequest} from 'next/server'; import {databaseConfigured,query} from '@/lib/postgres'; import {requireAdmin} from '@/lib/admin-auth';
export const runtime='nodejs'; export const dynamic='force-dynamic';
export async function GET(req:NextRequest){const denied=await requireAdmin(req);if(denied)return denied;if(!databaseConfigured())return Response.json({error:'DATABASE_URL missing'},{status:503});
 const [modules,integrations,tests,components,models,synthetic,errors,features,testFailures,testSuites,testCases,testJobs,performanceTargets]=await Promise.all([
  query('SELECT * FROM v_module_assurance ORDER BY category,name'),query('SELECT * FROM integration_master ORDER BY runtime_status DESC,name'),
  query("SELECT status,test_type,count(*)::int count FROM module_test_run GROUP BY status,test_type ORDER BY status,test_type"),
  query('SELECT component_key,name,runtime,component_type,enabled FROM platform_component ORDER BY runtime,component_key'),
  query("SELECT m.model_name,m.provider,m.capability_codes,m.enabled,count(i.id)::int invocations,max(i.created_at) last_used_at FROM ai_model_master m LEFT JOIN model_invocation i ON i.model_id=m.id GROUP BY m.id ORDER BY invocations DESC,m.model_name"),
  query('SELECT * FROM synthetic_dataset_run ORDER BY created_at DESC LIMIT 20'),
  query('SELECT component_key,error_code,severity,message,occurrence_count,last_seen_at FROM v_open_platform_errors LIMIT 100'),query('SELECT * FROM v_stakeholder_features'),query("SELECT m.module_key,t.test_type,t.test_name,t.status,t.http_status,t.error_type,t.error_message,t.run_at FROM module_test_run t JOIN module_master m ON m.id=t.module_id WHERE t.status IN('failed','blocked') ORDER BY t.run_at DESC LIMIT 200"),
  query('SELECT s.id,s.suite_key,s.name,s.test_level,s.objective,s.runner_key,s.automatic_enabled,s.schedule_cron,s.enabled,m.module_key,count(c.id)::int case_count FROM test_suite_master s LEFT JOIN module_master m ON m.id=s.module_id LEFT JOIN test_case_master c ON c.suite_id=s.id AND c.enabled GROUP BY s.id,m.module_key ORDER BY s.name'),
  query('SELECT s.suite_key,c.case_key,c.name,c.polarity,c.scenario,c.expected_result,c.enabled FROM test_case_master c JOIN test_suite_master s ON s.id=c.suite_id ORDER BY s.suite_key,c.polarity,c.case_key'),
  query('SELECT j.id,s.suite_key,j.trigger_mode,j.status,j.requested_by,j.target_environment,j.total_cases,j.passed_cases,j.failed_cases,j.started_at,j.completed_at,j.created_at FROM test_execution_job j JOIN test_suite_master s ON s.id=j.suite_id ORDER BY j.created_at DESC LIMIT 100'),
  query('SELECT target_key,name,concurrent_users,duration_seconds,max_error_rate,p95_latency_ms,min_requests_per_second,scenario_tags,enabled FROM performance_target ORDER BY name')]);
 return Response.json({modules:modules.rows,integrations:integrations.rows,tests:tests.rows,components:components.rows,models:models.rows,synthetic:synthetic.rows,errors:errors.rows,features:features.rows,testFailures:testFailures.rows,testSuites:testSuites.rows,testCases:testCases.rows,testJobs:testJobs.rows,performanceTargets:performanceTargets.rows});}

export async function POST(req:NextRequest){const denied=await requireAdmin(req);if(denied)return denied;const b=await req.json().catch(()=>null) as {suiteKey?:string;targetEnvironment?:string;parameters?:Record<string,unknown>}|null;const idempotencyKey=req.headers.get('idempotency-key');if(!b?.suiteKey||!idempotencyKey)return Response.json({error:'suiteKey and Idempotency-Key are required'},{status:400});
 const result=await query(`INSERT INTO test_execution_job(suite_id,idempotency_key,trigger_mode,requested_by,target_environment,parameters,total_cases)
 SELECT s.id,$2,'manual','admin-ui',$3,$4::jsonb,(SELECT count(*) FROM test_case_master c WHERE c.suite_id=s.id AND c.enabled) FROM test_suite_master s WHERE s.suite_key=$1 AND s.enabled
 ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[b.suiteKey,idempotencyKey,(b.targetEnvironment||'local').slice(0,40),JSON.stringify(b.parameters||{})]);if(!result.rowCount)return Response.json({error:'Enabled suite not found'},{status:404});return Response.json(result.rows[0],{status:202});}
export async function PUT(req:NextRequest){const denied=await requireAdmin(req);if(denied)return denied;const b=await req.json().catch(()=>null) as {moduleKey?:string;enabled?:boolean}|null;if(!b?.moduleKey||typeof b.enabled!=='boolean')return Response.json({error:'moduleKey and enabled required'},{status:400});
 const result=await query('UPDATE module_master SET enabled=$2,updated_at=now() WHERE module_key=$1 RETURNING module_key,enabled',[b.moduleKey,b.enabled]);if(!result.rowCount)return Response.json({error:'Module not found'},{status:404});return Response.json(result.rows[0]);}
