export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextRequest } from 'next/server';
import { requireAdmin } from '@/lib/admin-auth';

const DISCLAIMER = `\n\n---\n⚠️ DISCLAIMER: This is a draft outline generated by AI for lawyer review only. It does NOT constitute legal advice and must not be used or relied upon as such. All content must be reviewed, verified, and approved by a licensed Canadian lawyer before use. Provincial law variations may apply.`;

export async function POST(req: NextRequest): Promise<Response> {
  const denied = await requireAdmin(req);
  if (denied) return denied;

  const body = await req.json();
  const { matter_type, document_type, client_name, details } = body;

  if (!matter_type || !document_type) {
    return Response.json({ error: 'matter_type, document_type required' }, { status: 400 });
  }

  const prompt = `You are a Canadian legal document assistant helping a law firm draft document outlines.

Matter type: ${matter_type}
Document type: ${document_type}
Client name: ${client_name || '[Client Name]'}
Additional details: ${details || 'None provided'}

Province context: Alberta, Canada (note BC, ON, QC may have different requirements)

Generate a structured outline/template for this document. Include:
1. Document header and parties section
2. Key clauses/sections required for this document type under Canadian law
3. Important considerations and common provisions
4. Signature and execution requirements

Keep it professional and structured. Flag any jurisdiction-specific variations to verify.`;

  try {
    const resp = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: 'llama3.2', prompt, stream: false }),
      signal: AbortSignal.timeout(30000),
    });

    if (!resp.ok) throw new Error('Ollama error');
    const data = await resp.json();
    return Response.json({ result: data.response + DISCLAIMER, matter_type, document_type, client_name });
  } catch {
    return Response.json({
      result: `[AI Document Studio — AI temporarily unavailable]\n\nDocument type: ${document_type}\nMatter type: ${matter_type}\nClient: ${client_name || 'N/A'}\n\nPlease have a licensed lawyer draft this document manually.${DISCLAIMER}`,
      fallback: true,
    });
  }
}
