import { McpServerManifest, McpTool } from './types';

const TOOLS: McpTool[] = [
  {
    name: 'get_invoice',
    description: 'Retrieve a customer invoice by ID or booking reference. Returns PDF download URL.',
    tier: 'staff', riskLevel: 1,
    inputSchema: { type: 'object',
      properties: {
        invoiceId:  { type: 'string' },
        bookingId:  { type: 'string' },
        customerId: { type: 'string' },
      },
    },
    safetyNote: 'Never return raw card numbers, bank account numbers, or Stripe/payment tokens',
  },
  {
    name: 'get_payment_status',
    description: 'Check whether a payment has been completed, is pending, or has failed.',
    tier: 'staff', riskLevel: 1,
    inputSchema: { type: 'object', required: ['paymentId'],
      properties: { paymentId: { type: 'string' } },
    },
  },
  {
    name: 'send_invoice',
    description: 'Email a PDF invoice to the customer.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['invoiceId'],
      properties: {
        invoiceId:    { type: 'string' },
        recipientEmail:{ type: 'string', format: 'email' },
      },
    },
  },
  {
    name: 'create_refund_request',
    description: 'Initiate a refund request for a payment. Requires staff approval before the refund is processed.',
    tier: 'staff_approval', riskLevel: 4,
    inputSchema: { type: 'object', required: ['paymentId', 'amount', 'reason', 'requestedBy'],
      properties: {
        paymentId:   { type: 'string' },
        amount:      { type: 'number', description: 'Refund amount in cents' },
        reason:      { type: 'string', enum: ['class_cancelled','teacher_no_show','customer_request','billing_error','other'] },
        requestedBy: { type: 'string' },
        notes:       { type: 'string' },
      },
    },
    safetyNote: 'Refund amount cannot exceed the original payment amount',
    tags: ['requires_approval', 'financial_impact'],
  },
  {
    name: 'approve_refund',
    description: 'Approve and process a pending refund request. Admin only.',
    tier: 'admin', riskLevel: 5,
    inputSchema: { type: 'object', required: ['refundRequestId', 'adminId'],
      properties: {
        refundRequestId: { type: 'string' },
        adminId:         { type: 'string' },
        notes:           { type: 'string' },
      },
    },
    safetyNote: 'Processes actual money movement via Stripe. Cannot be reversed once submitted.',
    tags: ['requires_approval', 'financial_impact', 'irreversible'],
  },
  {
    name: 'get_financial_report',
    description: 'Retrieve revenue, refunds, outstanding invoices, and teacher commission summary for a period.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['periodFrom', 'periodTo'],
      properties: {
        periodFrom: { type: 'string', format: 'date' },
        periodTo:   { type: 'string', format: 'date' },
        format:     { type: 'string', enum: ['summary','detailed'], default: 'summary' },
      },
    },
    safetyNote: 'Financial reports are restricted to finance role. Do not return individual customer payment details.',
  },
  {
    name: 'update_pricing',
    description: 'Update class or membership pricing. Admin approval required. Takes effect from specified date.',
    tier: 'admin_destructive', riskLevel: 5,
    inputSchema: { type: 'object', required: ['priceItemId', 'newPriceCents', 'effectiveFrom', 'adminId', 'reason'],
      properties: {
        priceItemId:     { type: 'string' },
        newPriceCents:   { type: 'number' },
        effectiveFrom:   { type: 'string', format: 'date' },
        adminId:         { type: 'string' },
        reason:          { type: 'string' },
        notifyCustomers: { type: 'boolean', default: true },
      },
    },
    safetyNote: 'PRICING CHANGE — affects all future purchases. Verify tax implications. Review membership contracts before reducing recurring prices.',
    tags: ['requires_approval', 'financial_impact'],
  },
  {
    name: 'export_tax_report',
    description: 'Export HST/GST collected and remittable for a filing period.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['periodFrom', 'periodTo', 'jurisdiction'],
      properties: {
        periodFrom:   { type: 'string', format: 'date' },
        periodTo:     { type: 'string', format: 'date' },
        jurisdiction: { type: 'string', enum: ['canada_hst','canada_gst','india_gst','us_state'], default: 'canada_hst' },
        format:       { type: 'string', enum: ['csv','pdf'], default: 'pdf' },
      },
    },
    safetyNote: 'Tax reports are for advisory use only — have a qualified accountant review before filing',
  },
];

export const FINANCE_MCP: McpServerManifest = {
  id:          'finance-mcp',
  slug:        'finance-mcp',
  name:        'Finance MCP',
  description: 'Invoice retrieval, payment status, refund requests, revenue reports, pricing, and tax exports.',
  version:     '1.0.0',
  tools:       TOOLS,
  backingServices: ['ERPNext', 'Stripe', 'Gotenberg (PDF)'],
  availability: 'custom',
  implementationNote: 'ERPNext community MCP exists — strict finance-role allowlist mandatory. Refund and pricing tools require two-step human approval.',
};
