import { McpServerManifest, McpTool } from './types';

const TOOLS: McpTool[] = [
  {
    name: 'create_blog_draft',
    description: 'Generate a yoga blog post draft from a topic brief. Returns structured markdown with SEO metadata.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['topic'],
      properties: {
        topic:        { type: 'string' },
        targetLength: { type: 'number', description: 'Target word count', default: 800 },
        seoKeywords:  { type: 'array', items: { type: 'string' } },
        tone:         { type: 'string', enum: ['educational','inspirational','conversational'], default: 'inspirational' },
        teacherCredit:{ type: 'string', description: 'Teacher name to attribute as author' },
      },
    },
  },
  {
    name: 'publish_blog_post',
    description: 'Publish an approved draft to Ghost/Strapi CMS. Staff approval required.',
    tier: 'staff_approval', riskLevel: 3,
    inputSchema: { type: 'object', required: ['draftId', 'approvedBy'],
      properties: {
        draftId:    { type: 'string' },
        approvedBy: { type: 'string' },
        publishAt:  { type: 'string', format: 'date-time', description: 'Omit to publish immediately' },
        categories: { type: 'array', items: { type: 'string' } },
        tags:       { type: 'array', items: { type: 'string' } },
      },
    },
    safetyNote: 'Published blog posts are public and indexed by search engines',
    tags: ['requires_approval', 'public_facing'],
  },
  {
    name: 'create_email_campaign',
    description: 'Build an email campaign from a template with personalisation fields. Returns draft for review.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['templateId', 'subject', 'segmentId'],
      properties: {
        templateId:    { type: 'string' },
        subject:       { type: 'string' },
        segmentId:     { type: 'string' },
        previewText:   { type: 'string' },
        personalisations: { type: 'object' },
        couponCode:    { type: 'string' },
      },
    },
  },
  {
    name: 'send_test_email',
    description: 'Send a preview of an email campaign to a list of internal test addresses.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['campaignId', 'testEmails'],
      properties: {
        campaignId: { type: 'string' },
        testEmails: { type: 'array', items: { type: 'string', format: 'email' }, maxItems: 10 },
      },
    },
  },
  {
    name: 'send_bulk_email',
    description: 'Send an approved email campaign to the full selected segment. Admin approval required.',
    tier: 'admin', riskLevel: 4,
    inputSchema: { type: 'object', required: ['campaignId', 'approvalTicketId', 'scheduledAt'],
      properties: {
        campaignId:        { type: 'string' },
        approvalTicketId:  { type: 'string' },
        scheduledAt:       { type: 'string', format: 'date-time' },
      },
    },
    safetyNote: 'Bulk email to thousands of recipients. Verify unsubscribe compliance and CASL/CAN-SPAM before sending.',
    tags: ['requires_approval', 'bulk_action'],
  },
  {
    name: 'get_campaign_performance',
    description: 'Retrieve open rate, click-through rate, unsubscribe rate, and conversions for an email campaign.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['campaignId'],
      properties: { campaignId: { type: 'string' } },
    },
  },
  {
    name: 'update_banner',
    description: 'Update a homepage or landing-page promotional banner. Staff approval required.',
    tier: 'staff_approval', riskLevel: 3,
    inputSchema: { type: 'object', required: ['bannerId', 'approvedBy'],
      properties: {
        bannerId:   { type: 'string' },
        approvedBy: { type: 'string' },
        headline:   { type: 'string' },
        ctaText:    { type: 'string' },
        ctaUrl:     { type: 'string' },
        mediaUrl:   { type: 'string' },
        activeFrom: { type: 'string', format: 'date-time' },
        activeUntil:{ type: 'string', format: 'date-time' },
      },
    },
    tags: ['requires_approval', 'public_facing'],
  },
  {
    name: 'get_seo_report',
    description: 'Retrieve current SEO metrics: top landing pages, keyword rankings, and Core Web Vitals summary.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object',
      properties: {
        periodDays: { type: 'number', default: 30 },
        page:       { type: 'string', description: 'Specific page slug to analyse' },
      },
    },
  },
  {
    name: 'manage_newsletter_list',
    description: 'Add, remove, or re-segment subscribers in Listmonk/Mautic mailing lists.',
    tier: 'staff', riskLevel: 3,
    inputSchema: { type: 'object', required: ['action', 'listId'],
      properties: {
        action:     { type: 'string', enum: ['add','remove','move_segment'] },
        listId:     { type: 'string' },
        emails:     { type: 'array', items: { type: 'string', format: 'email' } },
        customerId: { type: 'string', description: 'Use instead of emails for a single customer' },
      },
    },
    safetyNote: 'Never add customers who have not opted in. Always honour unsubscribe status.',
  },
];

export const MARKETING_MCP: McpServerManifest = {
  id:          'marketing-mcp',
  slug:        'marketing-mcp',
  name:        'Marketing MCP',
  description: 'Blog drafting, email campaigns, banners, SEO reports, and newsletter list management.',
  version:     '1.0.0',
  tools:       TOOLS,
  backingServices: ['Ghost CMS', 'Strapi', 'Listmonk', 'Mautic', 'Formbricks'],
  availability: 'custom',
  implementationNote: 'Ghost has a community MCP — review quality before using. Build custom thin adapters for Listmonk and Mautic bulk-send with mandatory approval.',
};
