import {NextRequest} from 'next/server';
import {requireAdmin} from '../../../lib/session-auth';
import {query} from '../../../lib/postgres';
export const dynamic='force-dynamic';
const providerStatuses=new Set(['placeholder','configured','connected','degraded','disabled']);
const stageStatuses=new Set(['placeholder','manual','configured','operational','disabled']);
const contentMediums=new Set(['video','blog','whitepaper','case_study']);
async function workspace(){const r=await query<{id:string}>(`SELECT id FROM marketing_workspace ORDER BY created_at LIMIT 1`);return r.rows[0]?.id}
export async function GET(req:NextRequest){const denied=await requireAdmin(req);if(denied)return denied;const w=await workspace();if(!w)return Response.json({error:'Workspace missing.'},{status:503});const[providers,types,stages,projects,variants,metrics,search,nps,qualityProfiles,evaluations,routes]=await Promise.all([
 query(`SELECT * FROM content_factory_provider WHERE workspace_id=$1 ORDER BY display_name`,[w]),query(`SELECT * FROM content_factory_type ORDER BY display_name`),query(`SELECT * FROM content_factory_stage ORDER BY sort_order`),
 query(`SELECT * FROM content_factory_project WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 100`,[w]),query(`SELECT * FROM content_factory_variant ORDER BY created_at DESC LIMIT 200`),
 query(`SELECT project_id,sum(impressions)::bigint impressions,sum(views)::bigint views,sum(three_second_views)::bigint three_second_views,sum(completions)::bigint completions,sum(rewatches)::bigint rewatches,sum(shares)::bigint shares,sum(clicks)::bigint clicks,sum(conversions)::bigint conversions,sum(spend)::numeric spend,sum(revenue)::numeric revenue FROM content_factory_metric GROUP BY project_id`),
 query(`SELECT * FROM content_factory_search_metadata ORDER BY updated_at DESC`),query(`SELECT project_id,count(*)::int responses,round(avg(score),2) score,round(100.0*(count(*) FILTER(WHERE score>=9)-count(*) FILTER(WHERE score<=6))/nullif(count(*),0),1) nps FROM content_factory_nps GROUP BY project_id`),query(`SELECT * FROM media_quality_profile ORDER BY target_score`),query(`SELECT * FROM media_quality_evaluation ORDER BY created_at DESC LIMIT 100`),query(`SELECT * FROM media_routing_decision ORDER BY created_at DESC LIMIT 100`)]);
 return Response.json({providers:providers.rows,types:types.rows,stages:stages.rows,projects:projects.rows,variants:variants.rows,metrics:metrics.rows,search:search.rows,nps:nps.rows,qualityProfiles:qualityProfiles.rows,evaluations:evaluations.rows,routes:routes.rows});}
export async function POST(req:NextRequest){const denied=await requireAdmin(req);if(denied)return denied;const b=await req.json().catch(()=>null) as any;if(!b)return Response.json({error:'Invalid body.'},{status:400});const w=await workspace();if(!w)return Response.json({error:'Workspace missing.'},{status:503});
 if(b.action==='update_provider'){if(!providerStatuses.has(b.status))return Response.json({error:'Invalid status.'},{status:400});const r=await query(`UPDATE content_factory_provider SET status=$1,selected_model=$2,manual_notes=$3,updated_at=now() WHERE workspace_id=$4 AND provider_key=$5 RETURNING *`,[b.status,b.selectedModel||null,b.notes||'',w,b.providerKey]);return Response.json({provider:r.rows[0]});}
 if(b.action==='update_stage'){if(!stageStatuses.has(b.status))return Response.json({error:'Invalid status.'},{status:400});const r=await query(`UPDATE content_factory_stage SET automation_status=$1,provider_key=$2,manual_instructions=$3,updated_at=now() WHERE stage_key=$4 RETURNING *`,[b.status,b.providerKey||null,b.instructions||'',b.stageKey]);return Response.json({stage:r.rows[0]});}
 if(b.action==='create_project'){if(!b.title||!b.topic||!b.audience)return Response.json({error:'title, topic and audience required.'},{status:400});const medium=contentMediums.has(b.contentMedium)?b.contentMedium:'video';if(medium==='video'&&!b.contentType)return Response.json({error:'contentType (video genre) required for video projects.'},{status:400});const genre=medium==='video'?b.contentType:null,durationSeconds=medium==='video'?(Number(b.durationSeconds)||30):null,aspectRatio=medium==='video'?(b.aspectRatio||'9:16'):null;const r=await query(`INSERT INTO content_factory_project(workspace_id,title,topic,audience,language,culture_religion,content_type,emotion,visual_style,duration_seconds,aspect_ratio,manual_notes,content_medium) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[w,b.title,b.topic,b.audience,b.language||'English',b.culture||null,genre,b.emotion||null,b.visualStyle||null,durationSeconds,aspectRatio,b.notes||'',medium]);await query(`INSERT INTO marketing_event_log(workspace_id,event_name,entity_type,entity_id,actor,outcome) VALUES($1,'content_project.created','content_factory_project',$2,'admin','success')`,[w,r.rows[0].id]);return Response.json({project:r.rows[0]},{status:201});}
 if(b.action==='add_variant'){if(!b.projectId||!b.name||!b.style)return Response.json({error:'projectId, name and style required.'},{status:400});const r=await query(`INSERT INTO content_factory_variant(project_id,variant_name,style,duration_seconds,hook,cta,provider_key,manual_notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[b.projectId,b.name,b.style,Number(b.durationSeconds)||30,b.hook||null,b.cta||null,b.providerKey||null,b.notes||'']);return Response.json({variant:r.rows[0]},{status:201});}
 if(b.action==='save_search'){if(!b.projectId)return Response.json({error:'projectId required.'},{status:400});const r=await query(`INSERT INTO content_factory_search_metadata(project_id,primary_keyword,search_intent,title,description,tags,answer_summary,entity_mentions,citation_urls,geo_target,local_business_cta,manual_notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(project_id) DO UPDATE SET primary_keyword=excluded.primary_keyword,search_intent=excluded.search_intent,title=excluded.title,description=excluded.description,tags=excluded.tags,answer_summary=excluded.answer_summary,entity_mentions=excluded.entity_mentions,citation_urls=excluded.citation_urls,geo_target=excluded.geo_target,local_business_cta=excluded.local_business_cta,manual_notes=excluded.manual_notes,updated_at=now() RETURNING *`,[b.projectId,b.primaryKeyword||null,b.searchIntent||null,b.title||null,b.description||null,b.tags||[],b.answerSummary||null,b.entities||[],b.citations||[],b.geoTarget||null,b.localCta||null,b.notes||'']);return Response.json({search:r.rows[0]});}
 if(b.action==='add_nps'){const score=Number(b.score);if(!Number.isInteger(score)||score<0||score>10)return Response.json({error:'NPS score must be 0-10.'},{status:400});const r=await query(`INSERT INTO content_factory_nps(project_id,respondent_ref,score,feedback,source_channel) VALUES($1,$2,$3,$4,$5) RETURNING *`,[b.projectId||null,b.respondentRef||null,score,b.feedback||null,b.sourceChannel||null]);return Response.json({nps:r.rows[0]},{status:201});}
 if(b.action==='route_media'){if(b.contentMedium&&b.contentMedium!=='video')return Response.json({error:'Media routing (Higgsfield/Kling/FFmpeg pipelines) only applies to video projects.'},{status:400});if(!b.contentType||!['standard','premium','studio'].includes(b.tier))return Response.json({error:'contentType and valid tier required.'},{status:400});const privacy=b.privacy||'hybrid',gpu=Boolean(b.gpuAvailable),urgent=Boolean(b.urgent);let pipeline='open-source-first',provider='local';if(['mathematics','doodle'].includes(b.contentType))pipeline='manim-ffmpeg';else if(['ar_science','interactive_3d'].includes(b.contentType))pipeline='threejs-webxr';else if(b.tier==='studio'||(!gpu&&urgent))pipeline='premium-first',provider='commercial-provider-required';else if(b.tier==='premium')pipeline='hybrid-quality-fallback',provider='local-then-premium';if(privacy==='local_only'){pipeline=['mathematics','doodle'].includes(b.contentType)?'manim-ffmpeg':b.contentType==='interactive_3d'?'threejs-webxr':'open-source-only';provider='local';}const rationale=`${b.contentType} routed to ${pipeline}; tier=${b.tier}, privacy=${privacy}, GPU=${gpu?'available':'unavailable'}, urgent=${urgent}.`;const r=await query(`INSERT INTO media_routing_decision(project_id,content_type,quality_tier,selected_pipeline,selected_provider,factors,status,rationale) VALUES($1,$2,$3,$4,$5,$6,'proposed',$7) RETURNING *`,[b.projectId||null,b.contentType,b.tier,pipeline,provider,JSON.stringify({privacy,gpuAvailable:gpu,urgent,maxCost:b.maxCost||null}),rationale]);return Response.json({route:r.rows[0]},{status:201});}
 if(b.action==='evaluate_quality'){if(!b.variantId||!b.profileId||!b.scores)return Response.json({error:'variantId, profileId and scores required.'},{status:400});const profile=await query<any>(`SELECT * FROM media_quality_profile WHERE id=$1`,[b.profileId]);if(!profile.rowCount)return Response.json({error:'Profile not found.'},{status:404});let weighted=0,total=0;for(const[k,v]of Object.entries(profile.rows[0].weights)){const score=Number(b.scores[k]);if(!Number.isFinite(score)||score<0||score>100)return Response.json({error:`Missing/invalid score: ${k}`},{status:400});weighted+=score*Number(v);total+=Number(v)}weighted=weighted/total;const target=Number(profile.rows[0].target_score),decision=weighted>=target?'pass':weighted>=target-8?'regenerate_local':profile.rows[0].privacy_mode==='local_only'?'human_review':'premium_fallback';const r=await query(`INSERT INTO media_quality_evaluation(variant_id,profile_id,evaluator,scores,weighted_score,decision,evidence) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[b.variantId,b.profileId,b.evaluator||'human',JSON.stringify(b.scores),weighted,decision,JSON.stringify(b.evidence||{})]);return Response.json({evaluation:r.rows[0]},{status:201});}
 return Response.json({error:'Unknown action.'},{status:400});}
