'use client'; import {useEffect,useState} from 'react';
type Row=Record<string,unknown>; type Data={modules:Row[];integrations:Row[];tests:Row[];components:Row[];models:Row[];synthetic:Row[];errors:Row[];features:Row[];testFailures:Row[];testSuites:Row[];testCases:Row[];testJobs:Row[];performanceTargets:Row[]};
export default function Page(){const[d,setD]=useState<Data|null>(null);const[e,setE]=useState('');const load=()=>fetch('/api/admin/module-assurance',{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setD(x)}).catch(x=>setE(x.message));useEffect(()=>{void load()},[]);
 const toggle=async(m:Row)=>{await fetch('/api/admin/module-assurance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({moduleKey:m.module_key,enabled:!m.enabled})});void load()};
 const queueSuite=async(s:Row)=>{setE('');const key=`admin:${String(s.suite_key)}:${crypto.randomUUID()}`;const r=await fetch('/api/admin/module-assurance',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({suiteKey:s.suite_key,targetEnvironment:'local'})});const x=await r.json();if(!r.ok)setE(x.error||'Unable to queue suite');else void load()};
 return <div className="mx-auto max-w-[1500px] space-y-5 p-6"><header className="border-l-4 border-primary-600 pl-4"><h1 className="text-2xl font-bold">Module Assurance</h1><p className="text-sm text-gray-500">Evidence for modules, UI, database keys, integrations, runtimes, models, tests and synthetic reports.</p></header>{e&&<p className="rounded bg-red-50 p-3 text-red-700">{e}</p>}
 <div className="grid gap-3 md:grid-cols-6"><Card k="Modules" v={d?.modules.length}/><Card k="Integrations" v={d?.integrations.length}/><Card k="Runtime components" v={d?.components.length}/><Card k="Models used" v={d?.models.length}/><Card k="Open errors" v={d?.errors.length}/><Card k="Synthetic runs" v={d?.synthetic.length}/></div>
 <Table title="Executable test suites" rows={d?.testSuites||[]} cols={['suite_key','module_key','name','test_level','objective','runner_key','case_count','automatic_enabled','schedule_cron']} action={s=><button disabled={!s.enabled} onClick={()=>queueSuite(s)} className="rounded bg-indigo-600 px-3 py-1 text-xs text-white disabled:opacity-40">Queue manual run</button>}/>
 <Table title="Positive, negative and failure scenarios" rows={d?.testCases||[]} cols={['suite_key','case_key','name','polarity','scenario','expected_result','enabled']}/>
 <Table title="Test execution history" rows={d?.testJobs||[]} cols={['created_at','suite_key','trigger_mode','status','requested_by','target_environment','total_cases','passed_cases','failed_cases','started_at','completed_at']}/>
 <Table title="Capacity and scalability gates" rows={d?.performanceTargets||[]} cols={['target_key','name','concurrent_users','duration_seconds','max_error_rate','p95_latency_ms','min_requests_per_second','scenario_tags','enabled']}/>
 <Table title="Module matrix" rows={d?.modules||[]} cols={['module_key','name','category','runtime_language','lifecycle_status','features','database_objects','objects_with_pk','foreign_keys','passed_tests','failed_tests','last_tested_at']} action={m=><button onClick={()=>toggle(m)} className={`rounded px-2 py-1 text-xs text-white ${m.enabled?'bg-emerald-600':'bg-gray-500'}`}>{m.enabled?'ON':'OFF'}</button>}/>
 <Table title="Integration status" rows={d?.integrations||[]} cols={['integration_key','install_status','config_status','runtime_status','enabled','requires_credentials','endpoint','last_checked_at']}/>
 <Table title="Runtime and language" rows={d?.components||[]} cols={['component_key','name','runtime','component_type','enabled']}/>
 <Table title="Model execution" rows={d?.models||[]} cols={['provider','model_name','capability_codes','enabled','invocations','last_used_at']}/>
 {['sales','customer','admin'].map(s=><Table key={s} title={`${s} features`} rows={(d?.features||[]).filter(f=>f.stakeholder===s)} cols={['module_key','module_name','feature_name','ui_route','api_route','enabled']}/>)}
 <Table title="Test summary" rows={d?.tests||[]} cols={['test_type','status','count']}/><Table title="Blocked and failed tests" rows={d?.testFailures||[]} cols={['module_key','test_type','test_name','status','http_status','error_type','error_message','run_at']}/><Table title="Synthetic data reports" rows={d?.synthetic||[]} cols={['dataset_name','tag','status','record_counts','generated_by','created_at','expires_at']}/><Table title="Runtime/API/DB/agent errors" rows={d?.errors||[]} cols={['component_key','error_code','severity','message','occurrence_count','last_seen_at']}/></div>}
function Card({k,v}:{k:string;v:unknown}){return <div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-gray-500">{k}</div><b className="text-xl">{String(v??0)}</b></div>}
function Table({title,rows,cols,action}:{title:string;rows:Row[];cols:string[];action?:(r:Row)=>React.ReactNode}){return <section className="overflow-hidden rounded-xl border bg-white"><h2 className="p-4 font-semibold">{title} ({rows.length})</h2><div className="max-h-[520px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-gray-50"><tr>{cols.map(c=><th key={c} className="p-2 text-left text-xs">{c.replaceAll('_',' ')}</th>)}{action&&<th>Control</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id||r.module_key||r.integration_key||i)} className="border-t">{cols.map(c=><td key={c} className="max-w-xs truncate p-2 font-mono text-xs">{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}{action&&<td>{action(r)}</td>}</tr>)}</tbody></table></div></section>}
