export type QualityStory={id:string;module:string;actor:string;route:string;objective:string;types:string[];positive:string[];negative:string[];requiredData:string[];status:'automated'|'partial'|'missing'};
export const qualityStories:QualityStory[]=[
 {id:'PUBLIC-CATALOG-001',module:'catalog',actor:'visitor',route:'/catalog',objective:'Discover a yoga service and continue to booking',types:['unit','integration','positive','negative','data','accessibility','uiux'],positive:['catalog loads','service cards have names and actions'],negative:['broken media has fallback','empty results are explained'],requiredData:['synthetic service','tenant'],status:'partial'},
 {id:'BOOKING-001',module:'booking',actor:'customer',route:'/booking',objective:'Select a class, trainer and time and create a booking',types:['unit','integration','e2e','positive','negative','role','authentication','data'],positive:['available slot can be selected'],negative:['past/full slot rejected','anonymous transaction protected'],requiredData:['synthetic customer','trainer','class','slot'],status:'partial'},
 {id:'MEMBERSHIP-001',module:'membership',actor:'customer',route:'/membership',objective:'Compare plans and start membership purchase',types:['integration','positive','negative','accessibility','uiux'],positive:['plan benefits and CTA visible'],negative:['invalid coupon rejected','duplicate subscription prevented'],requiredData:['synthetic plan','price','tax'],status:'partial'},
 {id:'CUSTOMER-AUTH-001',module:'customer',actor:'customer',route:'/customer/login',objective:'Sign in without disclosing account existence',types:['unit','integration','positive','negative','role','authentication','security','accessibility'],positive:['valid credentials establish session'],negative:['invalid credentials fail safely','injection payload rejected'],requiredData:['synthetic customer credential'],status:'partial'},
 {id:'ADMIN-AUTH-001',module:'admin',actor:'anonymous',route:'/admin/operations-center',objective:'Prevent anonymous access to administration',types:['integration','negative','role','authentication','security'],positive:['admin session reaches dashboard'],negative:['anonymous user redirects to login','customer role denied'],requiredData:['synthetic admin','synthetic customer'],status:'automated'},
 {id:'MODEL-OPS-001',module:'ai',actor:'administrator',route:'/admin/operations-center',objective:'Inspect, enable, route and monitor every registered model',types:['integration','positive','negative','data','model','observability'],positive:['model inventory and health available'],negative:['disabled or missing model cannot receive work','timeout enters retry/dead-letter flow'],requiredData:['synthetic prompt','model registry'],status:'partial'},
 {id:'TRAINER-ONBOARD-001',module:'teacher',actor:'trainer',route:'/teacher/register',objective:'Submit identity, skills, services and availability for approval',types:['unit','integration','e2e','positive','negative','role','authentication','data','accessibility'],positive:['complete profile enters review'],negative:['missing consent/qualification rejected'],requiredData:['synthetic trainer','qualification','availability'],status:'missing'},
 {id:'SOCIAL-CAMPAIGN-001',module:'social',actor:'marketer',route:'/admin/marketing-command',objective:'Generate, approve, schedule and publish tenant campaign assets',types:['unit','integration','e2e','positive','negative','role','data','observability'],positive:['approved content schedules'],negative:['unapproved content cannot publish','expired OAuth token refreshes or alerts'],requiredData:['synthetic campaign','asset','channel connection'],status:'partial'},
];
export const qualityDimensions=['unit','integration','e2e','positive','negative','data','role','authentication','security','accessibility','color-blind','uiux','model','observability','performance'];
