'use client';import {useEffect,useState} from 'react';
type Story={id:string;module:string;actor:string;route:string;objective:string;types:string[];positive:string[];negative:string[];requiredData:string[];status:string};type Data={generatedAt:string;dimensions:string[];stories:Story[];run:{stats:Record<string,number>;tests:{title:string;status:string;durationMs:number;error:string}[]};models:{provider:string;model_name:string;capability_codes:string[];enabled:boolean}[];jobs:{status:string;count:number}[];tools:Record<string,string>};
export default function QualityCenter(){const[d,setD]=useState<Data|null>(null);const[e,setE]=useState('');useEffect(()=>{fetch('/api/admin/quality-center',{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setD(x)}).catch(x=>setE(x.message))},[]);const s=d?.run.stats||{};
 return <div className="mx-auto max-w-[1500px] space-y-5 p-6"><header className="border-l-4 border-primary-600 pl-4"><h1 className="text-2xl font-bold">Unified Quality & User Stories</h1><p>Playwright, Chrome CDP, axe, Stagehand/CUA readiness, model coverage and end-to-end gaps.</p></header>{e&&<p className="rounded bg-red-50 p-3 text-red-800">{e}</p>}
 <div className="grid gap-3 md:grid-cols-5"><Card n="Stories" v={d?.stories.length}/><Card n="Automated passed" v={s.expected}/><Card n="Failing" v={s.unexpected}/><Card n="Models" v={d?.models.length}/><Card n="Dimensions" v={d?.dimensions.length}/></div>
 <section className="app-card app-card--platform p-4"><h2 className="font-semibold">Integrated engines</h2><div className="mt-3 grid gap-2 md:grid-cols-5">{Object.entries(d?.tools||{}).map(([k,v])=><div key={k} className="rounded border bg-white p-3"><b>{k}</b><div className="text-xs">{v}</div></div>)}</div></section>
 <section className="overflow-x-auto rounded-xl border bg-white"><h2 className="p-4 font-semibold">Mandatory story matrix</h2><table className="w-full text-sm"><thead><tr>{['ID / module','Actor / route','Objective','Test types','Positive / negative','Data','Status'].map(x=><th className="bg-gray-50 p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{d?.stories.map(x=><tr className="border-t align-top" key={x.id}><td className="p-2"><b>{x.id}</b><div>{x.module}</div></td><td className="p-2">{x.actor}<div className="font-mono text-xs">{x.route}</div></td><td className="p-2">{x.objective}</td><td className="p-2">{x.types.join(', ')}</td><td className="p-2"><b>+</b> {x.positive.join('; ')}<br/><b>−</b> {x.negative.join('; ')}</td><td className="p-2">{x.requiredData.join(', ')}</td><td className="p-2"><Status value={x.status}/></td></tr>)}</tbody></table></section>
 <Table title="Latest browser results" rows={d?.run.tests||[]} cols={['title','status','durationMs','error']}/><Table title="Every registered model" rows={d?.models||[]} cols={['provider','model_name','capability_codes','enabled']}/></div>}
function Card({n,v}:{n:string;v:unknown}){return <div className="app-card app-card--operations p-4"><div className="text-xs uppercase">{n}</div><b className="text-2xl">{String(v??0)}</b></div>}function Status({value}:{value:string}){const c=value==='automated'?'bg-emerald-100 text-emerald-900':value==='missing'?'bg-red-100 text-red-900':'bg-amber-100 text-amber-900';return <span data-status aria-label={`Status ${value}`} className={`rounded px-2 py-1 font-semibold ${c}`}>{value}</span>}function Table({title,rows,cols}:{title:string;rows:any[];cols:string[]}){return <section className="overflow-x-auto rounded-xl border bg-white"><h2 className="p-4 font-semibold">{title} ({rows.length})</h2><table className="w-full text-sm"><thead><tr>{cols.map(c=><th key={c} className="bg-gray-50 p-2 text-left">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{cols.map(c=><td key={c} className="max-w-md p-2 text-xs">{Array.isArray(r[c])?r[c].join(', '):String(r[c]??'')}</td>)}</tr>)}</tbody></table></section>}
