// Platform API Catalog — Seed data for all 36 platforms, 150+ endpoints

export interface ApiOfferingSeed {
  platform: string;
  api_version?: string;
  api_name: string;
  endpoint_path: string;
  http_method: string;
  capability: string;
  category: string;
  auth_type: string;
  required_scopes?: string[];
  required_env_vars?: string[];
  rate_limit_calls?: number;
  rate_limit_window?: string;
  rate_limit_tier?: string;
  implementation_status: string;
  our_api_route?: string;
  is_stable?: boolean;
  requires_review?: boolean;
  notes?: string;
}

export const API_OFFERINGS_SEED: ApiOfferingSeed[] = [
  // ── Facebook Graph API v18.0 ──────────────────────────────────────────────
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/me/feed', http_method: 'POST',
    capability: 'Publish text/link post to page', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['pages_manage_posts', 'pages_read_engagement'],
    rate_limit_calls: 200, rate_limit_window: '1h',
    implementation_status: 'built', our_api_route: '/api/admin/social-intelligence/variants',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/me/photos', http_method: 'POST',
    capability: 'Upload photo to page', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['pages_manage_posts'],
    rate_limit_calls: 200, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/me/videos', http_method: 'POST',
    capability: 'Upload video to page', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['pages_manage_posts'],
    rate_limit_calls: 100, rate_limit_window: '1h',
    implementation_status: 'not_built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/{page-id}/insights', http_method: 'GET',
    capability: 'Fetch page analytics', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['pages_read_engagement'],
    rate_limit_calls: 200, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/{post-id}', http_method: 'GET',
    capability: 'Get post metrics (likes/comments/shares)', category: 'read',
    auth_type: 'oauth2',
    rate_limit_calls: 200, rate_limit_window: '1h',
    implementation_status: 'built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/{comment-id}/likes', http_method: 'POST',
    capability: 'Like a comment', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/me/conversations', http_method: 'GET',
    capability: 'Read page inbox messages', category: 'messaging',
    auth_type: 'oauth2', required_scopes: ['pages_messaging'],
    implementation_status: 'not_built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/me/messages', http_method: 'POST',
    capability: 'Send message reply', category: 'messaging',
    auth_type: 'oauth2', required_scopes: ['pages_messaging'],
    implementation_status: 'not_built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/{post-id}/comments', http_method: 'GET',
    capability: 'Read post comments', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'facebook', api_version: 'v18.0', api_name: 'Graph API',
    endpoint_path: '/{post-id}', http_method: 'DELETE',
    capability: 'Delete a post', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'partial',
  },

  // ── Instagram Graph API v18.0 ─────────────────────────────────────────────
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/me/media', http_method: 'POST',
    capability: 'Create media container (photo/video/reel)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['instagram_content_publish'],
    rate_limit_calls: 50, rate_limit_window: '24h',
    implementation_status: 'partial', requires_review: false,
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/me/media_publish', http_method: 'POST',
    capability: 'Publish created media container', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['instagram_content_publish'],
    rate_limit_calls: 25, rate_limit_window: '24h',
    implementation_status: 'partial',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/me/media', http_method: 'GET',
    capability: 'Get all published media', category: 'read',
    auth_type: 'oauth2', required_scopes: ['instagram_basic'],
    rate_limit_calls: 200, rate_limit_window: '1h',
    implementation_status: 'built',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/{media-id}/insights', http_method: 'GET',
    capability: 'Get media insights (reach/impressions/saves)', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['instagram_manage_insights'],
    implementation_status: 'partial',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/me/insights', http_method: 'GET',
    capability: 'Account-level insights', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['instagram_manage_insights'],
    implementation_status: 'partial',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/{media-id}/comments', http_method: 'GET',
    capability: 'Read post comments', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/{media-id}/replies', http_method: 'POST',
    capability: 'Reply to a comment', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['instagram_manage_comments'],
    implementation_status: 'not_built',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/{comment-id}', http_method: 'DELETE',
    capability: 'Delete a comment', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'instagram', api_version: 'v18.0', api_name: 'Instagram Graph API',
    endpoint_path: '/me/stories', http_method: 'GET',
    capability: 'Get stories (business accounts only)', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Twitter/X API v2 ──────────────────────────────────────────────────────
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/tweets', http_method: 'POST',
    capability: 'Create a tweet (text/image/video/poll)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['tweet.write', 'users.read'],
    rate_limit_calls: 17, rate_limit_window: '15m',
    implementation_status: 'partial', requires_review: true,
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/users/me', http_method: 'GET',
    capability: 'Get authenticated user info', category: 'read',
    auth_type: 'oauth2',
    rate_limit_calls: 25, rate_limit_window: '15m',
    implementation_status: 'built',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/users/{id}/tweets', http_method: 'GET',
    capability: 'Get user timeline', category: 'read',
    auth_type: 'oauth2', required_scopes: ['tweet.read'],
    rate_limit_calls: 1500, rate_limit_window: '15m',
    implementation_status: 'partial',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/tweets/{id}', http_method: 'GET',
    capability: 'Get tweet metrics', category: 'analytics',
    auth_type: 'oauth2',
    rate_limit_calls: 300, rate_limit_window: '15m',
    implementation_status: 'partial',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/tweets/{id}', http_method: 'DELETE',
    capability: 'Delete a tweet', category: 'publish',
    auth_type: 'oauth2',
    rate_limit_calls: 50, rate_limit_window: '15m',
    implementation_status: 'not_built',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/users/{id}/retweets', http_method: 'POST',
    capability: 'Retweet', category: 'publish',
    auth_type: 'oauth2',
    rate_limit_calls: 5, rate_limit_window: '15m',
    implementation_status: 'not_built',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/tweets/reply', http_method: 'POST',
    capability: 'Reply to a tweet', category: 'publish',
    auth_type: 'oauth2',
    rate_limit_calls: 17, rate_limit_window: '15m',
    implementation_status: 'not_built',
  },
  {
    platform: 'x_twitter', api_version: 'v2', api_name: 'Twitter API v2',
    endpoint_path: '/2/tweets/search/recent', http_method: 'GET',
    capability: 'Search recent tweets (keyword monitoring)', category: 'read',
    auth_type: 'oauth2', required_scopes: ['tweet.read'],
    rate_limit_calls: 180, rate_limit_window: '15m',
    implementation_status: 'not_built',
  },

  // ── LinkedIn API ──────────────────────────────────────────────────────────
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/ugcPosts', http_method: 'POST',
    capability: 'Publish post (text/image/video/article)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['w_member_social'],
    rate_limit_calls: 100, rate_limit_window: '24h',
    implementation_status: 'partial',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/me', http_method: 'GET',
    capability: 'Get authenticated member profile', category: 'read',
    auth_type: 'oauth2', required_scopes: ['r_liteprofile'],
    rate_limit_calls: 100, rate_limit_window: '24h',
    implementation_status: 'built',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/organizationAcls', http_method: 'GET',
    capability: 'Get company pages I admin', category: 'read',
    auth_type: 'oauth2', required_scopes: ['r_organization_admin'],
    implementation_status: 'partial',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/specificContent', http_method: 'POST',
    capability: 'Share article/document post', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['w_organization_social'],
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/organizationalEntityFollowerStatistics', http_method: 'GET',
    capability: 'Company page follower stats', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['r_organization_social'],
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/socialActions/{post-urn}/comments', http_method: 'GET',
    capability: 'Read post comments', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/socialActions/{post-urn}/comments', http_method: 'POST',
    capability: 'Comment on post', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin', api_version: 'v2', api_name: 'LinkedIn API',
    endpoint_path: '/v2/ugcPosts/{post-id}', http_method: 'DELETE',
    capability: 'Delete post', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── YouTube Data API v3 ───────────────────────────────────────────────────
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/videos', http_method: 'POST',
    capability: 'Upload video to YouTube', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['https://www.googleapis.com/auth/youtube.upload'],
    rate_limit_calls: 10000, rate_limit_window: '24h', rate_limit_tier: 'quota_units',
    implementation_status: 'partial',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/channels', http_method: 'GET',
    capability: 'Get channel info and stats', category: 'read',
    auth_type: 'oauth2', required_scopes: ['https://www.googleapis.com/auth/youtube.readonly'],
    rate_limit_calls: 10000, rate_limit_window: '24h', rate_limit_tier: 'quota_units',
    implementation_status: 'built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/videos/list', http_method: 'GET',
    capability: 'List/search videos', category: 'read',
    auth_type: 'oauth2',
    rate_limit_calls: 10000, rate_limit_window: '24h', rate_limit_tier: 'quota_units',
    implementation_status: 'built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/analytics/v2/reports', http_method: 'GET',
    capability: 'YouTube Analytics (watch time/CTR)', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['https://www.googleapis.com/auth/yt-analytics.readonly'],
    implementation_status: 'partial',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/playlists', http_method: 'POST',
    capability: 'Create playlist', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/playlistItems', http_method: 'POST',
    capability: 'Add video to playlist', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/commentThreads', http_method: 'GET',
    capability: 'Read video comments', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/comments', http_method: 'POST',
    capability: 'Reply to comment', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['https://www.googleapis.com/auth/youtube.force-ssl'],
    implementation_status: 'not_built',
  },
  {
    platform: 'youtube', api_version: 'v3', api_name: 'YouTube Data API v3',
    endpoint_path: '/youtube/v3/videos/delete', http_method: 'DELETE',
    capability: 'Delete video', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── TikTok Content Posting API ────────────────────────────────────────────
  {
    platform: 'tiktok', api_version: 'v2', api_name: 'TikTok Content Posting API',
    endpoint_path: '/v2/post/publish/video/init', http_method: 'POST',
    capability: 'Initialize video upload', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['video.publish'],
    rate_limit_calls: 600, rate_limit_window: '24h',
    implementation_status: 'partial', requires_review: true,
  },
  {
    platform: 'tiktok', api_version: 'v2', api_name: 'TikTok Content Posting API',
    endpoint_path: '/v2/post/publish/status/fetch', http_method: 'POST',
    capability: 'Check publish status', category: 'read',
    auth_type: 'oauth2',
    rate_limit_calls: 600, rate_limit_window: '24h',
    implementation_status: 'partial',
  },
  {
    platform: 'tiktok', api_version: 'v2', api_name: 'TikTok Research API',
    endpoint_path: '/v2/research/video/query', http_method: 'GET',
    capability: 'Search TikTok videos (Research API)', category: 'read',
    auth_type: 'oauth2', required_scopes: ['research.data.basic'],
    implementation_status: 'not_built', requires_review: true,
  },
  {
    platform: 'tiktok', api_version: 'v2', api_name: 'TikTok Content Posting API',
    endpoint_path: '/v2/user/info', http_method: 'GET',
    capability: 'Get user profile stats', category: 'read',
    auth_type: 'oauth2', required_scopes: ['user.info.basic'],
    rate_limit_calls: 600, rate_limit_window: '24h',
    implementation_status: 'built',
  },
  {
    platform: 'tiktok', api_version: 'v2', api_name: 'TikTok Content Posting API',
    endpoint_path: '/v2/video/list', http_method: 'GET',
    capability: 'Get user video list', category: 'read',
    auth_type: 'oauth2', required_scopes: ['video.list'],
    rate_limit_calls: 600, rate_limit_window: '24h',
    implementation_status: 'partial',
  },

  // ── Pinterest API v5 ──────────────────────────────────────────────────────
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/pins', http_method: 'POST',
    capability: 'Create a pin', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['boards:write', 'pins:write'],
    rate_limit_calls: 100, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/user_account', http_method: 'GET',
    capability: 'Get user account info', category: 'read',
    auth_type: 'oauth2', required_scopes: ['user_accounts:read'],
    rate_limit_calls: 100, rate_limit_window: '1h',
    implementation_status: 'built',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/user_account/analytics', http_method: 'GET',
    capability: 'Account analytics', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['user_accounts:read'],
    rate_limit_calls: 100, rate_limit_window: '1h',
    implementation_status: 'not_built',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/boards', http_method: 'GET',
    capability: 'List user boards', category: 'read',
    auth_type: 'oauth2', required_scopes: ['boards:read'],
    rate_limit_calls: 100, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/boards', http_method: 'POST',
    capability: 'Create board', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['boards:write'],
    implementation_status: 'not_built',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/pins/{pin_id}/analytics', http_method: 'GET',
    capability: 'Pin analytics (impressions/saves/clicks)', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'pinterest', api_version: 'v5', api_name: 'Pinterest API v5',
    endpoint_path: '/v5/pins/{pin_id}', http_method: 'DELETE',
    capability: 'Delete pin', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── WhatsApp Business Cloud API ───────────────────────────────────────────
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{phone-number-id}/messages', http_method: 'POST',
    capability: 'Send text/media/template message', category: 'messaging',
    auth_type: 'bearer_token', required_env_vars: ['WHATSAPP_PHONE_NUMBER_ID', 'WHATSAPP_ACCESS_TOKEN'],
    rate_limit_calls: 1000, rate_limit_window: '1s',
    implementation_status: 'partial',
  },
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{phone-number-id}/message_templates', http_method: 'GET',
    capability: 'Get message templates', category: 'read',
    auth_type: 'bearer_token', required_env_vars: ['WHATSAPP_ACCESS_TOKEN'],
    implementation_status: 'built',
  },
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{waba-id}/message_templates', http_method: 'POST',
    capability: 'Create message template', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built', requires_review: true,
  },
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{waba-id}/phone_numbers', http_method: 'GET',
    capability: 'List phone numbers', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{phone-number-id}/messages/media', http_method: 'POST',
    capability: 'Send image/video/document', category: 'messaging',
    auth_type: 'bearer_token',
    implementation_status: 'partial',
  },
  {
    platform: 'whatsapp_business', api_version: 'v18.0', api_name: 'WhatsApp Business Cloud API',
    endpoint_path: '/{message-id}', http_method: 'GET',
    capability: 'Get message status', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'partial',
  },

  // ── GitHub REST API ───────────────────────────────────────────────────────
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/repos/{owner}/{repo}/releases', http_method: 'POST',
    capability: 'Create release with notes', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['GITHUB_TOKEN'],
    rate_limit_calls: 5000, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/repos/{owner}/{repo}', http_method: 'GET',
    capability: 'Get repo stats (stars/forks/watchers)', category: 'read',
    auth_type: 'bearer_token', required_env_vars: ['GITHUB_TOKEN'],
    rate_limit_calls: 5000, rate_limit_window: '1h',
    implementation_status: 'built',
  },
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/repos/{owner}/{repo}/discussions', http_method: 'POST',
    capability: 'Create discussion', category: 'publish',
    auth_type: 'bearer_token', required_scopes: ['write:discussion'],
    implementation_status: 'not_built',
  },
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/repos/{owner}/{repo}/traffic/views', http_method: 'GET',
    capability: 'Repo traffic analytics', category: 'analytics',
    auth_type: 'bearer_token', required_scopes: ['repo'],
    implementation_status: 'not_built',
  },
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/gists', http_method: 'POST',
    capability: 'Create public gist', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'github', api_version: 'v3', api_name: 'GitHub REST API',
    endpoint_path: '/repos/{owner}/{repo}/releases', http_method: 'GET',
    capability: 'List releases', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },

  // ── Google Business Profile API ───────────────────────────────────────────
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations/{locationId}/localPosts', http_method: 'POST',
    capability: 'Create business post', category: 'publish',
    auth_type: 'oauth2', required_env_vars: ['GOOGLE_BUSINESS_ACCESS_TOKEN'],
    rate_limit_calls: 5000, rate_limit_window: '24h',
    implementation_status: 'partial',
  },
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations/{locationId}/reviews', http_method: 'GET',
    capability: 'Fetch customer reviews', category: 'review',
    auth_type: 'oauth2',
    rate_limit_calls: 5000, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations/{locationId}/reviews/{reviewId}/reply', http_method: 'POST',
    capability: 'Reply to review', category: 'review',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations/{locationId}/localPosts', http_method: 'GET',
    capability: 'List business posts', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'partial',
  },
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations', http_method: 'GET',
    capability: 'List managed locations', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'google_business', api_version: 'v4', api_name: 'Google Business Profile API',
    endpoint_path: '/v4/accounts/{accountId}/locations/{locationId}/reportInsights', http_method: 'GET',
    capability: 'Location performance insights', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Trustpilot Business API ───────────────────────────────────────────────
  {
    platform: 'trustpilot', api_version: 'v1', api_name: 'Trustpilot Business API',
    endpoint_path: '/v1/private/business-units/{businessUnitId}/reviews', http_method: 'GET',
    capability: 'Get business reviews', category: 'review',
    auth_type: 'api_key', required_env_vars: ['TRUSTPILOT_API_KEY', 'TRUSTPILOT_BUSINESS_UNIT_ID'],
    rate_limit_calls: 500, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'trustpilot', api_version: 'v1', api_name: 'Trustpilot Business API',
    endpoint_path: '/v1/private/business-units/{businessUnitId}/reviews/{reviewId}/reply', http_method: 'POST',
    capability: 'Reply to review', category: 'review',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },
  {
    platform: 'trustpilot', api_version: 'v1', api_name: 'Trustpilot Business API',
    endpoint_path: '/v1/private/business-units/{businessUnitId}/invitations', http_method: 'POST',
    capability: 'Send review invitation', category: 'publish',
    auth_type: 'api_key',
    implementation_status: 'partial',
  },
  {
    platform: 'trustpilot', api_version: 'v1', api_name: 'Trustpilot Business API',
    endpoint_path: '/v1/private/business-units/{businessUnitId}', http_method: 'GET',
    capability: 'Get business unit info and score', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'built',
  },
  {
    platform: 'trustpilot', api_version: 'v1', api_name: 'Trustpilot Business API',
    endpoint_path: '/v1/private/business-units/{businessUnitId}/reviews/summaries/aggregate', http_method: 'GET',
    capability: 'Review aggregate stats', category: 'analytics',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },

  // ── Vimeo API ─────────────────────────────────────────────────────────────
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/me/videos', http_method: 'POST',
    capability: 'Upload/import video from URL', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['VIMEO_ACCESS_TOKEN'],
    rate_limit_calls: 100, rate_limit_window: '15m',
    implementation_status: 'partial',
  },
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/me/videos', http_method: 'GET',
    capability: 'List user videos', category: 'read',
    auth_type: 'bearer_token', required_env_vars: ['VIMEO_ACCESS_TOKEN'],
    rate_limit_calls: 250, rate_limit_window: '1h',
    implementation_status: 'built',
  },
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/videos/{video_id}', http_method: 'GET',
    capability: 'Get video stats', category: 'analytics',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/videos/{video_id}', http_method: 'PATCH',
    capability: 'Update video title/description', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/videos/{video_id}', http_method: 'DELETE',
    capability: 'Delete video', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'vimeo', api_version: '3.4', api_name: 'Vimeo API',
    endpoint_path: '/me/projects', http_method: 'POST',
    capability: 'Create showcase/project', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Patreon API v2 ────────────────────────────────────────────────────────
  {
    platform: 'patreon', api_version: 'v2', api_name: 'Patreon API v2',
    endpoint_path: '/api/oauth2/v2/posts', http_method: 'POST',
    capability: 'Create creator post', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['PATREON_ACCESS_TOKEN'],
    rate_limit_calls: 60, rate_limit_window: '1m',
    implementation_status: 'partial',
  },
  {
    platform: 'patreon', api_version: 'v2', api_name: 'Patreon API v2',
    endpoint_path: '/api/oauth2/v2/campaigns/{campaignId}/members', http_method: 'GET',
    capability: 'Get patrons list', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },
  {
    platform: 'patreon', api_version: 'v2', api_name: 'Patreon API v2',
    endpoint_path: '/api/oauth2/v2/posts/{postId}', http_method: 'GET',
    capability: 'Get post stats', category: 'analytics',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'patreon', api_version: 'v2', api_name: 'Patreon API v2',
    endpoint_path: '/api/oauth2/v2/posts/{postId}', http_method: 'PATCH',
    capability: 'Update post', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'patreon', api_version: 'v2', api_name: 'Patreon API v2',
    endpoint_path: '/api/oauth2/v2/campaigns', http_method: 'GET',
    capability: 'Get campaign info', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },

  // ── Medium API ────────────────────────────────────────────────────────────
  {
    platform: 'medium', api_version: 'v1', api_name: 'Medium API',
    endpoint_path: '/v1/users/{userId}/posts', http_method: 'POST',
    capability: 'Publish article', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['MEDIUM_INTEGRATION_TOKEN'],
    implementation_status: 'built',
  },
  {
    platform: 'medium', api_version: 'v1', api_name: 'Medium API',
    endpoint_path: '/v1/me', http_method: 'GET',
    capability: 'Get user profile', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },
  {
    platform: 'medium', api_version: 'v1', api_name: 'Medium API',
    endpoint_path: '/v1/users/{userId}/publications', http_method: 'GET',
    capability: 'List publications', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'partial',
  },
  {
    platform: 'medium', api_version: 'v1', api_name: 'Medium API',
    endpoint_path: '/v1/publications/{publicationId}/posts', http_method: 'POST',
    capability: 'Publish to publication', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Discord API ───────────────────────────────────────────────────────────
  {
    platform: 'discord', api_version: 'v10', api_name: 'Discord API',
    endpoint_path: '/api/v10/channels/{channelId}/messages', http_method: 'POST',
    capability: 'Send message/embed', category: 'messaging',
    auth_type: 'bearer_token', required_env_vars: ['DISCORD_BOT_TOKEN'],
    rate_limit_calls: 5, rate_limit_window: '5s',
    implementation_status: 'built',
  },
  {
    platform: 'discord', api_version: 'v10', api_name: 'Discord Webhook API',
    endpoint_path: '/webhooks/{webhookId}/{webhookToken}', http_method: 'POST',
    capability: 'Send via webhook', category: 'messaging',
    auth_type: 'none', required_env_vars: ['DISCORD_WEBHOOK_URL'],
    rate_limit_calls: 5, rate_limit_window: '5s',
    implementation_status: 'built',
  },
  {
    platform: 'discord', api_version: 'v10', api_name: 'Discord API',
    endpoint_path: '/api/v10/guilds/{guildId}/scheduled-events', http_method: 'POST',
    capability: 'Create server event', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'discord', api_version: 'v10', api_name: 'Discord API',
    endpoint_path: '/api/v10/guilds/{guildId}', http_method: 'GET',
    capability: 'Get server info and member count', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'partial',
  },
  {
    platform: 'discord', api_version: 'v10', api_name: 'Discord API',
    endpoint_path: '/api/v10/channels/{channelId}/threads', http_method: 'POST',
    capability: 'Create thread', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Telegram Bot API ──────────────────────────────────────────────────────
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/sendMessage', http_method: 'POST',
    capability: 'Send text message to channel', category: 'messaging',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID'],
    rate_limit_calls: 30, rate_limit_window: '1s',
    implementation_status: 'built',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/sendPhoto', http_method: 'POST',
    capability: 'Send photo', category: 'messaging',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'partial',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/sendVideo', http_method: 'POST',
    capability: 'Send video', category: 'messaging',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'partial',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/sendDocument', http_method: 'POST',
    capability: 'Send document/file', category: 'messaging',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'not_built',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/getMe', http_method: 'GET',
    capability: 'Verify bot credentials', category: 'auth',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'built',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/getUpdates', http_method: 'GET',
    capability: 'Get channel/group messages', category: 'read',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'partial',
  },
  {
    platform: 'telegram', api_version: 'latest', api_name: 'Telegram Bot API',
    endpoint_path: '/bot{token}/pinChatMessage', http_method: 'POST',
    capability: 'Pin a message', category: 'publish',
    auth_type: 'none', required_env_vars: ['TELEGRAM_BOT_TOKEN'],
    implementation_status: 'not_built',
  },

  // ── Reddit API ────────────────────────────────────────────────────────────
  {
    platform: 'reddit', api_version: 'v1', api_name: 'Reddit API',
    endpoint_path: '/api/submit', http_method: 'POST',
    capability: 'Submit a post (text/link/image/video) to subreddit', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['submit'],
    rate_limit_calls: 60, rate_limit_window: '1m',
    implementation_status: 'not_built',
  },
  {
    platform: 'reddit', api_version: 'v1', api_name: 'Reddit API',
    endpoint_path: '/api/v1/me', http_method: 'GET',
    capability: 'Get authenticated user profile', category: 'read',
    auth_type: 'oauth2', required_scopes: ['identity'],
    implementation_status: 'built',
  },
  {
    platform: 'reddit', api_version: 'v1', api_name: 'Reddit API',
    endpoint_path: '/r/{subreddit}/comments', http_method: 'GET',
    capability: 'Read subreddit comments', category: 'read',
    auth_type: 'oauth2', required_scopes: ['read'],
    rate_limit_calls: 60, rate_limit_window: '1m',
    implementation_status: 'not_built',
  },
  {
    platform: 'reddit', api_version: 'v1', api_name: 'Reddit API',
    endpoint_path: '/api/comment', http_method: 'POST',
    capability: 'Reply to a post or comment', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['submit'],
    implementation_status: 'not_built',
  },
  {
    platform: 'reddit', api_version: 'v1', api_name: 'Reddit API',
    endpoint_path: '/r/{subreddit}/about', http_method: 'GET',
    capability: 'Get subreddit analytics (subscribers/active users)', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Mastodon API ──────────────────────────────────────────────────────────
  {
    platform: 'mastodon', api_version: 'v1', api_name: 'Mastodon REST API',
    endpoint_path: '/api/v1/statuses', http_method: 'POST',
    capability: 'Publish a toot (post with optional media)', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['MASTODON_ACCESS_TOKEN', 'MASTODON_SERVER_URL'],
    rate_limit_calls: 300, rate_limit_window: '5m',
    implementation_status: 'partial',
  },
  {
    platform: 'mastodon', api_version: 'v1', api_name: 'Mastodon REST API',
    endpoint_path: '/api/v1/accounts/verify_credentials', http_method: 'GET',
    capability: 'Verify account credentials', category: 'auth',
    auth_type: 'bearer_token',
    implementation_status: 'built',
  },
  {
    platform: 'mastodon', api_version: 'v1', api_name: 'Mastodon REST API',
    endpoint_path: '/api/v1/timelines/home', http_method: 'GET',
    capability: 'Read home timeline', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'mastodon', api_version: 'v1', api_name: 'Mastodon REST API',
    endpoint_path: '/api/v1/statuses/{id}', http_method: 'DELETE',
    capability: 'Delete a toot', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'mastodon', api_version: 'v1', api_name: 'Mastodon REST API',
    endpoint_path: '/api/v1/notifications', http_method: 'GET',
    capability: 'Get mentions and notifications', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Bluesky AT Protocol ───────────────────────────────────────────────────
  {
    platform: 'bluesky', api_version: 'v1', api_name: 'Bluesky AT Protocol',
    endpoint_path: '/xrpc/com.atproto.repo.createRecord', http_method: 'POST',
    capability: 'Create post (skeet) with optional images', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['BLUESKY_IDENTIFIER', 'BLUESKY_APP_PASSWORD'],
    rate_limit_calls: 5000, rate_limit_window: '1h',
    implementation_status: 'partial',
  },
  {
    platform: 'bluesky', api_version: 'v1', api_name: 'Bluesky AT Protocol',
    endpoint_path: '/xrpc/com.atproto.server.createSession', http_method: 'POST',
    capability: 'Create auth session (login)', category: 'auth',
    auth_type: 'none',
    implementation_status: 'built',
  },
  {
    platform: 'bluesky', api_version: 'v1', api_name: 'Bluesky AT Protocol',
    endpoint_path: '/xrpc/app.bsky.feed.getAuthorFeed', http_method: 'GET',
    capability: 'Get user feed posts', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'bluesky', api_version: 'v1', api_name: 'Bluesky AT Protocol',
    endpoint_path: '/xrpc/com.atproto.repo.deleteRecord', http_method: 'POST',
    capability: 'Delete a post', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'bluesky', api_version: 'v1', api_name: 'Bluesky AT Protocol',
    endpoint_path: '/xrpc/app.bsky.notification.listNotifications', http_method: 'GET',
    capability: 'Get mentions and replies', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Tumblr API ────────────────────────────────────────────────────────────
  {
    platform: 'tumblr', api_version: 'v2', api_name: 'Tumblr API v2',
    endpoint_path: '/v2/blog/{blog-identifier}/posts', http_method: 'POST',
    capability: 'Create a post (text/photo/video/link)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['write'],
    rate_limit_calls: 250, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'tumblr', api_version: 'v2', api_name: 'Tumblr API v2',
    endpoint_path: '/v2/user/info', http_method: 'GET',
    capability: 'Get authenticated user info', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'tumblr', api_version: 'v2', api_name: 'Tumblr API v2',
    endpoint_path: '/v2/blog/{blog-identifier}/posts', http_method: 'GET',
    capability: 'List blog posts', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'tumblr', api_version: 'v2', api_name: 'Tumblr API v2',
    endpoint_path: '/v2/blog/{blog-identifier}/posts/{post-id}', http_method: 'DELETE',
    capability: 'Delete a post', category: 'publish',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Twitch Helix API ──────────────────────────────────────────────────────
  {
    platform: 'twitch', api_version: 'helix', api_name: 'Twitch Helix API',
    endpoint_path: '/helix/users', http_method: 'GET',
    capability: 'Get user/channel info', category: 'read',
    auth_type: 'bearer_token', required_env_vars: ['TWITCH_CLIENT_ID', 'TWITCH_ACCESS_TOKEN'],
    rate_limit_calls: 800, rate_limit_window: '1m',
    implementation_status: 'built',
  },
  {
    platform: 'twitch', api_version: 'helix', api_name: 'Twitch Helix API',
    endpoint_path: '/helix/streams', http_method: 'GET',
    capability: 'Check if channel is live + viewer count', category: 'analytics',
    auth_type: 'bearer_token',
    rate_limit_calls: 800, rate_limit_window: '1m',
    implementation_status: 'partial',
  },
  {
    platform: 'twitch', api_version: 'helix', api_name: 'Twitch Helix API',
    endpoint_path: '/helix/videos', http_method: 'GET',
    capability: 'Get VOD/clip list', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'twitch', api_version: 'helix', api_name: 'Twitch Helix API',
    endpoint_path: '/helix/schedule/segment', http_method: 'POST',
    capability: 'Create a stream schedule segment', category: 'publish',
    auth_type: 'bearer_token', required_scopes: ['channel:manage:schedule'],
    implementation_status: 'not_built',
  },
  {
    platform: 'twitch', api_version: 'helix', api_name: 'Twitch Helix API',
    endpoint_path: '/helix/channels/followers', http_method: 'GET',
    capability: 'Get channel followers count', category: 'analytics',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── SoundCloud API ────────────────────────────────────────────────────────
  {
    platform: 'soundcloud', api_version: 'v1', api_name: 'SoundCloud API',
    endpoint_path: '/tracks', http_method: 'POST',
    capability: 'Upload audio track', category: 'publish',
    auth_type: 'oauth2', required_env_vars: ['SOUNDCLOUD_CLIENT_ID', 'SOUNDCLOUD_ACCESS_TOKEN'],
    rate_limit_calls: 15000, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'soundcloud', api_version: 'v1', api_name: 'SoundCloud API',
    endpoint_path: '/me', http_method: 'GET',
    capability: 'Get user profile and stats', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'soundcloud', api_version: 'v1', api_name: 'SoundCloud API',
    endpoint_path: '/me/tracks', http_method: 'GET',
    capability: 'List my uploaded tracks', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'partial',
  },
  {
    platform: 'soundcloud', api_version: 'v1', api_name: 'SoundCloud API',
    endpoint_path: '/tracks/{id}/comments', http_method: 'GET',
    capability: 'Read track comments', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Dailymotion API ───────────────────────────────────────────────────────
  {
    platform: 'dailymotion', api_version: 'v1', api_name: 'Dailymotion API',
    endpoint_path: '/me/videos', http_method: 'POST',
    capability: 'Upload video', category: 'publish',
    auth_type: 'oauth2', required_env_vars: ['DAILYMOTION_CLIENT_ID', 'DAILYMOTION_ACCESS_TOKEN'],
    rate_limit_calls: 10000, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'dailymotion', api_version: 'v1', api_name: 'Dailymotion API',
    endpoint_path: '/me', http_method: 'GET',
    capability: 'Get authenticated user profile', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'built',
  },
  {
    platform: 'dailymotion', api_version: 'v1', api_name: 'Dailymotion API',
    endpoint_path: '/me/videos', http_method: 'GET',
    capability: 'List my videos', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'partial',
  },
  {
    platform: 'dailymotion', api_version: 'v1', api_name: 'Dailymotion API',
    endpoint_path: '/video/{id}/stats', http_method: 'GET',
    capability: 'Get video analytics (views/likes)', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Snapchat Ads API ──────────────────────────────────────────────────────
  {
    platform: 'snapchat', api_version: 'v1', api_name: 'Snapchat Marketing API',
    endpoint_path: '/v1/adaccounts/{ad_account_id}/campaigns', http_method: 'POST',
    capability: 'Create ad campaign', category: 'campaign',
    auth_type: 'oauth2', required_env_vars: ['SNAPCHAT_CLIENT_ID', 'SNAPCHAT_ACCESS_TOKEN'],
    rate_limit_calls: 1000, rate_limit_window: '1h',
    implementation_status: 'not_built',
  },
  {
    platform: 'snapchat', api_version: 'v1', api_name: 'Snapchat Marketing API',
    endpoint_path: '/v1/adaccounts/{ad_account_id}/campaigns', http_method: 'GET',
    capability: 'List ad campaigns', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'snapchat', api_version: 'v1', api_name: 'Snapchat Marketing API',
    endpoint_path: '/v1/adaccounts/{ad_account_id}/adsquads', http_method: 'GET',
    capability: 'List ad squads (ad sets)', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'snapchat', api_version: 'v1', api_name: 'Snapchat Marketing API',
    endpoint_path: '/v1/adaccounts/{ad_account_id}/stats', http_method: 'GET',
    capability: 'Ad account performance stats', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Yelp Fusion API ───────────────────────────────────────────────────────
  {
    platform: 'yelp', api_version: 'v3', api_name: 'Yelp Fusion API',
    endpoint_path: '/v3/businesses/search', http_method: 'GET',
    capability: 'Search businesses by keyword/location', category: 'read',
    auth_type: 'api_key', required_env_vars: ['YELP_API_KEY'],
    rate_limit_calls: 500, rate_limit_window: '24h',
    implementation_status: 'partial',
  },
  {
    platform: 'yelp', api_version: 'v3', api_name: 'Yelp Fusion API',
    endpoint_path: '/v3/businesses/{id}/reviews', http_method: 'GET',
    capability: 'Get business reviews (up to 3)', category: 'review',
    auth_type: 'api_key',
    rate_limit_calls: 500, rate_limit_window: '24h',
    implementation_status: 'built',
  },
  {
    platform: 'yelp', api_version: 'v3', api_name: 'Yelp Fusion API',
    endpoint_path: '/v3/businesses/{id}', http_method: 'GET',
    capability: 'Get business details and rating', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'built',
  },
  {
    platform: 'yelp', api_version: 'v3', api_name: 'Yelp Fusion API',
    endpoint_path: '/v3/events', http_method: 'GET',
    capability: 'Search local events', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },

  // ── Tripadvisor Partner API ───────────────────────────────────────────────
  {
    platform: 'tripadvisor', api_version: 'v2', api_name: 'Tripadvisor Content API',
    endpoint_path: '/location/{locationId}/reviews', http_method: 'GET',
    capability: 'Get location reviews', category: 'review',
    auth_type: 'api_key', required_env_vars: ['TRIPADVISOR_API_KEY'],
    rate_limit_calls: 5000, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'tripadvisor', api_version: 'v2', api_name: 'Tripadvisor Content API',
    endpoint_path: '/location/{locationId}/details', http_method: 'GET',
    capability: 'Get location details and rating', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },
  {
    platform: 'tripadvisor', api_version: 'v2', api_name: 'Tripadvisor Content API',
    endpoint_path: '/location/search', http_method: 'GET',
    capability: 'Search locations', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },
  {
    platform: 'tripadvisor', api_version: 'v2', api_name: 'Tripadvisor Content API',
    endpoint_path: '/location/{locationId}/photos', http_method: 'GET',
    capability: 'Get location photos', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },

  // ── Apple Podcasts (RSS-based) ────────────────────────────────────────────
  {
    platform: 'apple_podcasts', api_version: 'v1', api_name: 'Apple Podcasts Connect API',
    endpoint_path: '/v1/podcasts/{id}', http_method: 'GET',
    capability: 'Get podcast info from Search API', category: 'read',
    auth_type: 'api_key', required_env_vars: ['APPLE_PODCAST_API_KEY'],
    implementation_status: 'not_built',
    notes: 'Primary distribution via RSS feed submission; analytics via Apple Podcasts Connect dashboard',
  },
  {
    platform: 'apple_podcasts', api_version: 'rss', api_name: 'RSS Feed',
    endpoint_path: '/feed.xml', http_method: 'GET',
    capability: 'Publish episode via RSS feed update', category: 'publish',
    auth_type: 'none',
    implementation_status: 'not_built',
  },
  {
    platform: 'apple_podcasts', api_version: 'v1', api_name: 'Podcast Analytics API',
    endpoint_path: '/podcasts/analytics/trends', http_method: 'GET',
    capability: 'Get podcast play analytics', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Spotify for Podcasters ────────────────────────────────────────────────
  {
    platform: 'spotify', api_version: 'v1', api_name: 'Spotify Web API',
    endpoint_path: '/v1/shows/{id}', http_method: 'GET',
    capability: 'Get podcast show details', category: 'read',
    auth_type: 'oauth2', required_env_vars: ['SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET'],
    rate_limit_calls: 180, rate_limit_window: '30s',
    implementation_status: 'not_built',
  },
  {
    platform: 'spotify', api_version: 'v1', api_name: 'Spotify Web API',
    endpoint_path: '/v1/shows/{id}/episodes', http_method: 'GET',
    capability: 'List podcast episodes', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'spotify', api_version: 'v1', api_name: 'Spotify for Podcasters API',
    endpoint_path: '/shows/{showId}/analytics', http_method: 'GET',
    capability: 'Podcast episode analytics', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'spotify', api_version: 'rss', api_name: 'RSS Feed Distribution',
    endpoint_path: '/podcast-feed.xml', http_method: 'GET',
    capability: 'Publish episode via RSS feed submission', category: 'publish',
    auth_type: 'none',
    implementation_status: 'not_built',
  },

  // ── GitLab API ────────────────────────────────────────────────────────────
  {
    platform: 'gitlab', api_version: 'v4', api_name: 'GitLab REST API',
    endpoint_path: '/projects/{id}/releases', http_method: 'POST',
    capability: 'Create project release', category: 'publish',
    auth_type: 'bearer_token', required_env_vars: ['GITLAB_ACCESS_TOKEN'],
    rate_limit_calls: 2000, rate_limit_window: '1h',
    implementation_status: 'not_built',
  },
  {
    platform: 'gitlab', api_version: 'v4', api_name: 'GitLab REST API',
    endpoint_path: '/projects/{id}', http_method: 'GET',
    capability: 'Get project info and stats', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'gitlab', api_version: 'v4', api_name: 'GitLab REST API',
    endpoint_path: '/projects/{id}/issues', http_method: 'POST',
    capability: 'Create project issue', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'gitlab', api_version: 'v4', api_name: 'GitLab REST API',
    endpoint_path: '/projects/{id}/repository/commits', http_method: 'GET',
    capability: 'Get commit history', category: 'read',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },

  // ── Substack (no official API) ────────────────────────────────────────────
  {
    platform: 'substack', api_version: 'unofficial', api_name: 'Substack Unofficial API',
    endpoint_path: '/api/v1/posts', http_method: 'POST',
    capability: 'Publish newsletter post (unofficial/manual)', category: 'publish',
    auth_type: 'none',
    implementation_status: 'not_built',
    is_stable: false,
    notes: 'No official API. Manual post via Substack web app. RSS feed available for read-only.',
  },
  {
    platform: 'substack', api_version: 'rss', api_name: 'Substack RSS Feed',
    endpoint_path: '/feed', http_method: 'GET',
    capability: 'Read published posts via RSS', category: 'read',
    auth_type: 'none',
    implementation_status: 'partial',
  },
  {
    platform: 'substack', api_version: 'unofficial', api_name: 'Substack Unofficial API',
    endpoint_path: '/api/v1/subscriber_count', http_method: 'GET',
    capability: 'Get subscriber count (unofficial)', category: 'analytics',
    auth_type: 'none',
    implementation_status: 'not_built', is_stable: false,
    notes: 'Unofficial endpoint — may break without warning.',
  },

  // ── Stack Overflow (read-only) ────────────────────────────────────────────
  {
    platform: 'stackoverflow', api_version: '2.3', api_name: 'Stack Exchange API',
    endpoint_path: '/2.3/users/{id}/questions', http_method: 'GET',
    capability: 'List user questions', category: 'read',
    auth_type: 'api_key', required_env_vars: ['STACKOVERFLOW_KEY'],
    rate_limit_calls: 10000, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'stackoverflow', api_version: '2.3', api_name: 'Stack Exchange API',
    endpoint_path: '/2.3/tags/{tag}/info', http_method: 'GET',
    capability: 'Get tag analytics (question count/activity)', category: 'analytics',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },
  {
    platform: 'stackoverflow', api_version: '2.3', api_name: 'Stack Exchange API',
    endpoint_path: '/2.3/search/advanced', http_method: 'GET',
    capability: 'Search questions by tag/keyword', category: 'read',
    auth_type: 'api_key',
    implementation_status: 'not_built',
  },

  // ── Quora (read-only/ads) ─────────────────────────────────────────────────
  {
    platform: 'quora', api_version: 'v1', api_name: 'Quora Ads API',
    endpoint_path: '/v1/campaigns', http_method: 'GET',
    capability: 'List ad campaigns', category: 'campaign',
    auth_type: 'oauth2', required_env_vars: ['QUORA_ACCESS_TOKEN'],
    implementation_status: 'not_built',
    notes: 'Quora content API is read-only for public Q&A. Ads API available for campaign management.',
  },
  {
    platform: 'quora', api_version: 'v1', api_name: 'Quora Ads API',
    endpoint_path: '/v1/campaigns', http_method: 'POST',
    capability: 'Create ad campaign', category: 'campaign',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'quora', api_version: 'v1', api_name: 'Quora Ads API',
    endpoint_path: '/v1/reports/campaigns', http_method: 'GET',
    capability: 'Get campaign performance report', category: 'analytics',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Threads (limited beta API) ────────────────────────────────────────────
  {
    platform: 'threads', api_version: 'v1', api_name: 'Threads API',
    endpoint_path: '/me/threads', http_method: 'POST',
    capability: 'Create a thread post (text/image/video)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['threads_basic', 'threads_content_publish'],
    rate_limit_calls: 250, rate_limit_window: '24h',
    implementation_status: 'not_built', requires_review: true,
    notes: 'Limited beta — Meta approval required. Threads API launched Dec 2023.',
  },
  {
    platform: 'threads', api_version: 'v1', api_name: 'Threads API',
    endpoint_path: '/me', http_method: 'GET',
    capability: 'Get Threads user profile', category: 'read',
    auth_type: 'oauth2', required_scopes: ['threads_basic'],
    implementation_status: 'not_built',
  },
  {
    platform: 'threads', api_version: 'v1', api_name: 'Threads API',
    endpoint_path: '/me/threads', http_method: 'GET',
    capability: 'List my Threads posts', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'threads', api_version: 'v1', api_name: 'Threads API',
    endpoint_path: '/me/threads_publishing_limit', http_method: 'GET',
    capability: 'Check publishing quota/rate limit', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },

  // ── Slack API ─────────────────────────────────────────────────────────────
  {
    platform: 'slack', api_version: 'v1', api_name: 'Slack Web API',
    endpoint_path: '/api/chat.postMessage', http_method: 'POST',
    capability: 'Post message to a Slack channel', category: 'messaging',
    auth_type: 'bearer_token', required_env_vars: ['SLACK_BOT_TOKEN', 'SLACK_CHANNEL_ID'],
    rate_limit_calls: 1, rate_limit_window: '1s',
    implementation_status: 'built',
  },
  {
    platform: 'slack', api_version: 'v1', api_name: 'Slack Web API',
    endpoint_path: '/api/conversations.list', http_method: 'GET',
    capability: 'List workspace channels', category: 'read',
    auth_type: 'bearer_token', required_env_vars: ['SLACK_BOT_TOKEN'],
    implementation_status: 'partial',
  },
  {
    platform: 'slack', api_version: 'v1', api_name: 'Slack Web API',
    endpoint_path: '/api/files.upload', http_method: 'POST',
    capability: 'Upload file/image to channel', category: 'publish',
    auth_type: 'bearer_token',
    implementation_status: 'not_built',
  },
  {
    platform: 'slack', api_version: 'v1', api_name: 'Slack Incoming Webhooks',
    endpoint_path: '/services/{webhook_path}', http_method: 'POST',
    capability: 'Send notification via Slack incoming webhook', category: 'webhook',
    auth_type: 'none', required_env_vars: ['SLACK_WEBHOOK_URL'],
    implementation_status: 'built',
  },

  // ── Dribbble API ──────────────────────────────────────────────────────────
  {
    platform: 'dribbble', api_version: 'v2', api_name: 'Dribbble API v2',
    endpoint_path: '/v2/user', http_method: 'GET',
    capability: 'Get authenticated user profile and stats', category: 'read',
    auth_type: 'oauth2', required_env_vars: ['DRIBBBLE_ACCESS_TOKEN'],
    rate_limit_calls: 60, rate_limit_window: '1m',
    implementation_status: 'built',
  },
  {
    platform: 'dribbble', api_version: 'v2', api_name: 'Dribbble API v2',
    endpoint_path: '/v2/user/shots', http_method: 'GET',
    capability: 'List user shots (portfolio)', category: 'read',
    auth_type: 'oauth2',
    implementation_status: 'not_built',
  },
  {
    platform: 'dribbble', api_version: 'v2', api_name: 'Dribbble API v2',
    endpoint_path: '/v2/shots', http_method: 'POST',
    capability: 'Upload a new shot (design post)', category: 'publish',
    auth_type: 'oauth2', required_scopes: ['upload'],
    implementation_status: 'not_built',
    requires_review: true,
    notes: 'Upload access requires explicit approval from Dribbble.',
  },

  // ── LinkedIn Ads API (additional platform for 36-platform count) ──────────
  {
    platform: 'linkedin_ads', api_version: 'v2', api_name: 'LinkedIn Marketing API',
    endpoint_path: '/v2/adCampaignsV2', http_method: 'POST',
    capability: 'Create LinkedIn ad campaign', category: 'campaign',
    auth_type: 'oauth2', required_scopes: ['rw_ads'],
    rate_limit_calls: 100, rate_limit_window: '24h',
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin_ads', api_version: 'v2', api_name: 'LinkedIn Marketing API',
    endpoint_path: '/v2/adAnalyticsV2', http_method: 'GET',
    capability: 'Campaign performance analytics', category: 'analytics',
    auth_type: 'oauth2', required_scopes: ['r_ads_reporting'],
    implementation_status: 'not_built',
  },
  {
    platform: 'linkedin_ads', api_version: 'v2', api_name: 'LinkedIn Marketing API',
    endpoint_path: '/v2/adCreativesV2', http_method: 'POST',
    capability: 'Create ad creative (image/video)', category: 'campaign',
    auth_type: 'oauth2', required_scopes: ['rw_ads'],
    implementation_status: 'not_built',
  },
];
