// Platform Credentials Seed Data — all 36 platforms
// Defines connector_type, priority, env vars, and setup steps.
// Used by GET /api/admin/platform-credentials/seed

export interface PlatformSetupField {
  name: string;
  label: string;
  type: 'text' | 'password' | 'url' | 'email';
  placeholder?: string;
  help?: string;
  required?: boolean;
}

export interface PlatformSetupStep {
  step_number: number;
  step_title: string;
  step_description: string;
  step_type: 'info' | 'form' | 'oauth' | 'verify' | 'copy_value' | 'open_url' | 'env_var';
  required_fields: PlatformSetupField[];
  action_url?: string;
  action_label?: string;
  env_var_to_set?: string;
  validation_hint?: string;
}

export interface PlatformSeedDef {
  platform: string;
  display_name: string;
  connector_type: 'postiz' | 'custom_connector' | 'manual_only';
  priority: 'high' | 'medium' | 'low';
  required_env_vars: string[];
  optional_env_vars: string[];
  developer_portal_url?: string;
  business_use?: string;
  automation_potential?: string;
  steps: PlatformSetupStep[];
}

export const PLATFORM_SEED_DATA: PlatformSeedDef[] = [
  // ─── FACEBOOK ───────────────────────────────────────────────────────
  {
    platform: 'facebook',
    display_name: 'Facebook / Meta',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['FACEBOOK_APP_ID', 'FACEBOOK_APP_SECRET', 'FACEBOOK_PAGE_ACCESS_TOKEN'],
    optional_env_vars: ['FACEBOOK_WEBHOOK_VERIFY_TOKEN'],
    developer_portal_url: 'https://developers.facebook.com',
    business_use: 'Posts, Page management, Lead Ads',
    automation_potential: 'High — full scheduling via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Meta Developer Account',
        step_description: 'Go to developers.facebook.com and log in with your Facebook account. Accept the developer terms.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com',
        action_label: 'Open Meta for Developers',
      },
      {
        step_number: 2,
        step_title: 'Create a New App',
        step_description: 'Click "Create App". Select "Business" as the app type. Enter your App Name (e.g. "SohamYoga Marketing"). Select your Business Manager account.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com/apps/create/',
        action_label: 'Create App',
      },
      {
        step_number: 3,
        step_title: 'Enter App Credentials',
        step_description: 'Copy the App ID and App Name from your Meta App Dashboard → Settings → Basic.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', placeholder: 'SohamYoga Marketing', required: true },
          { name: 'app_id', label: 'App ID', type: 'text', placeholder: '1234567890', help: 'Found on your App Dashboard', required: true },
        ],
        env_var_to_set: 'FACEBOOK_APP_ID',
      },
      {
        step_number: 4,
        step_title: 'Set App Secret',
        step_description: 'In your App Dashboard → Settings → Basic, copy the App Secret. Add to .env file: FACEBOOK_APP_SECRET=your_secret. Never share App Secret publicly. Rotate if exposed.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'FACEBOOK_APP_SECRET',
        validation_hint: 'Never share App Secret publicly. Rotate if exposed.',
      },
      {
        step_number: 5,
        step_title: 'Add Required Products',
        step_description: 'Add these products to your app: Facebook Login, Instagram Graph API, WhatsApp Business Platform, Messenger Platform (as needed).',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com/apps/',
        action_label: 'Open App Dashboard',
      },
      {
        step_number: 6,
        step_title: 'Configure OAuth Redirect URI',
        step_description: 'Add this exact URL to Valid OAuth Redirect URIs in Facebook Login settings.',
        step_type: 'form',
        required_fields: [
          { name: 'webhook_url', label: 'Your Callback URL', type: 'url', placeholder: 'https://yoursite.com/api/auth/facebook/callback', help: 'Add this exact URL to Valid OAuth Redirect URIs in Facebook Login settings', required: true },
        ],
      },
      {
        step_number: 7,
        step_title: 'Set Page Access Token',
        step_description: 'Generate a long-lived Page Access Token via Graph API Explorer or Meta Business Suite. Set FACEBOOK_PAGE_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'FACEBOOK_PAGE_ACCESS_TOKEN',
      },
      {
        step_number: 8,
        step_title: 'Test Connection',
        step_description: 'Click "Test Connection" to verify your Facebook credentials are working.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your page name and follower count',
      },
    ],
  },
  // ─── INSTAGRAM ──────────────────────────────────────────────────────
  {
    platform: 'instagram',
    display_name: 'Instagram',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['FACEBOOK_APP_ID', 'FACEBOOK_APP_SECRET', 'FACEBOOK_PAGE_ACCESS_TOKEN', 'INSTAGRAM_ACCOUNT_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.facebook.com',
    business_use: 'Feed posts, Reels, Stories, Analytics',
    automation_potential: 'High — full scheduling via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Complete Facebook/Meta Setup First',
        step_description: 'Instagram Graph API requires a Meta App. Complete the Facebook platform setup first before continuing here.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 2,
        step_title: 'Connect Instagram Business Account',
        step_description: 'In Meta Business Suite, connect your Instagram Business or Creator account to your Facebook Page. Both accounts must be linked for Instagram Graph API access.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://business.facebook.com/settings',
        action_label: 'Open Meta Business Suite',
      },
      {
        step_number: 3,
        step_title: 'Enable Instagram Product',
        step_description: 'In your Meta App Dashboard, add "Instagram Graph API" as a product. Under Instagram API setup, connect your Instagram business account.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com/apps/',
        action_label: 'Open App Dashboard',
      },
      {
        step_number: 4,
        step_title: 'Set Instagram Account ID',
        step_description: 'Use Graph API to find your Instagram Account ID: GET /me/accounts then get the instagram_business_account id. Set INSTAGRAM_ACCOUNT_ID in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'INSTAGRAM_ACCOUNT_ID',
        validation_hint: 'Format: 17841xxxxxxxxxx (a large numeric string)',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Test that your Instagram account is accessible via the Graph API.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Instagram username and follower count',
      },
    ],
  },
  // ─── THREADS ────────────────────────────────────────────────────────
  {
    platform: 'threads',
    display_name: 'Threads (Meta)',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['FACEBOOK_APP_ID', 'FACEBOOK_APP_SECRET', 'THREADS_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.facebook.com',
    business_use: 'Text posts, engagement, brand voice',
    automation_potential: 'Medium — via Meta Threads API',
    steps: [
      {
        step_number: 1,
        step_title: 'Threads API Access',
        step_description: 'Threads API is managed through Meta. You need an existing Meta App. Ensure your Facebook/Meta setup is complete.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 2,
        step_title: 'Add Threads Product',
        step_description: 'In your Meta App Dashboard, add the "Threads API" product. This is a separate product from Instagram.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com/apps/',
        action_label: 'Open App Dashboard',
      },
      {
        step_number: 3,
        step_title: 'Set Threads Access Token',
        step_description: 'Complete OAuth flow for Threads. Set THREADS_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'THREADS_ACCESS_TOKEN',
      },
      {
        step_number: 4,
        step_title: 'Test Connection',
        step_description: 'Verify your Threads credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Threads profile info',
      },
    ],
  },
  // ─── WHATSAPP BUSINESS ───────────────────────────────────────────────
  {
    platform: 'whatsapp_business',
    display_name: 'WhatsApp Business',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['WHATSAPP_PHONE_NUMBER_ID', 'WHATSAPP_ACCESS_TOKEN'],
    optional_env_vars: ['WHATSAPP_BUSINESS_ACCOUNT_ID', 'WHATSAPP_WEBHOOK_VERIFY_TOKEN'],
    developer_portal_url: 'https://developers.facebook.com',
    business_use: 'Customer messaging, order confirmations, broadcasts',
    automation_potential: 'High — automated notifications and campaigns',
    steps: [
      {
        step_number: 1,
        step_title: 'Prerequisites',
        step_description: 'You need: (1) A Meta Developer Account (set up via Facebook steps above), (2) A verified Business Manager account, (3) A phone number NOT already registered with WhatsApp personal.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 2,
        step_title: 'Add WhatsApp to Meta App',
        step_description: 'In your Meta Developer App → Add Product → WhatsApp Business Platform. Follow the setup wizard.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.facebook.com/apps/',
        action_label: 'Open Meta App',
      },
      {
        step_number: 3,
        step_title: 'Get Test Phone Number',
        step_description: 'Meta provides a free test phone number for development. For production, add and verify your real business phone number. Verification requires receiving an SMS or call.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 4,
        step_title: 'Enter WhatsApp Credentials',
        step_description: 'Enter your Phone Number ID and Business Account ID from the WhatsApp Getting Started page in Meta App Dashboard.',
        step_type: 'form',
        required_fields: [
          { name: 'phone_number_id', label: 'Phone Number ID', type: 'text', help: 'Found in WhatsApp → Getting Started in Meta App Dashboard', required: true },
          { name: 'wa_business_account_id', label: 'WhatsApp Business Account ID', type: 'text', required: true },
        ],
        env_var_to_set: 'WHATSAPP_PHONE_NUMBER_ID',
      },
      {
        step_number: 5,
        step_title: 'Set Access Token',
        step_description: 'Use System User Token from Meta Business Settings → System Users → Generate Token. Select whatsapp_business_messaging and whatsapp_business_management permissions.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'WHATSAPP_ACCESS_TOKEN',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Test your WhatsApp Business API connection.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Will attempt to send a test message to a pre-configured test number',
      },
    ],
  },
  // ─── TWITTER / X ────────────────────────────────────────────────────
  {
    platform: 'x_twitter',
    display_name: 'X / Twitter',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['TWITTER_CLIENT_ID', 'TWITTER_CLIENT_SECRET', 'TWITTER_BEARER_TOKEN', 'TWITTER_ACCESS_TOKEN', 'TWITTER_ACCESS_TOKEN_SECRET'],
    optional_env_vars: [],
    developer_portal_url: 'https://developer.twitter.com',
    business_use: 'Tweets, threads, analytics',
    automation_potential: 'High — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Apply for Twitter Developer Account',
        step_description: 'Go to developer.twitter.com. Click "Sign up" for a developer account. Fill in use case (Marketing automation for business). Required: phone number on account.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developer.twitter.com/en/portal/petition/essential/basic-info',
        action_label: 'Open Twitter Developer Portal',
      },
      {
        step_number: 2,
        step_title: 'Complete Developer Application',
        step_description: 'Describe your use case honestly: "Scheduling and publishing social media posts for a yoga/wellness business. Reading analytics. Not scraping user data." Approval usually takes 1-3 business days.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Create a Project and App',
        step_description: 'After approval: Create a Project → Create an App within it. Select "Read and Write" permissions. Enable OAuth 2.0 with PKCE.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developer.twitter.com/en/portal/projects-and-apps',
        action_label: 'Create App',
      },
      {
        step_number: 4,
        step_title: 'Enter API Credentials',
        step_description: 'Copy your App Name and Client ID (OAuth 2.0) from the Twitter Developer Portal.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID (OAuth 2.0)', type: 'text', required: true },
        ],
        env_var_to_set: 'TWITTER_CLIENT_ID',
      },
      {
        step_number: 5,
        step_title: 'Set Client Secret',
        step_description: 'Copy Client Secret from Twitter Developer Portal → Your App → Keys and Tokens. Set TWITTER_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITTER_CLIENT_SECRET',
      },
      {
        step_number: 6,
        step_title: 'Set Bearer Token',
        step_description: 'Generate Bearer Token from App → Keys and Tokens → Bearer Token. Set TWITTER_BEARER_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITTER_BEARER_TOKEN',
      },
      {
        step_number: 7,
        step_title: 'Set Access Token',
        step_description: 'Generate Access Token from App → Keys and Tokens (requires Read+Write permission). Set TWITTER_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITTER_ACCESS_TOKEN',
      },
      {
        step_number: 8,
        step_title: 'Set Access Token Secret',
        step_description: 'Set TWITTER_ACCESS_TOKEN_SECRET in your .env file (generated alongside the Access Token).',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITTER_ACCESS_TOKEN_SECRET',
      },
      {
        step_number: 9,
        step_title: 'Test Connection',
        step_description: 'Verify your Twitter/X credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Twitter handle and follower count',
      },
    ],
  },
  // ─── LINKEDIN ───────────────────────────────────────────────────────
  {
    platform: 'linkedin',
    display_name: 'LinkedIn',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET', 'LINKEDIN_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.linkedin.com/developers',
    business_use: 'Professional posts, B2B leads, company page',
    automation_potential: 'High — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create LinkedIn Developer Application',
        step_description: 'Go to linkedin.com/developers. Click "Create App". Fill in App Name, LinkedIn Page (your company page), and App Logo. Agree to API Terms.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.linkedin.com/developers/apps/new',
        action_label: 'Open LinkedIn Developers',
      },
      {
        step_number: 2,
        step_title: 'Request Required Permissions',
        step_description: 'Under Products tab, request access to: "Share on LinkedIn" (for posting), "Marketing Developer Platform" (for ads and analytics). Some permissions require LinkedIn review.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Enter App Credentials',
        step_description: 'Copy your App Name and Client ID from the LinkedIn Developer Application.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID', type: 'text', placeholder: '86xxxxxx', required: true },
        ],
        env_var_to_set: 'LINKEDIN_CLIENT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Client Secret',
        step_description: 'Set LINKEDIN_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'LINKEDIN_CLIENT_SECRET',
      },
      {
        step_number: 5,
        step_title: 'Configure OAuth Redirect URL',
        step_description: 'Add your redirect URL to Authorized Redirect URLs in app settings.',
        step_type: 'form',
        required_fields: [
          { name: 'redirect_url', label: 'Redirect URL', type: 'url', placeholder: 'https://yoursite.com/api/auth/linkedin/callback', required: true },
        ],
      },
      {
        step_number: 6,
        step_title: 'Set Access Token',
        step_description: 'Complete OAuth 2.0 flow to get an access token. Set LINKEDIN_ACCESS_TOKEN. Tokens expire in 60 days — refresh token lasts 1 year.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'LINKEDIN_ACCESS_TOKEN',
      },
      {
        step_number: 7,
        step_title: 'Test Connection',
        step_description: 'Verify your LinkedIn credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your LinkedIn profile info',
      },
    ],
  },
  // ─── TIKTOK ─────────────────────────────────────────────────────────
  {
    platform: 'tiktok',
    display_name: 'TikTok',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['TIKTOK_CLIENT_KEY', 'TIKTOK_CLIENT_SECRET', 'TIKTOK_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.tiktok.com',
    business_use: 'Short video posts, trending content',
    automation_potential: 'High — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create TikTok Developer Account',
        step_description: 'Go to developers.tiktok.com. Log in with your TikTok account. Accept developer terms.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.tiktok.com',
        action_label: 'Open TikTok for Developers',
      },
      {
        step_number: 2,
        step_title: 'Create an App',
        step_description: 'Click "Create App". Select "Web" or "Desktop" app type. Fill in App Name, description, website URL. Submit for review — approval takes 1-7 days.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.tiktok.com/apps/',
        action_label: 'Create App',
      },
      {
        step_number: 3,
        step_title: 'Request Content Posting API',
        step_description: 'In your app settings, add the "Content Posting API" product. This requires additional approval from TikTok and a business use case description.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 4,
        step_title: 'Enter App Credentials',
        step_description: 'Copy Client Key from TikTok Developer Portal.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client Key', type: 'text', required: true },
        ],
        env_var_to_set: 'TIKTOK_CLIENT_KEY',
      },
      {
        step_number: 5,
        step_title: 'Set Client Secret',
        step_description: 'Set TIKTOK_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TIKTOK_CLIENT_SECRET',
      },
      {
        step_number: 6,
        step_title: 'Set Access Token',
        step_description: 'Complete OAuth 2.0 flow via TikTok Login Kit to get user access token. Set TIKTOK_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TIKTOK_ACCESS_TOKEN',
      },
      {
        step_number: 7,
        step_title: 'Test Connection',
        step_description: 'Verify your TikTok credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your TikTok account info',
      },
    ],
  },
  // ─── YOUTUBE ────────────────────────────────────────────────────────
  {
    platform: 'youtube',
    display_name: 'YouTube',
    connector_type: 'postiz',
    priority: 'high',
    required_env_vars: ['YOUTUBE_CLIENT_ID', 'YOUTUBE_CLIENT_SECRET', 'YOUTUBE_API_KEY', 'YOUTUBE_REFRESH_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://console.cloud.google.com',
    business_use: 'Video uploads, channel management, analytics',
    automation_potential: 'High — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Open Google Cloud Console',
        step_description: 'Go to console.cloud.google.com. Create a new Project (e.g. "SohamYoga Marketing").',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://console.cloud.google.com',
        action_label: 'Open Google Cloud',
      },
      {
        step_number: 2,
        step_title: 'Enable YouTube Data API v3',
        step_description: 'In APIs & Services → Library, search for "YouTube Data API v3" and enable it.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://console.cloud.google.com/apis/library/youtube.googleapis.com',
        action_label: 'Enable API',
      },
      {
        step_number: 3,
        step_title: 'Create OAuth 2.0 Credentials',
        step_description: 'Go to APIs & Services → Credentials → Create Credentials → OAuth Client ID. Select "Web application". Add your redirect URI.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://console.cloud.google.com/apis/credentials',
        action_label: 'Create Credentials',
      },
      {
        step_number: 4,
        step_title: 'Enter Credentials',
        step_description: 'Copy your Client ID from Google Cloud Console.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'Project Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID', type: 'text', placeholder: 'xxx.apps.googleusercontent.com', required: true },
        ],
        env_var_to_set: 'YOUTUBE_CLIENT_ID',
      },
      {
        step_number: 5,
        step_title: 'Set Client Secret',
        step_description: 'Set YOUTUBE_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'YOUTUBE_CLIENT_SECRET',
      },
      {
        step_number: 6,
        step_title: 'Set API Key (for public data)',
        step_description: 'Create API Key in Credentials for reading public YouTube data. Set YOUTUBE_API_KEY in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'YOUTUBE_API_KEY',
      },
      {
        step_number: 7,
        step_title: 'Set Refresh Token',
        step_description: 'Complete OAuth consent flow once to get refresh token. Use Google OAuth Playground (oauth.com/playground) to generate. Set YOUTUBE_REFRESH_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'YOUTUBE_REFRESH_TOKEN',
      },
      {
        step_number: 8,
        step_title: 'Test Connection',
        step_description: 'Verify your YouTube credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your YouTube channel info',
      },
    ],
  },
  // ─── PINTEREST ──────────────────────────────────────────────────────
  {
    platform: 'pinterest',
    display_name: 'Pinterest',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['PINTEREST_APP_ID', 'PINTEREST_APP_SECRET', 'PINTEREST_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.pinterest.com',
    business_use: 'Pins, boards, visual marketing',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Pinterest Business Account',
        step_description: 'If not already done, convert your Pinterest account to a Business account at business.pinterest.com.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://business.pinterest.com',
        action_label: 'Open Pinterest Business',
      },
      {
        step_number: 2,
        step_title: 'Create Pinterest App',
        step_description: 'Go to developers.pinterest.com/apps. Click "Create app". Fill in app name, description, and website URL.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.pinterest.com/apps/',
        action_label: 'Open Pinterest Developers',
      },
      {
        step_number: 3,
        step_title: 'Request API Access',
        step_description: 'New apps start in sandbox mode. To publish to real boards, request approval: In your app → Request production access. Describe your use case.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 4,
        step_title: 'Enter App Credentials',
        step_description: 'Copy App ID from Pinterest Developers.',
        step_type: 'form',
        required_fields: [
          { name: 'app_id', label: 'App ID', type: 'text', required: true },
        ],
        env_var_to_set: 'PINTEREST_APP_ID',
      },
      {
        step_number: 5,
        step_title: 'Set App Secret',
        step_description: 'Set PINTEREST_APP_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'PINTEREST_APP_SECRET',
      },
      {
        step_number: 6,
        step_title: 'Set Access Token',
        step_description: 'Use OAuth 2.0 to get access token with scopes: boards:read, boards:write, pins:read, pins:write. Set PINTEREST_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'PINTEREST_ACCESS_TOKEN',
      },
      {
        step_number: 7,
        step_title: 'Test Connection',
        step_description: 'Verify your Pinterest credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Pinterest account info',
      },
    ],
  },
  // ─── GITHUB ─────────────────────────────────────────────────────────
  {
    platform: 'github',
    display_name: 'GitHub',
    connector_type: 'custom_connector',
    priority: 'medium',
    required_env_vars: ['GITHUB_TOKEN', 'GITHUB_OWNER'],
    optional_env_vars: ['GITHUB_REPO'],
    developer_portal_url: 'https://github.com/settings/tokens',
    business_use: 'Content publishing via GitHub Pages, CI/CD integration',
    automation_potential: 'Medium — custom integration',
    steps: [
      {
        step_number: 1,
        step_title: 'Create GitHub Account',
        step_description: 'Create or log into github.com with your business email. Verify your email address.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://github.com/join',
        action_label: 'Join GitHub',
      },
      {
        step_number: 2,
        step_title: 'Create Personal Access Token',
        step_description: 'Go to Settings → Developer settings → Personal access tokens → Tokens (classic). Click "Generate new token". Select scopes: repo, write:packages, read:org, workflow.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://github.com/settings/tokens/new',
        action_label: 'Create Token',
      },
      {
        step_number: 3,
        step_title: 'Enter GitHub Details',
        step_description: 'Enter your GitHub username/org and primary repository name.',
        step_type: 'form',
        required_fields: [
          { name: 'github_owner', label: 'GitHub Username or Org', type: 'text', placeholder: 'yourusername', required: true },
          { name: 'github_repo', label: 'Primary Repository', type: 'text', placeholder: 'your-repo-name', required: true },
        ],
        env_var_to_set: 'GITHUB_OWNER',
      },
      {
        step_number: 4,
        step_title: 'Set GitHub Token',
        step_description: 'Paste your Personal Access Token. Never commit this to git — use .env file only. Set GITHUB_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'GITHUB_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your GitHub credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your GitHub user info',
      },
    ],
  },
  // ─── GITLAB ─────────────────────────────────────────────────────────
  {
    platform: 'gitlab',
    display_name: 'GitLab',
    connector_type: 'custom_connector',
    priority: 'low',
    required_env_vars: ['GITLAB_TOKEN', 'GITLAB_PROJECT_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://gitlab.com/-/profile/personal_access_tokens',
    business_use: 'CI/CD, content hosting',
    automation_potential: 'Low — niche use case',
    steps: [
      {
        step_number: 1,
        step_title: 'Create GitLab Account',
        step_description: 'Create or log into gitlab.com. Verify your email.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://gitlab.com/users/sign_up',
        action_label: 'Join GitLab',
      },
      {
        step_number: 2,
        step_title: 'Create Access Token',
        step_description: 'Go to Profile → Access Tokens. Create a new token with scopes: api, read_api, read_repository, write_repository.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://gitlab.com/-/profile/personal_access_tokens',
        action_label: 'Create Token',
      },
      {
        step_number: 3,
        step_title: 'Enter GitLab Details',
        step_description: 'Enter your GitLab Project ID (found in Project → Settings → General).',
        step_type: 'form',
        required_fields: [
          { name: 'gitlab_project_id', label: 'Project ID', type: 'text', help: 'Found in Project → Settings → General', required: true },
        ],
        env_var_to_set: 'GITLAB_PROJECT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set GitLab Token',
        step_description: 'Set GITLAB_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'GITLAB_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your GitLab credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your GitLab user info',
      },
    ],
  },
  // ─── GOOGLE BUSINESS PROFILE ─────────────────────────────────────────
  {
    platform: 'google_business',
    display_name: 'Google Business Profile',
    connector_type: 'custom_connector',
    priority: 'high',
    required_env_vars: ['GOOGLE_BUSINESS_ACCOUNT_ID', 'GOOGLE_BUSINESS_ACCESS_TOKEN'],
    optional_env_vars: ['GOOGLE_BUSINESS_LOCATION_ID'],
    developer_portal_url: 'https://business.google.com',
    business_use: 'Google Maps listing, reviews, local SEO',
    automation_potential: 'Medium — review management and posts',
    steps: [
      {
        step_number: 1,
        step_title: 'Claim Your Business on Google',
        step_description: 'Go to business.google.com and claim/verify your business. Verification via postcard, phone, or email (varies by business type).',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://business.google.com',
        action_label: 'Open Google Business',
      },
      {
        step_number: 2,
        step_title: 'Enable My Business API',
        step_description: 'In Google Cloud Console (same project as YouTube if applicable), enable the "Google My Business API" and "Business Profile Performance API".',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://console.cloud.google.com/apis/library/mybusiness.googleapis.com',
        action_label: 'Enable API',
      },
      {
        step_number: 3,
        step_title: 'Enter Business Details',
        step_description: 'Enter your Business Account ID and Location ID from the Business Profile API.',
        step_type: 'form',
        required_fields: [
          { name: 'business_account_id', label: 'Business Account ID', type: 'text', help: 'From Business Profile API: GET accounts/. Format: accounts/123456', required: true },
          { name: 'location_id', label: 'Location ID', type: 'text', help: 'GET accounts/{accountId}/locations. Format: locations/789', required: true },
        ],
        env_var_to_set: 'GOOGLE_BUSINESS_ACCOUNT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Access Token',
        step_description: 'Reuse Google OAuth credentials from YouTube setup if same project. Needs businessprofile scope. Set GOOGLE_BUSINESS_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'GOOGLE_BUSINESS_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Google Business credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your business location info',
      },
    ],
  },
  // ─── TELEGRAM ───────────────────────────────────────────────────────
  {
    platform: 'telegram',
    display_name: 'Telegram',
    connector_type: 'custom_connector',
    priority: 'medium',
    required_env_vars: ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://t.me/botfather',
    business_use: 'Channel broadcasts, customer notifications',
    automation_potential: 'Medium — bot-based automation',
    steps: [
      {
        step_number: 1,
        step_title: 'Create a Telegram Bot',
        step_description: 'Open Telegram and search for @BotFather. Send /newbot. Choose a name and username (must end in "bot"). BotFather will give you an API token.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://t.me/botfather',
        action_label: 'Open BotFather',
      },
      {
        step_number: 2,
        step_title: 'Enter Bot Details',
        step_description: 'Enter your Telegram bot username.',
        step_type: 'form',
        required_fields: [
          { name: 'bot_username', label: 'Bot Username', type: 'text', placeholder: 'YourBrandBot', required: true },
        ],
      },
      {
        step_number: 3,
        step_title: 'Set Bot Token',
        step_description: 'Copy the token from BotFather (format: 123456789:ABCdef...). Keep secret — anyone with this can control your bot. Set TELEGRAM_BOT_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TELEGRAM_BOT_TOKEN',
      },
      {
        step_number: 4,
        step_title: 'Get Chat/Channel ID',
        step_description: 'For a channel: Add your bot as an admin to the channel. Send a message to the channel. Call https://api.telegram.org/bot{TOKEN}/getUpdates to find the chat_id (negative number for channels).',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 5,
        step_title: 'Enter Channel/Group ID',
        step_description: 'Enter your Telegram channel or group chat ID.',
        step_type: 'form',
        required_fields: [
          { name: 'chat_id', label: 'Chat/Channel ID', type: 'text', placeholder: '-1001234567890', required: true },
        ],
        env_var_to_set: 'TELEGRAM_CHAT_ID',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Telegram bot.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Will send a test message to your channel',
      },
    ],
  },
  // ─── DISCORD ────────────────────────────────────────────────────────
  {
    platform: 'discord',
    display_name: 'Discord',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['DISCORD_WEBHOOK_URL'],
    optional_env_vars: ['DISCORD_BOT_TOKEN'],
    developer_portal_url: 'https://discord.com/developers/applications',
    business_use: 'Community management, announcements',
    automation_potential: 'Medium — webhook-based posting',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Discord Application',
        step_description: 'Go to discord.com/developers/applications. Click "New Application". Name it (e.g. "SohamYoga Bot").',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://discord.com/developers/applications',
        action_label: 'Open Discord Developers',
      },
      {
        step_number: 2,
        step_title: 'Create a Bot (Optional)',
        step_description: 'In your Application → Bot → Add Bot. Enable "Server Members Intent" and "Message Content Intent" under Privileged Gateway Intents.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Set Bot Token (Optional)',
        step_description: 'If using a bot, set DISCORD_BOT_TOKEN in your .env file. Reset token if already revealed. This is highly sensitive.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'DISCORD_BOT_TOKEN',
      },
      {
        step_number: 4,
        step_title: 'Create Webhook (Recommended)',
        step_description: 'For simpler posting (no bot needed), go to your Discord Server → Channel Settings → Integrations → Webhooks → Create Webhook. Copy the webhook URL.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 5,
        step_title: 'Set Webhook URL',
        step_description: 'Set DISCORD_WEBHOOK_URL in your .env file. Format: https://discord.com/api/webhooks/...',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'DISCORD_WEBHOOK_URL',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Discord webhook.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Will post a test message to the configured channel',
      },
    ],
  },
  // ─── REDDIT ─────────────────────────────────────────────────────────
  {
    platform: 'reddit',
    display_name: 'Reddit',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['REDDIT_CLIENT_ID', 'REDDIT_CLIENT_SECRET', 'REDDIT_USERNAME', 'REDDIT_PASSWORD'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.reddit.com/prefs/apps',
    business_use: 'Community posts, AMA, brand mentions',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Reddit Developer App',
        step_description: 'Go to reddit.com/prefs/apps. Scroll down and click "Create App" or "Create another app". Select "web app" type.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.reddit.com/prefs/apps',
        action_label: 'Open Reddit Apps',
      },
      {
        step_number: 2,
        step_title: 'Configure App',
        step_description: 'Fill in App Name, Redirect URI, and copy the App ID (client_id shown below app name).',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'redirect_uri', label: 'Redirect URI', type: 'url', placeholder: 'https://yoursite.com/api/auth/reddit/callback', required: true },
          { name: 'app_id', label: 'App ID (client_id)', type: 'text', help: 'Shown below your app name', required: true },
        ],
        env_var_to_set: 'REDDIT_CLIENT_ID',
      },
      {
        step_number: 3,
        step_title: 'Set Client Secret',
        step_description: 'Set REDDIT_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'REDDIT_CLIENT_SECRET',
      },
      {
        step_number: 4,
        step_title: 'Set Reddit Username',
        step_description: 'Reddit OAuth requires your account username for script-type auth. Set REDDIT_USERNAME in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'REDDIT_USERNAME',
      },
      {
        step_number: 5,
        step_title: 'Set Reddit Password',
        step_description: 'Set REDDIT_PASSWORD in your .env file. Use an app password if 2FA is enabled.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'REDDIT_PASSWORD',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Reddit credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Reddit account info',
      },
    ],
  },
  // ─── TRUSTPILOT ─────────────────────────────────────────────────────
  {
    platform: 'trustpilot',
    display_name: 'Trustpilot',
    connector_type: 'custom_connector',
    priority: 'high',
    required_env_vars: ['TRUSTPILOT_BUSINESS_UNIT_ID', 'TRUSTPILOT_API_KEY', 'TRUSTPILOT_API_SECRET'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.trustpilot.com',
    business_use: 'Review management, reputation monitoring',
    automation_potential: 'High — automated review responses',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Trustpilot Business Account',
        step_description: 'Claim your business on Trustpilot. Verify ownership via email or domain verification.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://business.trustpilot.com',
        action_label: 'Open Trustpilot Business',
      },
      {
        step_number: 2,
        step_title: 'Apply for API Access',
        step_description: 'Go to developers.trustpilot.com. Register for API access. Choose plan (Free tier supports reading reviews and basic features).',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.trustpilot.com',
        action_label: 'Open Trustpilot Developers',
      },
      {
        step_number: 3,
        step_title: 'Enter API Credentials',
        step_description: 'Enter your Business Unit ID from Trustpilot Business → Integrations → API.',
        step_type: 'form',
        required_fields: [
          { name: 'business_unit_id', label: 'Business Unit ID', type: 'text', help: 'Found in Trustpilot Business → Integrations → API', required: true },
        ],
        env_var_to_set: 'TRUSTPILOT_BUSINESS_UNIT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set API Key',
        step_description: 'Set TRUSTPILOT_API_KEY in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TRUSTPILOT_API_KEY',
      },
      {
        step_number: 5,
        step_title: 'Set API Secret',
        step_description: 'Set TRUSTPILOT_API_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TRUSTPILOT_API_SECRET',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Trustpilot credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your business review stats',
      },
    ],
  },
  // ─── VIMEO ──────────────────────────────────────────────────────────
  {
    platform: 'vimeo',
    display_name: 'Vimeo',
    connector_type: 'custom_connector',
    priority: 'medium',
    required_env_vars: ['VIMEO_CLIENT_ID', 'VIMEO_CLIENT_SECRET', 'VIMEO_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developer.vimeo.com',
    business_use: 'Professional video hosting, course content',
    automation_potential: 'Medium — video uploads and management',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Vimeo Account',
        step_description: 'Create a Vimeo account. For API access and uploading, a paid plan (Starter or above) is required.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://vimeo.com/join',
        action_label: 'Join Vimeo',
      },
      {
        step_number: 2,
        step_title: 'Create Vimeo App',
        step_description: 'Go to developer.vimeo.com/apps/new. Fill in App Name, description, and App URL. Accept terms.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developer.vimeo.com/apps/new',
        action_label: 'Create App',
      },
      {
        step_number: 3,
        step_title: 'Enter App Details',
        step_description: 'Copy your App Name and Client ID from Vimeo Developer.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'client_id', label: 'Client ID', type: 'text', required: true },
        ],
        env_var_to_set: 'VIMEO_CLIENT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Client Secret',
        step_description: 'Set VIMEO_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'VIMEO_CLIENT_SECRET',
      },
      {
        step_number: 5,
        step_title: 'Set Access Token',
        step_description: 'Generate a Personal Access Token from your Vimeo app with scopes: public, private, create, edit, delete, upload, video_files. Set VIMEO_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'VIMEO_ACCESS_TOKEN',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Vimeo credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Vimeo account info',
      },
    ],
  },
  // ─── SOUNDCLOUD ─────────────────────────────────────────────────────
  {
    platform: 'soundcloud',
    display_name: 'SoundCloud',
    connector_type: 'manual_only',
    priority: 'low',
    required_env_vars: ['SOUNDCLOUD_CLIENT_ID', 'SOUNDCLOUD_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.soundcloud.com',
    business_use: 'Podcast/audio content distribution',
    automation_potential: 'Low — API registration on waitlist',
    steps: [
      {
        step_number: 1,
        step_title: 'Create SoundCloud Account',
        step_description: 'Create or log into SoundCloud with your artist/brand account.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://soundcloud.com/create',
        action_label: 'Join SoundCloud',
      },
      {
        step_number: 2,
        step_title: 'Register as Developer',
        step_description: 'Note: SoundCloud API registration is currently limited. Submit a request at developers.soundcloud.com. Most new registrations are on waitlist.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.soundcloud.com',
        action_label: 'Open SoundCloud API',
      },
      {
        step_number: 3,
        step_title: 'Enter App Details',
        step_description: 'Once approved, enter your Client ID.',
        step_type: 'form',
        required_fields: [
          { name: 'client_id', label: 'Client ID', type: 'text', required: true },
        ],
        env_var_to_set: 'SOUNDCLOUD_CLIENT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Access Token',
        step_description: 'Set SOUNDCLOUD_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'SOUNDCLOUD_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your SoundCloud credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'API access is limited — may not be available',
      },
    ],
  },
  // ─── PATREON ────────────────────────────────────────────────────────
  {
    platform: 'patreon',
    display_name: 'Patreon',
    connector_type: 'custom_connector',
    priority: 'medium',
    required_env_vars: ['PATREON_ACCESS_TOKEN', 'PATREON_CAMPAIGN_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.patreon.com/portal/registration/register-clients',
    business_use: 'Membership content, patron management',
    automation_potential: 'Medium — patron management and content',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Patreon Creator Account',
        step_description: 'Set up your Patreon creator page. Complete onboarding — membership tiers, about page, first post.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.patreon.com/create',
        action_label: 'Open Patreon',
      },
      {
        step_number: 2,
        step_title: 'Register Patreon App',
        step_description: 'Go to patreon.com/portal/registration/register-clients. Fill in App Name, Description, and Redirect URI.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.patreon.com/portal/registration/register-clients',
        action_label: 'Register App',
      },
      {
        step_number: 3,
        step_title: 'Enter Campaign ID',
        step_description: 'Find your Campaign ID via GET /api/oauth2/v2/campaigns after auth.',
        step_type: 'form',
        required_fields: [
          { name: 'campaign_id', label: 'Campaign ID', type: 'text', help: 'Found in Patreon API: GET /api/oauth2/v2/campaigns', required: true },
        ],
        env_var_to_set: 'PATREON_CAMPAIGN_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Access Token',
        step_description: 'Use OAuth 2.0 flow to get Creator Access Token. Set PATREON_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'PATREON_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Patreon credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your campaign info',
      },
    ],
  },
  // ─── MEDIUM ─────────────────────────────────────────────────────────
  {
    platform: 'medium',
    display_name: 'Medium',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['MEDIUM_INTEGRATION_TOKEN', 'MEDIUM_USER_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://medium.com/me/settings/security',
    business_use: 'Thought leadership articles, blog cross-posting',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Medium Account',
        step_description: 'Create or log into Medium with your brand account.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://medium.com/m/signin',
        action_label: 'Join Medium',
      },
      {
        step_number: 2,
        step_title: 'Get Integration Token',
        step_description: 'Go to Settings → Security → Integration Tokens → Get Integration Token. This is your API key.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://medium.com/me/settings/security',
        action_label: 'Open Settings',
      },
      {
        step_number: 3,
        step_title: 'Set Integration Token',
        step_description: 'Set MEDIUM_INTEGRATION_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'MEDIUM_INTEGRATION_TOKEN',
      },
      {
        step_number: 4,
        step_title: 'Get Your User ID',
        step_description: 'Call GET https://api.medium.com/v1/me with your token to get your userId.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 5,
        step_title: 'Set User ID',
        step_description: 'Set MEDIUM_USER_ID in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'MEDIUM_USER_ID',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Medium credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Medium profile info',
      },
    ],
  },
  // ─── GOOGLE ADS ─────────────────────────────────────────────────────
  {
    platform: 'google_ads',
    display_name: 'Google Ads',
    connector_type: 'custom_connector',
    priority: 'high',
    required_env_vars: ['GOOGLE_ADS_CUSTOMER_ID', 'GOOGLE_ADS_DEVELOPER_TOKEN', 'GOOGLE_ADS_CLIENT_ID', 'GOOGLE_ADS_CLIENT_SECRET', 'GOOGLE_ADS_REFRESH_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://ads.google.com',
    business_use: 'Search/Display ads, campaign management',
    automation_potential: 'High — programmatic ad management',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Google Ads Account',
        step_description: 'Create a Google Ads account at ads.google.com. A billing method is required but you can set a low budget.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://ads.google.com',
        action_label: 'Open Google Ads',
      },
      {
        step_number: 2,
        step_title: 'Enable Google Ads API',
        step_description: 'Enable Google Ads API in your Google Cloud project.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://console.cloud.google.com/apis/library/googleads.googleapis.com',
        action_label: 'Enable API',
      },
      {
        step_number: 3,
        step_title: 'Apply for API Access',
        step_description: 'New accounts need to apply for API access at developers.google.com/google-ads/api/docs/first-call/overview. Standard access allows all features.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.google.com/google-ads/api/docs/first-call/overview',
        action_label: 'Apply for Access',
      },
      {
        step_number: 4,
        step_title: 'Enter Customer ID',
        step_description: 'Enter your Google Ads Customer ID (found in top-right corner of Google Ads dashboard).',
        step_type: 'form',
        required_fields: [
          { name: 'customer_id', label: 'Customer ID', type: 'text', placeholder: '123-456-7890', help: 'Found in top-right corner of Google Ads dashboard', required: true },
        ],
        env_var_to_set: 'GOOGLE_ADS_CUSTOMER_ID',
      },
      {
        step_number: 5,
        step_title: 'Set Developer Token',
        step_description: 'Found in Google Ads → Tools & Settings → API Center. Set GOOGLE_ADS_DEVELOPER_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'GOOGLE_ADS_DEVELOPER_TOKEN',
      },
      {
        step_number: 6,
        step_title: 'Set OAuth Credentials',
        step_description: 'Reuse from YouTube/Google setup or create new OAuth 2.0 credentials in Cloud Console. Set GOOGLE_ADS_CLIENT_ID, GOOGLE_ADS_CLIENT_SECRET, GOOGLE_ADS_REFRESH_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'GOOGLE_ADS_CLIENT_ID',
      },
      {
        step_number: 7,
        step_title: 'Test Connection',
        step_description: 'Verify your Google Ads credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Google Ads account info',
      },
    ],
  },
  // ─── SNAPCHAT ────────────────────────────────────────────────────────
  {
    platform: 'snapchat',
    display_name: 'Snapchat',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['SNAPCHAT_CLIENT_ID', 'SNAPCHAT_CLIENT_SECRET', 'SNAPCHAT_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developers.snap.com',
    business_use: 'Stories, Spotlight, youth demographics',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Snap Developer Account',
        step_description: 'Go to developers.snap.com. Create or log in with your Snap account. Accept developer terms.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.snap.com',
        action_label: 'Open Snap Developers',
      },
      {
        step_number: 2,
        step_title: 'Create a New App',
        step_description: 'Click "Create App". Select app type. Fill in app name and description.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developers.snap.com/dashboard',
        action_label: 'Create App',
      },
      {
        step_number: 3,
        step_title: 'Enter App Credentials',
        step_description: 'Copy Client ID from Snap Developer Dashboard.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID', type: 'text', required: true },
        ],
        env_var_to_set: 'SNAPCHAT_CLIENT_ID',
      },
      {
        step_number: 4,
        step_title: 'Set Client Secret',
        step_description: 'Set SNAPCHAT_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'SNAPCHAT_CLIENT_SECRET',
      },
      {
        step_number: 5,
        step_title: 'Set Access Token',
        step_description: 'Complete OAuth 2.0 flow. Set SNAPCHAT_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'SNAPCHAT_ACCESS_TOKEN',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Snapchat credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Snapchat account info',
      },
    ],
  },
  // ─── TWITCH ─────────────────────────────────────────────────────────
  {
    platform: 'twitch',
    display_name: 'Twitch',
    connector_type: 'postiz',
    priority: 'low',
    required_env_vars: ['TWITCH_CLIENT_ID', 'TWITCH_CLIENT_SECRET', 'TWITCH_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://dev.twitch.tv',
    business_use: 'Live streaming, gaming audience',
    automation_potential: 'Low — manual streaming primary use case',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Twitch Developer Account',
        step_description: 'Go to dev.twitch.tv. Log in with your Twitch account. Register your application.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://dev.twitch.tv/console',
        action_label: 'Open Twitch Developers',
      },
      {
        step_number: 2,
        step_title: 'Register Application',
        step_description: 'Click "Register Your Application". Fill in name, OAuth Redirect URLs, and category.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID', type: 'text', required: true },
        ],
        env_var_to_set: 'TWITCH_CLIENT_ID',
      },
      {
        step_number: 3,
        step_title: 'Set Client Secret',
        step_description: 'Set TWITCH_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITCH_CLIENT_SECRET',
      },
      {
        step_number: 4,
        step_title: 'Set Access Token',
        step_description: 'Complete OAuth flow. Set TWITCH_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TWITCH_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Twitch credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Twitch channel info',
      },
    ],
  },
  // ─── MASTODON ───────────────────────────────────────────────────────
  {
    platform: 'mastodon',
    display_name: 'Mastodon',
    connector_type: 'postiz',
    priority: 'low',
    required_env_vars: ['MASTODON_INSTANCE_URL', 'MASTODON_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://mastodon.social',
    business_use: 'Decentralized social, privacy-conscious audience',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Mastodon Account',
        step_description: 'Choose a Mastodon instance (mastodon.social is most popular). Create an account on your chosen instance.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://mastodon.social',
        action_label: 'Join Mastodon',
      },
      {
        step_number: 2,
        step_title: 'Register Application',
        step_description: 'In your Mastodon instance → Settings → Development → New Application. Set scopes: read, write, follow.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Enter Instance URL',
        step_description: 'Enter your Mastodon instance URL.',
        step_type: 'form',
        required_fields: [
          { name: 'instance_url', label: 'Instance URL', type: 'url', placeholder: 'https://mastodon.social', required: true },
        ],
        env_var_to_set: 'MASTODON_INSTANCE_URL',
      },
      {
        step_number: 4,
        step_title: 'Set Access Token',
        step_description: 'Set MASTODON_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'MASTODON_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Mastodon credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Mastodon account info',
      },
    ],
  },
  // ─── BLUESKY ────────────────────────────────────────────────────────
  {
    platform: 'bluesky',
    display_name: 'Bluesky',
    connector_type: 'postiz',
    priority: 'low',
    required_env_vars: ['BLUESKY_IDENTIFIER', 'BLUESKY_PASSWORD'],
    optional_env_vars: [],
    developer_portal_url: 'https://bsky.app',
    business_use: 'Growing social platform, Twitter alternative',
    automation_potential: 'Medium — via Postiz',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Bluesky Account',
        step_description: 'Create an account at bsky.app using your business email.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://bsky.app',
        action_label: 'Join Bluesky',
      },
      {
        step_number: 2,
        step_title: 'Create App Password',
        step_description: 'Go to Settings → App Passwords → Add App Password. This is safer than your main password.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Set Identifier',
        step_description: 'Set BLUESKY_IDENTIFIER in your .env file (your Bluesky handle, e.g. username.bsky.social).',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'BLUESKY_IDENTIFIER',
      },
      {
        step_number: 4,
        step_title: 'Set App Password',
        step_description: 'Set BLUESKY_PASSWORD in your .env file (use app password, not your main password).',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'BLUESKY_PASSWORD',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Bluesky credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Bluesky profile info',
      },
    ],
  },
  // ─── TUMBLR ─────────────────────────────────────────────────────────
  {
    platform: 'tumblr',
    display_name: 'Tumblr',
    connector_type: 'postiz',
    priority: 'low',
    required_env_vars: ['TUMBLR_CONSUMER_KEY', 'TUMBLR_CONSUMER_SECRET', 'TUMBLR_ACCESS_TOKEN', 'TUMBLR_ACCESS_SECRET'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.tumblr.com/oauth/apps',
    business_use: 'Visual content, niche communities',
    automation_potential: 'Low — niche platform',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Tumblr Developer App',
        step_description: 'Go to tumblr.com/oauth/apps. Click "Register application". Fill in Application Name, Application Website, and Callback URL.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.tumblr.com/oauth/apps',
        action_label: 'Open Tumblr Apps',
      },
      {
        step_number: 2,
        step_title: 'Enter App Credentials',
        step_description: 'Copy Consumer Key from your Tumblr App.',
        step_type: 'form',
        required_fields: [
          { name: 'app_id', label: 'Consumer Key', type: 'text', required: true },
        ],
        env_var_to_set: 'TUMBLR_CONSUMER_KEY',
      },
      {
        step_number: 3,
        step_title: 'Set Consumer Secret',
        step_description: 'Set TUMBLR_CONSUMER_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TUMBLR_CONSUMER_SECRET',
      },
      {
        step_number: 4,
        step_title: 'Set OAuth Tokens',
        step_description: 'Complete OAuth 1.0a flow. Set TUMBLR_ACCESS_TOKEN and TUMBLR_ACCESS_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TUMBLR_ACCESS_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Tumblr credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Tumblr blog info',
      },
    ],
  },
  // ─── DAILYMOTION ────────────────────────────────────────────────────
  {
    platform: 'dailymotion',
    display_name: 'Dailymotion',
    connector_type: 'manual_only',
    priority: 'low',
    required_env_vars: ['DAILYMOTION_API_KEY', 'DAILYMOTION_API_SECRET', 'DAILYMOTION_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://developer.dailymotion.com',
    business_use: 'Video content distribution',
    automation_potential: 'Low — niche video platform',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Dailymotion Account',
        step_description: 'Create or log into Dailymotion at dailymotion.com.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.dailymotion.com',
        action_label: 'Open Dailymotion',
      },
      {
        step_number: 2,
        step_title: 'Register Application',
        step_description: 'Go to developer.dailymotion.com. Register your application to get API credentials.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developer.dailymotion.com',
        action_label: 'Open Developer Portal',
      },
      {
        step_number: 3,
        step_title: 'Enter API Credentials',
        step_description: 'Enter your API Key from Dailymotion Developer Portal.',
        step_type: 'form',
        required_fields: [
          { name: 'app_id', label: 'API Key', type: 'text', required: true },
        ],
        env_var_to_set: 'DAILYMOTION_API_KEY',
      },
      {
        step_number: 4,
        step_title: 'Set API Secret and Access Token',
        step_description: 'Set DAILYMOTION_API_SECRET and DAILYMOTION_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'DAILYMOTION_API_SECRET',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Dailymotion credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'No automated test available for this platform',
      },
    ],
  },
  // ─── SPOTIFY ────────────────────────────────────────────────────────
  {
    platform: 'spotify',
    display_name: 'Spotify',
    connector_type: 'manual_only',
    priority: 'medium',
    required_env_vars: ['SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET'],
    optional_env_vars: ['SPOTIFY_SHOW_ID'],
    developer_portal_url: 'https://developer.spotify.com',
    business_use: 'Podcast hosting, playlist marketing',
    automation_potential: 'Low — distribution via Spotify for Podcasters',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Spotify Developer App',
        step_description: 'Go to developer.spotify.com/dashboard. Log in and create a new app.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://developer.spotify.com/dashboard',
        action_label: 'Open Spotify Developer',
      },
      {
        step_number: 2,
        step_title: 'Enter App Credentials',
        step_description: 'Copy Client ID from your Spotify Developer Dashboard.',
        step_type: 'form',
        required_fields: [
          { name: 'app_name', label: 'App Name', type: 'text', required: true },
          { name: 'app_id', label: 'Client ID', type: 'text', required: true },
        ],
        env_var_to_set: 'SPOTIFY_CLIENT_ID',
      },
      {
        step_number: 3,
        step_title: 'Set Client Secret',
        step_description: 'Set SPOTIFY_CLIENT_SECRET in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'SPOTIFY_CLIENT_SECRET',
      },
      {
        step_number: 4,
        step_title: 'Configure Spotify for Podcasters',
        step_description: 'For podcast distribution, set up your show at podcasters.spotify.com. Get your Show ID from the URL.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Spotify credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return Spotify catalog search results',
      },
    ],
  },
  // ─── APPLE PODCASTS ─────────────────────────────────────────────────
  {
    platform: 'apple_podcasts',
    display_name: 'Apple Podcasts',
    connector_type: 'manual_only',
    priority: 'medium',
    required_env_vars: ['APPLE_PODCASTS_RSS_FEED_URL'],
    optional_env_vars: [],
    developer_portal_url: 'https://podcastsconnect.apple.com',
    business_use: 'Podcast distribution to Apple listeners',
    automation_potential: 'Low — RSS-based distribution',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Apple ID',
        step_description: 'Ensure you have an Apple ID (personal or business). No separate developer account needed for podcast submission.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 2,
        step_title: 'Set Up Podcast RSS Feed',
        step_description: 'Apple Podcasts uses RSS for distribution. Set up your podcast RSS feed via a podcast host (Anchor, Buzzsprout, Libsyn, etc.) or generate your own.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Submit to Apple Podcasts Connect',
        step_description: 'Go to podcastsconnect.apple.com. Submit your RSS feed URL. Approval takes 1-5 business days.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://podcastsconnect.apple.com',
        action_label: 'Open Podcasts Connect',
      },
      {
        step_number: 4,
        step_title: 'Enter RSS Feed URL',
        step_description: 'Enter your podcast RSS feed URL.',
        step_type: 'form',
        required_fields: [
          { name: 'rss_feed_url', label: 'RSS Feed URL', type: 'url', placeholder: 'https://yourhost.com/podcast.rss', required: true },
        ],
        env_var_to_set: 'APPLE_PODCASTS_RSS_FEED_URL',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Manual setup complete. No automated test available.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'RSS feed distribution — manual verification only',
      },
    ],
  },
  // ─── YELP ───────────────────────────────────────────────────────────
  {
    platform: 'yelp',
    display_name: 'Yelp',
    connector_type: 'custom_connector',
    priority: 'medium',
    required_env_vars: ['YELP_API_KEY', 'YELP_BUSINESS_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.yelp.com/developers',
    business_use: 'Review management, local discovery',
    automation_potential: 'Medium — review monitoring and responses',
    steps: [
      {
        step_number: 1,
        step_title: 'Claim Your Yelp Business',
        step_description: 'Go to biz.yelp.com and claim/verify your business listing.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://biz.yelp.com',
        action_label: 'Open Yelp Business',
      },
      {
        step_number: 2,
        step_title: 'Create Yelp App',
        step_description: 'Go to yelp.com/developers/v3/manage_app. Create an app to get your API key.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.yelp.com/developers/v3/manage_app',
        action_label: 'Create App',
      },
      {
        step_number: 3,
        step_title: 'Enter Business Details',
        step_description: 'Enter your Yelp Business ID (from your Yelp business URL).',
        step_type: 'form',
        required_fields: [
          { name: 'business_id', label: 'Business ID', type: 'text', help: 'From your Yelp business URL: yelp.com/biz/YOUR-BUSINESS-ID', required: true },
        ],
        env_var_to_set: 'YELP_BUSINESS_ID',
      },
      {
        step_number: 4,
        step_title: 'Set API Key',
        step_description: 'Set YELP_API_KEY in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'YELP_API_KEY',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Yelp credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your business review stats',
      },
    ],
  },
  // ─── TRIPADVISOR ────────────────────────────────────────────────────
  {
    platform: 'tripadvisor',
    display_name: 'Tripadvisor',
    connector_type: 'custom_connector',
    priority: 'low',
    required_env_vars: ['TRIPADVISOR_API_KEY', 'TRIPADVISOR_LOCATION_ID'],
    optional_env_vars: [],
    developer_portal_url: 'https://www.tripadvisor.com/developers',
    business_use: 'Travel/hospitality reviews',
    automation_potential: 'Low — review monitoring only',
    steps: [
      {
        step_number: 1,
        step_title: 'Claim Tripadvisor Listing',
        step_description: 'Claim your business listing at tripadvisor.com if not already done.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.tripadvisor.com/BusinessListingCenter',
        action_label: 'Open Business Center',
      },
      {
        step_number: 2,
        step_title: 'Apply for API Access',
        step_description: 'Go to tripadvisor.com/developers and apply for Content API access.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.tripadvisor.com/developers',
        action_label: 'Apply for API',
      },
      {
        step_number: 3,
        step_title: 'Enter Location Details',
        step_description: 'Enter your Tripadvisor Location ID.',
        step_type: 'form',
        required_fields: [
          { name: 'location_id', label: 'Location ID', type: 'text', help: 'From Tripadvisor URL: tripadvisor.com/Hotel_Review-gXXX-dLOCATION_ID', required: true },
        ],
        env_var_to_set: 'TRIPADVISOR_LOCATION_ID',
      },
      {
        step_number: 4,
        step_title: 'Set API Key',
        step_description: 'Set TRIPADVISOR_API_KEY in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'TRIPADVISOR_API_KEY',
      },
      {
        step_number: 5,
        step_title: 'Test Connection',
        step_description: 'Verify your Tripadvisor credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your location review data',
      },
    ],
  },
  // ─── QUORA ──────────────────────────────────────────────────────────
  {
    platform: 'quora',
    display_name: 'Quora',
    connector_type: 'manual_only',
    priority: 'low',
    required_env_vars: [],
    optional_env_vars: ['QUORA_ADS_TOKEN'],
    developer_portal_url: 'https://www.quora.com/business',
    business_use: 'Thought leadership Q&A, ads',
    automation_potential: 'Low — mainly manual engagement',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Quora Business Account',
        step_description: 'Create a Quora account for your brand. Go to quora.com/business to set up advertising.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.quora.com/business',
        action_label: 'Open Quora Business',
      },
      {
        step_number: 2,
        step_title: 'Set Up Brand Profile',
        step_description: 'Complete your Quora profile with business bio, profile image, and topics relevant to yoga/wellness.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Configure Quora Ads (Optional)',
        step_description: 'If using Quora Ads, set up your ad account and get your API token from Quora Ads Manager.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://www.quora.com/ads/account',
        action_label: 'Open Quora Ads',
      },
      {
        step_number: 4,
        step_title: 'Manual Setup Complete',
        step_description: 'Quora is primarily a manual platform. Engage authentically in Q&A sessions related to yoga, wellness, and mindfulness.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Manual engagement platform — no automated API test',
      },
    ],
  },
  // ─── STACK OVERFLOW ─────────────────────────────────────────────────
  {
    platform: 'stack_overflow',
    display_name: 'Stack Overflow',
    connector_type: 'manual_only',
    priority: 'low',
    required_env_vars: ['STACK_OVERFLOW_API_KEY'],
    optional_env_vars: [],
    developer_portal_url: 'https://api.stackexchange.com',
    business_use: 'Technical community, developer audience',
    automation_potential: 'Low — developer-focused platform',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Stack Overflow Account',
        step_description: 'Create a Stack Overflow account for your brand/team at stackoverflow.com.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://stackoverflow.com/users/signup',
        action_label: 'Join Stack Overflow',
      },
      {
        step_number: 2,
        step_title: 'Register Stack Exchange App',
        step_description: 'Go to stackapps.com/apps/oauth/register. Register your app to get an API key.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://stackapps.com/apps/oauth/register',
        action_label: 'Register App',
      },
      {
        step_number: 3,
        step_title: 'Set API Key',
        step_description: 'Set STACK_OVERFLOW_API_KEY in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'STACK_OVERFLOW_API_KEY',
      },
      {
        step_number: 4,
        step_title: 'Test Connection',
        step_description: 'Verify your Stack Exchange credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return user info from Stack Exchange API',
      },
    ],
  },
  // ─── SUBSTACK ───────────────────────────────────────────────────────
  {
    platform: 'substack',
    display_name: 'Substack',
    connector_type: 'manual_only',
    priority: 'medium',
    required_env_vars: ['SUBSTACK_PUBLICATION_URL'],
    optional_env_vars: [],
    developer_portal_url: 'https://substack.com',
    business_use: 'Newsletter publishing, subscription revenue',
    automation_potential: 'Low — mainly manual publishing',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Substack Publication',
        step_description: 'Go to substack.com. Create your newsletter/publication. Set up paid subscriptions if desired.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://substack.com/new',
        action_label: 'Create Publication',
      },
      {
        step_number: 2,
        step_title: 'Enter Publication URL',
        step_description: 'Enter your Substack publication URL.',
        step_type: 'form',
        required_fields: [
          { name: 'publication_url', label: 'Publication URL', type: 'url', placeholder: 'https://yourname.substack.com', required: true },
        ],
        env_var_to_set: 'SUBSTACK_PUBLICATION_URL',
      },
      {
        step_number: 3,
        step_title: 'Configure Cross-posting',
        step_description: 'Set up cross-posting from your main blog to Substack. Substack supports importing from RSS feeds.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 4,
        step_title: 'Manual Setup Complete',
        step_description: 'Substack has limited API access. Content is primarily published manually through the Substack dashboard.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Manual publishing platform — no automated API test',
      },
    ],
  },
  // ─── SLACK ──────────────────────────────────────────────────────────
  {
    platform: 'slack',
    display_name: 'Slack',
    connector_type: 'postiz',
    priority: 'medium',
    required_env_vars: ['SLACK_BOT_TOKEN', 'SLACK_CHANNEL_ID'],
    optional_env_vars: ['SLACK_SIGNING_SECRET'],
    developer_portal_url: 'https://api.slack.com',
    business_use: 'Team communications, community workspace',
    automation_potential: 'High — bot notifications and alerts',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Slack App',
        step_description: 'Go to api.slack.com/apps. Click "Create New App". Choose "From scratch". Name your app and select your workspace.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://api.slack.com/apps/new',
        action_label: 'Create Slack App',
      },
      {
        step_number: 2,
        step_title: 'Configure Bot Permissions',
        step_description: 'Under OAuth & Permissions → Bot Token Scopes, add: chat:write, channels:read, groups:read, im:read, mpim:read.',
        step_type: 'info',
        required_fields: [],
      },
      {
        step_number: 3,
        step_title: 'Install App to Workspace',
        step_description: 'Click "Install to Workspace" in OAuth & Permissions. Authorize the app. Copy the Bot User OAuth Token.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://api.slack.com/apps',
        action_label: 'Open Slack Apps',
      },
      {
        step_number: 4,
        step_title: 'Set Bot Token',
        step_description: 'Set SLACK_BOT_TOKEN in your .env file (starts with xoxb-).',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'SLACK_BOT_TOKEN',
      },
      {
        step_number: 5,
        step_title: 'Enter Channel ID',
        step_description: 'Enter the Slack Channel ID where notifications should be sent.',
        step_type: 'form',
        required_fields: [
          { name: 'channel_id', label: 'Channel ID', type: 'text', help: 'Right-click channel → View channel details → Channel ID at bottom', required: true },
        ],
        env_var_to_set: 'SLACK_CHANNEL_ID',
      },
      {
        step_number: 6,
        step_title: 'Test Connection',
        step_description: 'Verify your Slack credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Will send a test message to your configured channel',
      },
    ],
  },
  // ─── DRIBBBLE ───────────────────────────────────────────────────────
  {
    platform: 'dribbble',
    display_name: 'Dribbble',
    connector_type: 'postiz',
    priority: 'low',
    required_env_vars: ['DRIBBBLE_ACCESS_TOKEN'],
    optional_env_vars: [],
    developer_portal_url: 'https://dribbble.com/account/applications/new',
    business_use: 'Design portfolio, creative community',
    automation_potential: 'Low — design-focused niche platform',
    steps: [
      {
        step_number: 1,
        step_title: 'Create Dribbble Account',
        step_description: 'Create a Dribbble account at dribbble.com. A Designer or Team account is needed for API access.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://dribbble.com/signup',
        action_label: 'Join Dribbble',
      },
      {
        step_number: 2,
        step_title: 'Register Application',
        step_description: 'Go to dribbble.com/account/applications/new. Fill in application name, description, and website URL.',
        step_type: 'open_url',
        required_fields: [],
        action_url: 'https://dribbble.com/account/applications/new',
        action_label: 'Register App',
      },
      {
        step_number: 3,
        step_title: 'Set Access Token',
        step_description: 'Complete OAuth flow or generate personal access token. Set DRIBBBLE_ACCESS_TOKEN in your .env file.',
        step_type: 'env_var',
        required_fields: [],
        env_var_to_set: 'DRIBBBLE_ACCESS_TOKEN',
      },
      {
        step_number: 4,
        step_title: 'Test Connection',
        step_description: 'Verify your Dribbble credentials.',
        step_type: 'verify',
        required_fields: [],
        validation_hint: 'Should return your Dribbble profile info',
      },
    ],
  },
];

// Platform emoji map
export const PLATFORM_EMOJIS: Record<string, string> = {
  facebook: '📘',
  instagram: '📸',
  threads: '🧵',
  whatsapp_business: '💬',
  x_twitter: '🐦',
  linkedin: '💼',
  tiktok: '🎵',
  youtube: '▶️',
  pinterest: '📌',
  github: '🐙',
  gitlab: '🦊',
  google_business: '🗺️',
  telegram: '✈️',
  discord: '🎮',
  reddit: '🤖',
  trustpilot: '⭐',
  vimeo: '🎬',
  soundcloud: '🎧',
  patreon: '🎨',
  medium: '📝',
  google_ads: '🎯',
  snapchat: '👻',
  twitch: '🎮',
  mastodon: '🐘',
  bluesky: '🦋',
  tumblr: '📓',
  dailymotion: '🎥',
  spotify: '🎵',
  apple_podcasts: '🎙️',
  yelp: '⭐',
  tripadvisor: '🏝️',
  quora: '❓',
  stack_overflow: '📚',
  substack: '📧',
  slack: '💬',
  dribbble: '🏀',
};
