import { NextRequest} from 'next/server';
import { pool } from '@/lib/db';
import crypto from 'crypto';

import { requireAdmin } from '@/lib/admin-auth';
const CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS vector_store (
  id BIGSERIAL PRIMARY KEY,
  namespace VARCHAR(100) NOT NULL,
  source_id INT,
  source_type VARCHAR(100),
  content_text TEXT NOT NULL,
  content_hash VARCHAR(64) UNIQUE,
  embedding JSONB,
  embedding_model VARCHAR(100) DEFAULT 'nomic-embed-text',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_vector_store_namespace ON vector_store(namespace);
`;

const SEED_DOCS = [
  // bot_knowledge_base namespace
  { ns: 'bot_knowledge_base', type: 'faq', text: 'How do I book a yoga class? Visit the booking page at /booking, choose your preferred class time and instructor, then complete payment. Confirmation is sent via email.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'What is the cancellation policy? Classes can be cancelled up to 24 hours before start time for a full refund. Late cancellations receive studio credit.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'How do I reset my password? Click Forgot Password on the login page. A reset link will be emailed to your registered address.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'Do you offer beginner yoga classes? Yes! We have beginner-friendly Hatha Yoga every Monday and Wednesday at 7am and 6pm.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'What equipment do I need for yoga? A yoga mat is required. Blocks and straps are provided at the studio. Wear comfortable, breathable clothing.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'Can I freeze my membership? Yes, memberships can be frozen for up to 3 months per year. Contact support to initiate a freeze.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'Do you offer online classes? Yes, all classes are available via live stream. Links are sent 15 minutes before class start.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'What are your studio hours? Studio is open Monday-Friday 6am-9pm, Saturday 7am-7pm, Sunday 8am-6pm.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'How do I contact customer support? Email support@sohamyoga.com or use the chat widget in the bottom-right corner. Response within 2 hours.' },
  { ns: 'bot_knowledge_base', type: 'faq', text: 'What is the pricing for a monthly unlimited membership? Monthly unlimited membership is $89/month. Annual memberships are $799/year (savings of 25%).' },
  // blog_posts namespace
  { ns: 'blog_posts', type: 'blog', text: '5 Benefits of Morning Yoga: Starting your day with yoga improves flexibility, reduces stress hormones, boosts energy, sharpens focus, and sets a positive intention for the day.' },
  { ns: 'blog_posts', type: 'blog', text: 'Introduction to Pranayama: Pranayama is the practice of breath control in yoga. Key techniques include Nadi Shodhana (alternate nostril), Kapalabhati (skull-shining breath), and Ujjayi (ocean breath).' },
  { ns: 'blog_posts', type: 'blog', text: 'Yoga for Back Pain: Gentle yoga poses like Cat-Cow, Child\'s Pose, and Supine Twist can relieve lower back pain. Consult a healthcare provider before starting if you have chronic pain.' },
  { ns: 'blog_posts', type: 'blog', text: 'The Eight Limbs of Yoga: Patanjali\'s Yoga Sutras outline 8 limbs: Yama (ethics), Niyama (self-discipline), Asana (posture), Pranayama (breath), Pratyahara (withdrawal), Dharana (focus), Dhyana (meditation), Samadhi (bliss).' },
  { ns: 'blog_posts', type: 'blog', text: 'Nutrition Tips for Yogis: A plant-based diet rich in whole grains, legumes, fruits, and vegetables supports a yoga practice. Stay hydrated and avoid heavy meals 2 hours before practice.' },
  // platform_docs namespace
  { ns: 'platform_docs', type: 'doc', text: 'Admin Dashboard Overview: The admin dashboard provides real-time KPIs for bookings, revenue, leads, and social media performance. Access via /admin.' },
  { ns: 'platform_docs', type: 'doc', text: 'Cron Job System: 55 scheduled jobs run on UTC time. Jobs use local Ollama for AI tasks — zero cloud API costs. Jobs are registered in CronRegistry.ts and jobModules.ts.' },
  { ns: 'platform_docs', type: 'doc', text: 'Affiliate System: The affiliate system tracks referral links, commissions, payouts, and fraud. Commission is settled daily at 5am UTC via AffiliateCommissionSettleJob.' },
  { ns: 'platform_docs', type: 'doc', text: 'Social Media Integration: Postiz handles social post scheduling. n8n automates Instagram/Facebook/Reviews/YouTube in parallel. Meta Graph API and Twitter API v2 are connected.' },
  { ns: 'platform_docs', type: 'doc', text: 'Vector Store & RAG: The vector_store table stores document embeddings generated by nomic-embed-text via Ollama. Full-text search is the fallback when embeddings are not yet generated.' },
  // marketing namespace
  { ns: 'marketing', type: 'campaign', text: 'Summer Wellness Campaign 2026: Target audience is urban professionals aged 25-40. Key message: Reclaim your energy this summer with mindful movement. Offer: 20% off first month.' },
  { ns: 'marketing', type: 'campaign', text: 'Corporate Wellness Partnership: Pitch to HR teams — offer bulk membership packages starting at $65/employee/month for groups of 10+. ROI: reduced sick days, higher productivity.' },
  { ns: 'marketing', type: 'campaign', text: 'Referral Program Launch: Current members earn $20 studio credit for each friend they refer who completes their first paid month. Referred friends get 15% off their first month.' },
  { ns: 'marketing', type: 'email', text: 'Re-engagement Email — Subject: We miss you! Body: It has been a while since your last class. Here is 30% off your next booking, valid for 7 days. Click to redeem.' },
  { ns: 'marketing', type: 'social', text: 'Instagram caption: Find stillness in the storm. Our Sunday Yin Yoga class is the perfect reset for your week. Book your spot via the link in bio. #sohamyoga #yinyoga #weekendwellness' },
  // competitor_intel namespace
  { ns: 'competitor_intel', type: 'analysis', text: 'CorePower Yoga: Large franchise chain, 200+ locations. Strengths: brand recognition, class variety. Weakness: impersonal, high turnover instructors. Avg price $30/class or $199/month unlimited.' },
  { ns: 'competitor_intel', type: 'analysis', text: 'Mindbody Platform: B2B software for wellness studios. Powers 60,000+ businesses. Key features: scheduling, payments, marketing. Sohamyoga competes by being a full-stack owned platform.' },
  { ns: 'competitor_intel', type: 'analysis', text: 'Alo Moves: Online yoga platform. 3000+ classes. $20/month. Targets home practitioners. Differentiation opportunity: live, community-centered in-studio experience.' },
  // support_tickets namespace
  { ns: 'support_tickets', type: 'ticket', text: 'Ticket #1042 — Customer could not find their booking confirmation. Resolution: email was filtered to spam. Added whitelist instructions to confirmation flow.' },
  { ns: 'support_tickets', type: 'ticket', text: 'Ticket #1089 — Payment declined for annual membership. Resolution: card expiry. Customer updated card details. Membership activated successfully.' },
  { ns: 'support_tickets', type: 'ticket', text: 'Ticket #1103 — Zoom link for online class not received. Resolution: email delivery delay. Added redundant SMS notification for class links.' },
  // policies namespace
  { ns: 'policies', type: 'policy', text: 'Privacy Policy Summary: We collect name, email, payment info, and class attendance. Data is stored securely on Canadian servers. We never sell personal data. GDPR and PIPEDA compliant.' },
  { ns: 'policies', type: 'policy', text: 'Refund Policy: Full refund within 7 days of purchase if no classes attended. Prorated refund for unused classes after 7 days. Gift cards are non-refundable.' },
  { ns: 'policies', type: 'policy', text: 'Code of Conduct: All students are expected to arrive on time, silence phones, respect other students\' space, and follow instructor guidance. Harassment of any kind is not tolerated.' },
  // architecture namespace
  { ns: 'architecture', type: 'arch', text: 'System Architecture: Next.js 14 frontend on port 3000, FastAPI backend on port 8100, PostgreSQL on port 5437, Ollama on port 11434. All services communicate locally.' },
  { ns: 'architecture', type: 'arch', text: 'Database Schema: Over 80 PostgreSQL tables covering modules: users, bookings, classes, blog, campaigns, social_accounts, affiliates, platform_workflows, and more.' },
  { ns: 'architecture', type: 'arch', text: 'Agent Architecture: 5 specialized agents (supervisor, content, analytics, review, scheduling) orchestrated via LangGraph, running on llama3.2 via Ollama.' },
  { ns: 'architecture', type: 'arch', text: 'Cron Architecture: 55 background jobs in Next.js process managed by node-cron. Python agent jobs run in FastAPI background tasks. Logs written to cron_run_log table.' },
  { ns: 'architecture', type: 'arch', text: 'RAG Pipeline: Documents ingested to vector_store table. Embeddings generated by nomic-embed-text model via Ollama. Full-text search (PostgreSQL tsvector) used as fallback.' },
  // social_content namespace
  { ns: 'social_content', type: 'post', text: 'Facebook post: Join us this Saturday for our Community Open Class — FREE for first-time visitors! Experience the warmth of the Soham Yoga community. Tag a friend who needs a reset.' },
  { ns: 'social_content', type: 'post', text: 'Twitter/X post: The pose you avoid the most is the one you need the most. Try our new restorative yoga series — Tuesdays at 7pm. Book at sohamyoga.com #yoga #mindfulness' },
  { ns: 'social_content', type: 'post', text: 'LinkedIn post: Investing in employee wellness pays dividends. Our corporate yoga program has helped teams at [Client] reduce burnout by 34% in 6 months. DM for a partnership proposal.' },
  // event_summaries namespace
  { ns: 'event_summaries', type: 'event', text: 'Workshop: Yoga for Athletes — Oct 2026. 45 attendees. Instructor: Maria Chen. Topics: hip flexor release, shoulder mobility, recovery flows. Avg rating: 4.8/5.' },
  { ns: 'event_summaries', type: 'event', text: 'Meditation Retreat: Silence & Stillness — Nov 2026. 20 attendees. 2-day immersive. Revenue: $8,500. NPS score: 72. Repeat attendance rate: 85%.' },
  // class_descriptions namespace
  { ns: 'class_descriptions', type: 'class', text: 'Vinyasa Flow (Intermediate): A dynamic, breath-synchronized practice linking movement and breath. Builds strength, flexibility, and cardiovascular fitness. 60 minutes.' },
  { ns: 'class_descriptions', type: 'class', text: 'Restorative Yoga (All Levels): Deeply relaxing practice using props (bolsters, blankets, blocks) to support the body in passive poses held for 5-10 minutes. Activates parasympathetic nervous system.' },
  { ns: 'class_descriptions', type: 'class', text: 'Hot Yoga (Advanced): 26 postures in a heated room (38°C/100°F). Detoxifies through sweat, improves flexibility, and builds mental resilience. Bring water and a towel.' },
  { ns: 'class_descriptions', type: 'class', text: 'Prenatal Yoga (Speciality): Safe, gentle practice for all trimesters. Focuses on pelvic floor strength, breath awareness, and community with other expecting mothers. Instructor certified in prenatal care.' },
  { ns: 'class_descriptions', type: 'class', text: 'Kids Yoga (Ages 5-12): Playful, story-based yoga helping children build body awareness, focus, and confidence. 45-minute classes every Saturday at 9am.' },
  // instructor_bios namespace
  { ns: 'instructor_bios', type: 'bio', text: 'Sarah Patel — Lead Instructor. 200hr RYT, 10 years teaching. Specialties: Ashtanga, Yin Yoga, Yoga Nidra. Philosophy: Yoga is a practice of coming home to yourself.' },
  { ns: 'instructor_bios', type: 'bio', text: 'David Kim — Wellness Coach. Certified in Mindfulness-Based Stress Reduction (MBSR). Leads meditation, breathwork, and men\'s yoga programs. Background in corporate wellness.' },
];

export async function POST(req: NextRequest) {

  const denied = await requireAdmin(req);
  if (denied) return denied;
  try {
    await pool.query(CREATE_TABLE);

    let inserted = 0;
    for (const doc of SEED_DOCS) {
      const hash = crypto.createHash('sha256').update(doc.text).digest('hex');
      await pool.query(
        `INSERT INTO vector_store (namespace, source_type, content_text, content_hash, metadata)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (content_hash) DO NOTHING`,
        [doc.ns, doc.type, doc.text, hash, JSON.stringify({ seeded: true })]
      );
      inserted++;
    }

    const count = await pool.query('SELECT COUNT(*) AS cnt FROM vector_store');
    return Response.json({ ok: true, seeded: inserted, total: Number(count.rows[0].cnt) });
  } catch (err) {
    return Response.json({ error: err instanceof Error ? err.message : 'Internal server error' }, { status: 500 });
  }
}
