/**
 * Dynamic job-module import map, keyed by class name (matches CronJobDef.module
 * in CronRegistry.ts). Shared between runner.ts (scheduled execution) and the
 * demo-hub "Run Now" API route (on-demand execution) so there is exactly one
 * place that knows how to load a job by name.
 */
export const JOB_MODULES: Record<string, () => Promise<{ run: () => Promise<void> }>> = {
  MarketingAutomationJob:     () => import('./jobs/MarketingAutomationJob'),
  NotificationDispatchJob:    () => import('./jobs/NotificationDispatchJob'),
  LeaderboardRefreshJob:      () => import('./jobs/LeaderboardRefreshJob'),
  NotificationRetryJob:       () => import('./jobs/NotificationRetryJob'),
  ComplaintAlertJob:          () => import('./jobs/ComplaintAlertJob'),
  DunningManagementJob:       () => import('./jobs/DunningManagementJob'),
  CampaignTriggerJob:         () => import('./jobs/CampaignTriggerJob'),
  CrisisDetectionJob:         () => import('./jobs/CrisisDetectionJob'),
  CampaignAdaptationJob:      () => import('./jobs/CampaignAdaptationJob'),
  AnalyticsAggregationJob:    () => import('./jobs/AnalyticsAggregationJob'),
  StreakUpdateJob:            () => import('./jobs/StreakUpdateJob'),
  WellnessScoringJob:         () => import('./jobs/WellnessScoringJob'),
  MilestoneCheckJob:          () => import('./jobs/MilestoneCheckJob'),
  BadgeAwardJob:              () => import('./jobs/BadgeAwardJob'),
  AiCoachJob:                 () => import('./jobs/AiCoachJob'),
  CampaignCopyDraftJob:       () => import('./jobs/CampaignCopyDraftJob'),
  VideoScriptDraftJob:        () => import('./jobs/VideoScriptDraftJob'),
  ChurnPredictionJob:         () => import('./jobs/ChurnPredictionJob'),
  NewsletterDraftJob:         () => import('./jobs/NewsletterDraftJob'),
  CommunityDigestJob:         () => import('./jobs/CommunityDigestJob'),
  LeadNurturingJob:           () => import('./jobs/LeadNurturingJob'),
  SeoReportJob:               () => import('./jobs/SeoReportJob'),
  SearchVisibilityJob:        () => import('./jobs/SearchVisibilityJob'),
  PostizProviderHealthJob:    () => import('./jobs/PostizProviderHealthJob'),
  PostizSocialAutoPublishJob: () => import('./jobs/PostizSocialAutoPublishJob'),
  FirstWaveDispatchJob: () => import('./jobs/FirstWaveDispatchJob'),
  FeatureGapAdvisorJob:       () => import('./jobs/FeatureGapAdvisorJob'),
  ModuleBoundaryQualityJob:   () => import('./jobs/ModuleBoundaryQualityJob'),
  AbandonedCartRecoveryJob:   () => import('./jobs/AbandonedCartRecoveryJob'),
  CampaignHealthAuditJob:     () => import('./jobs/CampaignHealthAuditJob'),
  WellnessScoreComputeJob:    () => import('./jobs/WellnessScoreComputeJob'),
  ProvisioningTaskStalenessJob: () => import('./jobs/ProvisioningTaskStalenessJob'),
  BrandProfileDraftJob: () => import('./jobs/BrandProfileDraftJob'),
  PlatformBioDraftJob: () => import('./jobs/PlatformBioDraftJob'),
  NpsInvitationJob:           () => import('./jobs/NpsInvitationJob'),
  NpsCalculationJob:          () => import('./jobs/NpsCalculationJob'),
  CsatCalculationJob:         () => import('./jobs/CsatCalculationJob'),
  CesCalculationJob:          () => import('./jobs/CesCalculationJob'),
  ReviewRequestJob:           () => import('./jobs/ReviewRequestJob'),
  OpportunityScoringJob:      () => import('./jobs/OpportunityScoringJob'),
  AppointmentReminderJob:     () => import('./jobs/AppointmentReminderJob'),
  SocialContentIdeaJob:       () => import('./jobs/SocialContentIdeaJob'),
  VoiceOfCustomerJob:         () => import('./jobs/VoiceOfCustomerJob'),
  YogaEducationContentJob:    () => import('./jobs/YogaEducationContentJob'),
  FunnelStageAnalysisJob:     () => import('./jobs/FunnelStageAnalysisJob'),
  AdvocacyScoreJob:           () => import('./jobs/AdvocacyScoreJob'),
  ReferralInvitationJob:      () => import('./jobs/ReferralInvitationJob'),
  ViralDetectionJob:          () => import('./jobs/ViralDetectionJob'),
  InfluencerValueJob:         () => import('./jobs/InfluencerValueJob'),
  GitHubRepoScoutJob:         () => import('./jobs/GitHubRepoScoutJob'),
  ModuleRegistryDriftSweepJob: () => import('./jobs/ModuleRegistryDriftSweepJob'),
  DripSequenceProcessorJob: () => import('./jobs/DripSequenceProcessorJob'),
  MarketResearchPricingDigestJob: () => import('./jobs/MarketResearchPricingDigestJob'),
  IngestionSourceRefreshJob:  () => import('./jobs/IngestionSourceRefreshJob'),
  ConnectorTokenRefreshJob:   () => import('./jobs/ConnectorTokenRefreshJob'),
  LocalFolderScanJob:         () => import('./jobs/LocalFolderScanJob'),
  GoogleDriveScanJob:         () => import('./jobs/GoogleDriveScanJob'),
  SlackScanJob:               () => import('./jobs/SlackScanJob'),
  CtaHealthCheckJob:          () => import('./jobs/CtaHealthCheckJob'),
  HealthSnapshotJob:          () => import('./jobs/HealthSnapshotJob'),
  SecurityScanJob:            () => import('./jobs/SecurityScanJob'),
  BacklogPrioritizationJob:   () => import('./jobs/BacklogPrioritizationJob'),
  DeepTestAdvisoryJob:        () => import('./jobs/DeepTestAdvisoryJob'),
};
