/**
 * Dynamic job-module import map, keyed by class name (matches CronJobDef.module
 * in CronRegistry.ts). Shared between runner.ts (scheduled execution) and the
 * demo-hub "Run Now" API route (on-demand execution) so there is exactly one
 * place that knows how to load a job by name.
 */
export const JOB_MODULES: Record<string, () => Promise<{ run: () => Promise<void> }>> = {
  WorkflowEngineJob:          () => import('./jobs/WorkflowEngineJob'),
  AIContentAdaptJob:          () => import('./jobs/AIContentAdaptJob'),
  MarketingAutomationJob:     () => import('./jobs/MarketingAutomationJob'),
  NotificationDispatchJob:    () => import('./jobs/NotificationDispatchJob'),
  LeaderboardRefreshJob:      () => import('./jobs/LeaderboardRefreshJob'),
  NotificationRetryJob:       () => import('./jobs/NotificationRetryJob'),
  ComplaintAlertJob:          () => import('./jobs/ComplaintAlertJob'),
  DunningManagementJob:       () => import('./jobs/DunningManagementJob'),
  CampaignTriggerJob:         () => import('./jobs/CampaignTriggerJob'),
  CrisisDetectionJob:         () => import('./jobs/CrisisDetectionJob'),
  CampaignAdaptationJob:      () => import('./jobs/CampaignAdaptationJob'),
  AnalyticsAggregationJob:    () => import('./jobs/AnalyticsAggregationJob'),
  StreakUpdateJob:            () => import('./jobs/StreakUpdateJob'),
  WellnessScoringJob:         () => import('./jobs/WellnessScoringJob'),
  MilestoneCheckJob:          () => import('./jobs/MilestoneCheckJob'),
  BadgeAwardJob:              () => import('./jobs/BadgeAwardJob'),
  OccasionWishJob:            () => import('./jobs/OccasionWishJob'),
  AiCoachJob:                 () => import('./jobs/AiCoachJob'),
  CampaignCopyDraftJob:       () => import('./jobs/CampaignCopyDraftJob'),
  VideoScriptDraftJob:        () => import('./jobs/VideoScriptDraftJob'),
  ChurnPredictionJob:         () => import('./jobs/ChurnPredictionJob'),
  NewsletterDraftJob:         () => import('./jobs/NewsletterDraftJob'),
  CommunityDigestJob:         () => import('./jobs/CommunityDigestJob'),
  LeadNurturingJob:           () => import('./jobs/LeadNurturingJob'),
  SeoReportJob:               () => import('./jobs/SeoReportJob'),
  SearchVisibilityJob:        () => import('./jobs/SearchVisibilityJob'),
  PostizProviderHealthJob:    () => import('./jobs/PostizProviderHealthJob'),
  PostizSocialAutoPublishJob: () => import('./jobs/PostizSocialAutoPublishJob'),
  FirstWaveDispatchJob: () => import('./jobs/FirstWaveDispatchJob'),
  FeatureGapAdvisorJob:       () => import('./jobs/FeatureGapAdvisorJob'),
  ModuleBoundaryQualityJob:   () => import('./jobs/ModuleBoundaryQualityJob'),
  AbandonedCartRecoveryJob:   () => import('./jobs/AbandonedCartRecoveryJob'),
  CampaignHealthAuditJob:     () => import('./jobs/CampaignHealthAuditJob'),
  WellnessScoreComputeJob:    () => import('./jobs/WellnessScoreComputeJob'),
  ProvisioningTaskStalenessJob: () => import('./jobs/ProvisioningTaskStalenessJob'),
  BrandProfileDraftJob: () => import('./jobs/BrandProfileDraftJob'),
  PlatformBioDraftJob: () => import('./jobs/PlatformBioDraftJob'),
  NpsInvitationJob:           () => import('./jobs/NpsInvitationJob'),
  NpsCalculationJob:          () => import('./jobs/NpsCalculationJob'),
  CsatCalculationJob:         () => import('./jobs/CsatCalculationJob'),
  CesCalculationJob:          () => import('./jobs/CesCalculationJob'),
  ReviewRequestJob:           () => import('./jobs/ReviewRequestJob'),
  OpportunityScoringJob:      () => import('./jobs/OpportunityScoringJob'),
  AppointmentReminderJob:     () => import('./jobs/AppointmentReminderJob'),
  SocialContentIdeaJob:       () => import('./jobs/SocialContentIdeaJob'),
  VoiceOfCustomerJob:         () => import('./jobs/VoiceOfCustomerJob'),
  YogaEducationContentJob:    () => import('./jobs/YogaEducationContentJob'),
  FunnelStageAnalysisJob:     () => import('./jobs/FunnelStageAnalysisJob'),
  AdvocacyScoreJob:           () => import('./jobs/AdvocacyScoreJob'),
  ReferralInvitationJob:      () => import('./jobs/ReferralInvitationJob'),
  ViralDetectionJob:          () => import('./jobs/ViralDetectionJob'),
  InfluencerValueJob:         () => import('./jobs/InfluencerValueJob'),
  GitHubRepoScoutJob:         () => import('./jobs/GitHubRepoScoutJob'),
  ModuleRegistryDriftSweepJob: () => import('./jobs/ModuleRegistryDriftSweepJob'),
  DripSequenceProcessorJob: () => import('./jobs/DripSequenceProcessorJob'),
  MarketResearchPricingDigestJob: () => import('./jobs/MarketResearchPricingDigestJob'),
  MarketResearchSchedulerJob:     () => import('./jobs/MarketResearchSchedulerJob'),
  IngestionSourceRefreshJob:  () => import('./jobs/IngestionSourceRefreshJob'),
  ConnectorTokenRefreshJob:   () => import('./jobs/ConnectorTokenRefreshJob'),
  LocalFolderScanJob:         () => import('./jobs/LocalFolderScanJob'),
  GoogleDriveScanJob:         () => import('./jobs/GoogleDriveScanJob'),
  SlackScanJob:               () => import('./jobs/SlackScanJob'),
  CtaHealthCheckJob:          () => import('./jobs/CtaHealthCheckJob'),
  HealthSnapshotJob:          () => import('./jobs/HealthSnapshotJob'),
  SecurityScanJob:            () => import('./jobs/SecurityScanJob'),
  BacklogPrioritizationJob:   () => import('./jobs/BacklogPrioritizationJob'),
  DeepTestAdvisoryJob:        () => import('./jobs/DeepTestAdvisoryJob'),
  FacebookReportSyncJob:      () => import('./jobs/FacebookReportSyncJob'),
  LinkedInReportSyncJob:      () => import('./jobs/LinkedInReportSyncJob'),
  YouTubeReportSyncJob:       () => import('./jobs/YouTubeReportSyncJob'),
  TelegramReportSyncJob:      () => import('./jobs/TelegramReportSyncJob'),
  AffiliatePartnerTierJob:    () => import('./jobs/AffiliatePartnerTierJob'),
  AffiliatePayoutJob:         () => import('./jobs/AffiliatePayoutJob'),
  AffiliateFraudScanJob:      () => import('./jobs/AffiliateFraudScanJob'),
  AffiliateCommissionSettleJob: () => import('./jobs/AffiliateCommissionSettleJob'),
  ModuleTestSchedulerJob:      () => import('./jobs/ModuleTestSchedulerJob'),
  SocialAnalyticsSyncJob:      () => import('./jobs/SocialAnalyticsSyncJob'),
  HashtagTrendJob:             () => import('./jobs/HashtagTrendJob'),
  SocialAlertScanJob:          () => import('./jobs/SocialAlertScanJob'),
  ContentCalendarReminderJob:  () => import('./jobs/ContentCalendarReminderJob'),
  CommandCenterSyncJob:        () => import('./jobs/CommandCenterSyncJob'),
  // Extended platform jobs
  WhatsAppMessageQueueJob:     () => import('./jobs/WhatsAppMessageQueueJob'),
  PinterestPinSyncJob:         () => import('./jobs/PinterestPinSyncJob'),
  GitHubReleaseSyncJob:        () => import('./jobs/GitHubReleaseSyncJob'),
  GoogleBusinessSyncJob:       () => import('./jobs/GoogleBusinessSyncJob'),
  TrustpilotReviewSyncJob:     () => import('./jobs/TrustpilotReviewSyncJob'),
  VimeoAnalyticsSyncJob:       () => import('./jobs/VimeoAnalyticsSyncJob'),
  PatreonPostSyncJob:          () => import('./jobs/PatreonPostSyncJob'),
  ApiQuotaMonitorJob:          () => import('./jobs/ApiQuotaMonitorJob'),
  // Platform Monitoring Jobs
  PlatformHealthCheckJob:      () => import('./jobs/PlatformHealthCheckJob'),
  RateLimitSnapshotJob:        () => import('./jobs/RateLimitSnapshotJob'),
  RetryQueueJob:               () => import('./jobs/RetryQueueJob'),
  ApiLogCleanupJob:            () => import('./jobs/ApiLogCleanupJob'),
  // Broadcast & Notifications
  BroadcastSendJob:            () => import('./jobs/BroadcastSendJob'),
  NotificationAlertScanJob:    () => import('./jobs/NotificationAlertScanJob'),
  // Calendar & Scheduling
  CalendarSyncJob:             () => import('./jobs/CalendarSyncJob'),
  // Bot & Customer Service
  BotSessionCleanupJob:        () => import('./jobs/BotSessionCleanupJob'),
  // AI & Data
  SyntheticDataGeneratorJob:   () => import('./jobs/SyntheticDataGeneratorJob'),
  // Ad & Geo
  AdPlannerSyncJob:            () => import('./jobs/AdPlannerSyncJob'),
  GoogleAdsSyncJob:            () => import('./jobs/GoogleAdsSyncJob'),
  PaidAdsSyncJob:              () => import('./jobs/PaidAdsSyncJob'),
  GeoAeoTrackingJob:           () => import('./jobs/GeoAeoTrackingJob'),
  // Email & Drip
  DripSequenceJob:             () => import('./jobs/DripSequenceJob'),
  EmailHealthCheckJob:         () => import('./jobs/EmailHealthCheckJob'),
  // Social
  FacebookAutoPublishJob:      () => import('./jobs/FacebookAutoPublishJob'),
  // Registry & QR
  VerticalRegistryAuditJob:    () => import('./jobs/VerticalRegistryAuditJob'),
  QrSessionCleanupJob:         () => import('./jobs/QrSessionCleanupJob'),
  // Voice AI
  VoiceAiScriptRefreshJob:     () => import('./jobs/VoiceAiScriptRefreshJob'),
  // MCP
  McpHealthCheckJob:           () => import('./jobs/McpHealthCheckJob'),
  // Vector Store
  VectorEmbeddingUpdateJob:    () => import('./jobs/VectorEmbeddingUpdateJob'),
  // AI Governance
  AIGovernanceAuditJob:        () => import('./jobs/AIGovernanceAuditJob'),
  QualityBenchmarkJob:         () => import('./jobs/QualityBenchmarkJob'),
  // Competitor Intelligence
  CompetitorMonitorJob:        () => import('./jobs/CompetitorMonitorJob'),
};
