import { McpServerManifest, McpTool } from './types';

const TOOLS: McpTool[] = [
  {
    name: 'search_content',
    description: 'Full-text search across CMS articles, documents, videos, and knowledge-base entries.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['query'],
      properties: {
        query:        { type: 'string' },
        contentTypes: { type: 'array', items: { type: 'string', enum: ['article','video','document','faq','pose_guide'] } },
        limit:        { type: 'number', default: 10 },
      },
    },
  },
  {
    name: 'get_document',
    description: 'Retrieve a specific document by ID, returning metadata and a download URL.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['documentId'],
      properties: {
        documentId: { type: 'string' },
        version:    { type: 'string', description: 'Omit to get latest version' },
      },
    },
  },
  {
    name: 'upload_document',
    description: 'Upload a new document to Paperless-ngx for archiving and full-text indexing.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['fileBase64', 'filename', 'documentType'],
      properties: {
        fileBase64:   { type: 'string' },
        filename:     { type: 'string' },
        documentType: { type: 'string', enum: ['policy','waiver','certificate','marketing','legal','training'] },
        tags:         { type: 'array', items: { type: 'string' } },
      },
    },
    safetyNote: 'Do not upload health records, medical information, or passport/ID copies via this tool',
  },
  {
    name: 'classify_document',
    description: 'Run AI classification on an uploaded document to suggest type, tags, and retention period.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['documentId'],
      properties: { documentId: { type: 'string' } },
    },
  },
  {
    name: 'get_video_details',
    description: 'Return a yoga class video record: title, teacher, duration, HLS URL, and view count.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['videoId'],
      properties: { videoId: { type: 'string' } },
    },
    safetyNote: 'Return HLS URL only to authenticated and entitled users',
  },
  {
    name: 'upload_video',
    description: 'Upload a new class recording to PeerTube for processing and storage.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['videoUrl', 'title', 'teacherId', 'classId'],
      properties: {
        videoUrl:  { type: 'string', description: 'Presigned upload URL or local path' },
        title:     { type: 'string' },
        teacherId: { type: 'string' },
        classId:   { type: 'string' },
        visibility:{ type: 'string', enum: ['private','members_only','public'], default: 'members_only' },
      },
    },
  },
  {
    name: 'publish_video',
    description: 'Make a processed video visible to the target audience. Staff approval required.',
    tier: 'staff_approval', riskLevel: 3,
    inputSchema: { type: 'object', required: ['videoId', 'approvedBy'],
      properties: {
        videoId:    { type: 'string' },
        approvedBy: { type: 'string' },
        visibility: { type: 'string', enum: ['private','members_only','public'] },
        thumbnail:  { type: 'string', description: 'Thumbnail URL; auto-generated if omitted' },
      },
    },
    safetyNote: 'Verify no participant has objected to recording consent before publishing',
    tags: ['requires_approval'],
  },
  {
    name: 'manage_knowledge_base',
    description: 'Create, update, or archive a knowledge-base FAQ or pose guide entry.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['action', 'entryId'],
      properties: {
        action:   { type: 'string', enum: ['create','update','archive'] },
        entryId:  { type: 'string' },
        title:    { type: 'string' },
        body:     { type: 'string' },
        category: { type: 'string' },
        tags:     { type: 'array', items: { type: 'string' } },
      },
    },
  },
];

export const CONTENT_MCP: McpServerManifest = {
  id:          'content-mcp',
  slug:        'content-mcp',
  name:        'Content MCP',
  description: 'CMS content search, document management, video upload and publishing, and knowledge-base maintenance.',
  version:     '1.0.0',
  tools:       TOOLS,
  backingServices: ['Ghost CMS', 'Strapi', 'Paperless-ngx', 'PeerTube', 'Meilisearch', 'Qdrant'],
  availability: 'custom',
  implementationNote: 'Community MCP servers available for Paperless-ngx — review before use. PeerTube wrapping is fully custom.',
};
