/**
 * Social Media MCP — 15 compact tools covering all portal social-media operations.
 * Architecture rule: no autonomous publishing. Every post, reply, and campaign change
 * REQUIRES explicit human approval before execution.
 *
 * Quora: NOT supported. Unofficial "APIs" are fragile and may violate ToS.
 * Use the manual-publishing queue: AI drafts → human reviews → human posts.
 */
import { McpServerManifest, McpTool } from './types';

const TOOLS: McpTool[] = [
  {
    name: 'list_social_accounts',
    description: 'List all connected social accounts, their platforms, connection status, token expiry, and Postiz sync state.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['workspaceId'],
      properties: {
        workspaceId: { type: 'string' },
        platform:    { type: 'string', description: 'Filter by platform (omit for all)' },
        status:      { type: 'string', enum: ['connected','expired','error','all'], default: 'all' },
      },
    },
  },
  {
    name: 'create_content_draft',
    description: 'Create a new content draft with master text targeting one or more social platforms. Returns draft ID for downstream tools.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['workspaceId', 'masterText', 'contentType', 'platforms'],
      properties: {
        workspaceId:    { type: 'string' },
        masterText:     { type: 'string' },
        contentType:    { type: 'string', enum: ['text','image','video','carousel','story','reel','short'] },
        platforms:      { type: 'array', items: { type: 'string' } },
        campaignId:     { type: 'string' },
        generatedWithAI:{ type: 'boolean', default: true },
        tags:           { type: 'array', items: { type: 'string' } },
      },
    },
  },
  {
    name: 'adapt_content',
    description: 'Rewrite master text for a specific platform: enforcing character limits, hashtag conventions, tone, and media aspect ratios.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['draftId', 'platform'],
      properties: {
        draftId:        { type: 'string' },
        platform:       { type: 'string' },
        tone:           { type: 'string', enum: ['professional','casual','inspirational','educational','promotional'] },
        includeHashtags:{ type: 'boolean', default: true },
        maxHashtags:    { type: 'number', default: 5 },
      },
    },
  },
  {
    name: 'upload_media',
    description: 'Upload an image or video to the portal media library and attach it to a draft.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['draftId', 'filePath', 'mediaType'],
      properties: {
        draftId:   { type: 'string' },
        filePath:  { type: 'string', description: 'Local path or remote URL' },
        mediaType: { type: 'string', enum: ['image/jpeg','image/png','image/webp','video/mp4'] },
        platform:  { type: 'string', description: 'Target platform for dimension validation' },
        altText:   { type: 'string' },
      },
    },
    safetyNote: 'Do not upload content containing personal health data or identifiable participant images without explicit consent',
  },
  {
    name: 'preview_post',
    description: 'Render a platform-specific preview of the post showing how it will appear to the audience. Read-only.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['draftId', 'platform'],
      properties: {
        draftId:  { type: 'string' },
        platform: { type: 'string' },
      },
    },
  },
  {
    name: 'request_approval',
    description: 'Submit a draft to the approval inbox for human review. Post cannot be scheduled or published until approval is granted.',
    tier: 'staff', riskLevel: 2,
    inputSchema: { type: 'object', required: ['draftId'],
      properties: {
        draftId:        { type: 'string' },
        reviewerUserId: { type: 'string', description: 'Specific reviewer (optional — defaults to marketing manager)' },
        note:           { type: 'string', description: 'Context note for the reviewer' },
        urgency:        { type: 'string', enum: ['low','normal','urgent'], default: 'normal' },
      },
    },
    safetyNote: 'Campaign cannot be published until approval status is approved. Never bypass this step.',
  },
  {
    name: 'schedule_post',
    description: 'Schedule an approved draft for future publishing across selected platforms. Staff approval required.',
    tier: 'staff_approval', riskLevel: 3,
    inputSchema: { type: 'object', required: ['draftId', 'scheduledAt'],
      properties: {
        draftId:     { type: 'string' },
        scheduledAt: { type: 'string', format: 'date-time' },
        timezone:    { type: 'string', default: 'America/Toronto' },
        platforms:   { type: 'array', items: { type: 'string' }, description: 'Platform subset (omit to schedule all)' },
      },
    },
    safetyNote: 'Draft must have status=approved before scheduling. Verify the date/time and timezone carefully.',
    tags: ['requires_approval', 'public_facing'],
  },
  {
    name: 'publish_post',
    description: 'Immediately publish an approved draft. REQUIRES a valid approval token. Never publishes autonomously.',
    tier: 'admin', riskLevel: 4,
    inputSchema: { type: 'object', required: ['draftId', 'confirmApprovalId'],
      properties: {
        draftId:          { type: 'string' },
        confirmApprovalId:{ type: 'string', description: 'Approval token from the approval workflow — REQUIRED' },
        platforms:        { type: 'array', items: { type: 'string' }, description: 'Platform subset (omit to publish all approved)' },
      },
    },
    safetyNote: 'Publishing to public channels is irreversible. Verify approval token is valid and not expired before calling.',
    tags: ['requires_approval', 'public_facing', 'irreversible'],
  },
  {
    name: 'get_post_status',
    description: 'Return the current publication status of a draft across all target platforms: queued, publishing, published, or failed.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['draftId'],
      properties: { draftId: { type: 'string' } },
    },
  },
  {
    name: 'retry_failed_post',
    description: 'Retry publishing on platforms where a post failed. Maximum 3 retries per platform.',
    tier: 'staff', riskLevel: 3,
    inputSchema: { type: 'object', required: ['draftId'],
      properties: {
        draftId:   { type: 'string' },
        platforms: { type: 'array', items: { type: 'string' }, description: 'Specific failed platforms to retry (all if omitted)' },
      },
    },
    safetyNote: 'Do not retry if the failure was a platform ban, policy violation, or API credential issue. Investigate first.',
  },
  {
    name: 'read_analytics',
    description: 'Retrieve reach, impressions, clicks, engagement rate, and conversions for a post or campaign across platforms.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object',
      properties: {
        draftId:    { type: 'string', description: 'Specific post (provide draftId or campaignId)' },
        campaignId: { type: 'string', description: 'Campaign rollup' },
        platform:   { type: 'string', description: 'Filter to one platform (omit for all)' },
        dateFrom:   { type: 'string', format: 'date' },
        dateTo:     { type: 'string', format: 'date' },
        metrics:    { type: 'array', items: { type: 'string', enum: ['impressions','reach','clicks','engagement','conversions','follower_change'] } },
      },
    },
  },
  {
    name: 'read_comments',
    description: 'Retrieve recent comments on a published post. Read-only — does NOT reply automatically.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['draftId', 'platform'],
      properties: {
        draftId:   { type: 'string' },
        platform:  { type: 'string' },
        limit:     { type: 'number', default: 20 },
        sentiment: { type: 'string', enum: ['positive','negative','neutral','all'], default: 'all' },
      },
    },
    safetyNote: 'Return comment content only — never surface commenter personal data or linked profiles beyond what the public post shows',
  },
  {
    name: 'draft_reply',
    description: 'Generate a reply draft for a comment. Creates draft ONLY — never posts automatically. Human must approve and post manually.',
    tier: 'auto', riskLevel: 1,
    inputSchema: { type: 'object', required: ['commentId', 'platform'],
      properties: {
        commentId: { type: 'string' },
        platform:  { type: 'string' },
        tone:      { type: 'string', enum: ['professional','warm','concise','empathetic'] },
        context:   { type: 'string', description: 'Additional context for reply generation' },
      },
    },
    safetyNote: 'This tool ONLY generates a draft. The human must copy it to the platform and post manually. Do not expose a "post now" flow.',
  },
  {
    name: 'pause_campaign',
    description: 'Pause all scheduled posts in a campaign. Used during brand incidents or policy reviews. Requires admin approval.',
    tier: 'admin', riskLevel: 4,
    inputSchema: { type: 'object', required: ['campaignId', 'reason'],
      properties: {
        campaignId: { type: 'string' },
        reason:     { type: 'string', description: 'Reason for pause — required for audit log' },
        pausedBy:   { type: 'string' },
      },
    },
    safetyNote: 'Pausing cancels queued posts but does not delete them. Resume is possible. Log the reason for every pause.',
    tags: ['requires_approval'],
  },
  {
    name: 'disconnect_account',
    description: 'Revoke and disconnect a social media account. Tokens are permanently deleted. All scheduled posts on this account are cancelled.',
    tier: 'admin_destructive', riskLevel: 5,
    inputSchema: { type: 'object', required: ['accountId', 'confirmText'],
      properties: {
        accountId:   { type: 'string' },
        reason:      { type: 'string' },
        confirmText: { type: 'string', description: "Must be the literal string 'DISCONNECT' to confirm" },
      },
    },
    safetyNote: 'IRREVERSIBLE — tokens are deleted and all scheduled posts on this account are cancelled. Re-connecting requires a new OAuth flow.',
    tags: ['requires_approval', 'irreversible'],
  },
];

export const SOCIAL_MCP: McpServerManifest = {
  id:          'social-mcp',
  slug:        'social-mcp',
  name:        'Social Media MCP',
  description: 'Draft, adapt, approve, schedule, publish, analyze, and manage social media across 16+ platforms. Wraps Postiz, Nango OAuth, and custom connectors for Telegram, WhatsApp, and Google Business.',
  version:     '2.0.0',
  tools:       TOOLS,
  backingServices: [
    'Postiz (14 platforms via OAuth)',
    'Postiz MCP adapter',
    'Nango (OAuth token management)',
    'Telegram Bot API (custom connector)',
    'WhatsApp Business API (custom connector)',
    'Google Business Profile API (custom connector)',
    'Manual-publishing queue (Quora)',
  ],
  availability: 'custom',
  implementationNote: 'Postiz MCP (antoniolg/postiz-mcp) is the AI control layer. Build custom connectors for Telegram, WhatsApp Business, and Google Business using MCP TypeScript SDK. Quora support is manual-only — no automated posting.',
};
