'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
type Row=Record<string,any>; type Data={workspace:Row|null;channels:Row[];assets:Row[];jobs:Row[];interactions:Row[];forms:Row[];events:Row[]};
const empty:Data={workspace:null,channels:[],assets:[],jobs:[],interactions:[],forms:[],events:[]};
export default function DigitalMarketing(){const[data,setData]=useState<Data>(empty);const[title,setTitle]=useState('Yoga for busy professionals');const[script,setScript]=useState('Take one quiet minute to reset your breath, release your shoulders, and make space for focused movement. Join SohamYoga for a guided beginner-friendly class.');const[formName,setFormName]=useState('Campaign enquiry');const[formUrl,setFormUrl]=useState('http://127.0.0.1:8085/contact');const[busy,setBusy]=useState('');const[notice,setNotice]=useState('');
 const load=useCallback(()=>fetch('/api/digital-marketing',{cache:'no-store'}).then(r=>r.json()).then(setData),[]);useEffect(()=>{void load();const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);
 async function renderVideo(e:FormEvent){e.preventDefault();setBusy('video');setNotice('');const r=await fetch('/api/digital-marketing/video/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,script})});const j=await r.json();setNotice(r.ok?`Real MP4 rendered: ${j.asset.filePath}`:j.error);setBusy('');await load()}
 async function action(body:Row){setBusy(body.action);const r=await fetch('/api/digital-marketing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setNotice(r.ok?'Saved successfully':j.error);setBusy('');await load()}
 return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Digital Marketing Production</h1><p className="text-sm text-gray-500">Real assets, approval, schedules, provider readiness, responses, attribution and audit events.</p></header>
 <section className="grid gap-3 md:grid-cols-4">{[['Channels',data.channels.length],['Assets',data.assets.length],['Jobs',data.jobs.length],['Open responses',data.interactions.filter(x=>x.response_status==='new').length]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-white p-4"><div className="text-xs text-gray-500">{k}</div><div className="text-2xl font-bold">{v}</div></div>)}</section>
 {notice&&<p role="status" className="rounded border border-blue-200 bg-blue-50 p-3 text-sm">{notice}</p>}
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Provider readiness</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{data.channels.map(c=><div key={c.channel} className="flex justify-between rounded border p-3 text-sm"><span><strong>{c.channel}</strong><br/><span className="text-gray-500">{c.provider}</span></span><span className={c.status==='connected'?'text-green-700':'text-amber-700'}>{c.status}</span></div>)}</div></section>
 <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={renderVideo} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Create narrated video</h2><label className="block text-sm">Title<input className="mt-1 w-full rounded border p-2" value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="block text-sm">Approved script<textarea className="mt-1 h-36 w-full rounded border p-2" value={script} onChange={e=>setScript(e.target.value)} required/></label><button disabled={!!busy} className="rounded bg-brand-600 px-4 py-2 text-white disabled:opacity-50">{busy==='video'?'Rendering…':'Render real MP4'}</button><p className="text-xs text-gray-500">Local narration and FFmpeg rendering. Output remains review-required.</p></form>
 <form onSubmit={e=>{e.preventDefault();void action({action:'form_link',name:formName,destinationUrl:formUrl,utmSource:'portal',utmMedium:'campaign'})}} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Link feedback or lead form</h2><label className="block text-sm">Name<input className="mt-1 w-full rounded border p-2" value={formName} onChange={e=>setFormName(e.target.value)} required/></label><label className="block text-sm">Destination URL<input type="url" className="mt-1 w-full rounded border p-2" value={formUrl} onChange={e=>setFormUrl(e.target.value)} required/></label><button disabled={!!busy} className="rounded bg-gray-800 px-4 py-2 text-white">Create attributed link</button></form></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Assets and approval</h2><div className="mt-3 space-y-2">{data.assets.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3 text-sm"><span><strong>{a.title}</strong> · {a.asset_type} · {a.status}{a.duration_seconds&&` · ${Number(a.duration_seconds).toFixed(1)}s`}</span><span className="flex gap-2">{a.file_path&&<a className="text-blue-700 underline" href={a.file_path} target="_blank">Preview</a>}{a.status==='ready_for_review'&&<button className="rounded bg-green-700 px-3 py-1 text-white" onClick={()=>action({action:'approve_asset',assetId:a.id})}>Approve</button>}{a.status==='approved'&&<button className="rounded bg-red-700 px-3 py-1 text-white" onClick={()=>action({action:'schedule_publish',assetId:a.id,channel:'youtube',scheduledAt:new Date(Date.now()+3600000).toISOString()})}>Schedule YouTube +1h</button>}</span></div>)}{!data.assets.length&&<p className="text-sm text-gray-400">No assets yet.</p>}</div></section>
 <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Scheduled jobs</h2>{data.jobs.slice(0,15).map(j=><div key={j.id} className="mt-2 rounded border p-2 text-xs"><strong>{j.job_type}</strong> · {j.status} · {new Date(j.scheduled_at).toLocaleString()}{j.blocker&&<div className="text-amber-700">{j.blocker}</div>}</div>)}</div><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Response and feedback queue</h2>{data.interactions.slice(0,15).map(i=><div key={i.id} className="mt-2 rounded border p-2 text-xs"><strong>{i.channel}</strong> · {i.direction} · {i.intent||'unclassified'} · {i.response_status}</div>)}{!data.interactions.length&&<p className="mt-3 text-sm text-gray-400">No provider responses ingested yet.</p>}</div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Tracking and audit log</h2>{data.events.slice(0,20).map((e,i)=><div key={i} className="mt-2 text-xs">{new Date(e.occurred_at).toLocaleString()} · <strong>{e.event_name}</strong> · {e.outcome} · {e.actor}</div>)}</section></div>}
