import { NextRequest} from 'next/server';
import { query } from '@/lib/postgres';
import { ensureSocialIntelligenceSchema } from '@/lib/social-intelligence-schema';

import { requireAdmin } from '@/lib/admin-auth';
interface ContentTypeConfigDef {
  platform: string;
  content_type: string;
  display_name: string;
  max_chars: number | null;
  max_images: number;
  max_video_mb: number | null;
  max_duration_seconds: number | null;
  supported_aspect_ratios: string[];
  required_fields: string[];
  optional_fields: string[];
  best_posting_times: string[];
  avg_engagement_rate: number;
  tips: string[];
}

const CONTENT_TYPE_CONFIGS: ContentTypeConfigDef[] = [
  // ── YouTube ──────────────────────────────────────────────────────────
  { platform:'youtube', content_type:'video_post', display_name:'YouTube Video',
    max_chars:5000, max_images:1, max_video_mb:128000, max_duration_seconds:43200,
    supported_aspect_ratios:['16:9','4:3'],
    required_fields:['title','description','tags','thumbnail'],
    optional_fields:['cta_url','chapters','end_screen'],
    best_posting_times:['Tuesday 10am','Thursday 3pm','Saturday 11am'],
    avg_engagement_rate:4.5,
    tips:['Thumbnail CTR determines 70% of initial views','Use chapters for videos over 10 min','First 30 seconds retention is the key metric','Include target keyword in title first 3 words','Pin a comment with links immediately after publishing'] },
  { platform:'youtube', content_type:'short', display_name:'YouTube Short',
    max_chars:100, max_images:0, max_video_mb:256, max_duration_seconds:60,
    supported_aspect_ratios:['9:16'],
    required_fields:['title'],
    optional_fields:['caption','tags'],
    best_posting_times:['Daily 12pm','Friday 5pm'],
    avg_engagement_rate:6.2,
    tips:['Hook in first 3 seconds','Add text overlays for silent viewers','End with subscribe CTA','Loop-able endings boost watch time','Hashtag #Shorts in title'] },
  { platform:'youtube', content_type:'live', display_name:'YouTube Live',
    max_chars:5000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','scheduled_time'],
    optional_fields:['description','thumbnail'],
    best_posting_times:['Weekend 2pm','Weekday 7pm'],
    avg_engagement_rate:5.8,
    tips:['Promote 48h in advance','Engage comments in real time','Pin a welcome comment at start','Schedule premieres for pre-recorded live feel'] },
  { platform:'youtube', content_type:'community_post', display_name:'YouTube Community Post',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','16:9'],
    required_fields:['caption'],
    optional_fields:['media_urls','poll'],
    best_posting_times:['Monday 9am','Thursday 2pm'],
    avg_engagement_rate:3.1,
    tips:['Use polls to boost engagement','Share behind-scenes content','Link to new video for traffic'] },

  // ── Facebook ─────────────────────────────────────────────────────────
  { platform:'facebook', content_type:'text_post', display_name:'Facebook Text Post',
    max_chars:63206, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['caption'],
    optional_fields:['link'],
    best_posting_times:['Wednesday 11am','Friday 1pm','Sunday 12pm'],
    avg_engagement_rate:3.2,
    tips:['Keep organic posts under 80 chars for max reach','Include a question to boost comments','No external links in post body — put in comments','Stories > posts for algorithm reach'] },
  { platform:'facebook', content_type:'image_post', display_name:'Facebook Image Post',
    max_chars:63206, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1','4:5'],
    required_fields:['caption'],
    optional_fields:['media_urls','link'],
    best_posting_times:['Wednesday 11am','Friday 1pm'],
    avg_engagement_rate:4.1,
    tips:['1200×628px for link posts','Use bright colors to stop scroll','Alt text improves accessibility and reach','Tag relevant accounts in images'] },
  { platform:'facebook', content_type:'video_post', display_name:'Facebook Video Post',
    max_chars:63206, max_images:0, max_video_mb:10240, max_duration_seconds:14400,
    supported_aspect_ratios:['16:9','1:1','4:5'],
    required_fields:['media_urls'],
    optional_fields:['caption','thumbnail_url'],
    best_posting_times:['Thursday 1pm','Friday 11am'],
    avg_engagement_rate:5.7,
    tips:['Add captions — 85% watch without sound','Square video outperforms landscape on mobile','Front-load value in first 3 seconds'] },
  { platform:'facebook', content_type:'carousel', display_name:'Facebook Carousel',
    max_chars:63206, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['caption','media_urls'],
    optional_fields:['cta_text','cta_url'],
    best_posting_times:['Tuesday 1pm','Thursday 11am'],
    avg_engagement_rate:5.3,
    tips:['Tell a story across cards','Put the hook on card 1','Each card needs its own CTA','Use 3-7 cards for best completion rate'] },
  { platform:'facebook', content_type:'story', display_name:'Facebook Story',
    max_chars:15, max_images:1, max_video_mb:null, max_duration_seconds:20,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption','link'],
    best_posting_times:['Morning 8am','Evening 7pm'],
    avg_engagement_rate:3.8,
    tips:['Use polls and sliders for interaction','24h window — post time-sensitive content','Add swipe-up link for conversions','First story appears first in viewer list'] },
  { platform:'facebook', content_type:'reel', display_name:'Facebook Reel',
    max_chars:2200, max_images:0, max_video_mb:1024, max_duration_seconds:90,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption','hashtags'],
    best_posting_times:['Tuesday 9am','Thursday 5pm'],
    avg_engagement_rate:6.5,
    tips:['Original audio boosts distribution','Hook in first 2 seconds','Add trending music from library','Longer reels (30-90s) get more reach'] },
  { platform:'facebook', content_type:'event', display_name:'Facebook Event',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','scheduled_time'],
    optional_fields:['description','media_urls','cta_url'],
    best_posting_times:['Monday 10am','Wednesday 12pm'],
    avg_engagement_rate:4.2,
    tips:['Create event 2+ weeks in advance','Post in event feed weekly','Use co-hosts to reach new audiences'] },
  { platform:'facebook', content_type:'poll', display_name:'Facebook Poll',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['caption','options'],
    optional_fields:[],
    best_posting_times:['Tuesday 11am','Thursday 2pm'],
    avg_engagement_rate:7.1,
    tips:['2 options outperform 4 options','Yes/No questions get most votes','Ask something your audience cares about'] },

  // ── Instagram ─────────────────────────────────────────────────────────
  { platform:'instagram', content_type:'image_post', display_name:'Instagram Image Post',
    max_chars:2200, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','4:5','16:9'],
    required_fields:['media_urls','caption'],
    optional_fields:['hashtags','mentions'],
    best_posting_times:['Monday 11am','Wednesday 10am','Friday 11am'],
    avg_engagement_rate:4.7,
    tips:['Use all 30 hashtags for max reach','Geo-tag for local discovery','First line must hook before "more"','Profile grid aesthetic drives follows'] },
  { platform:'instagram', content_type:'carousel', display_name:'Instagram Carousel',
    max_chars:2200, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','4:5'],
    required_fields:['media_urls','caption'],
    optional_fields:['hashtags'],
    best_posting_times:['Tuesday 9am','Thursday 11am'],
    avg_engagement_rate:6.8,
    tips:['Swipe-to-learn format drives 3× saves','Last slide CTA boosts DMs','First slide must compel swipe','Use consistent font/color for brand'] },
  { platform:'instagram', content_type:'reel', display_name:'Instagram Reel',
    max_chars:2200, max_images:0, max_video_mb:null, max_duration_seconds:90,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption','hashtags','thumbnail_url'],
    best_posting_times:['Monday 9am','Wednesday 11am','Friday 9am'],
    avg_engagement_rate:8.2,
    tips:['Use trending audio','Show transformation in 3 clips','Add text for silent viewers','Hook in first 1 second','Share to stories for extra reach'] },
  { platform:'instagram', content_type:'story', display_name:'Instagram Story',
    max_chars:150, max_images:1, max_video_mb:null, max_duration_seconds:15,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption','link'],
    best_posting_times:['Morning 8am','Lunch 12pm','Evening 8pm'],
    avg_engagement_rate:3.5,
    tips:['Use countdown stickers for launches','Poll to boost algorithm','24h window — post consistently','Add link sticker for bio traffic'] },
  { platform:'instagram', content_type:'shopping_post', display_name:'Instagram Shopping Post',
    max_chars:2200, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','4:5'],
    required_fields:['media_urls','product_tags'],
    optional_fields:['caption','hashtags'],
    best_posting_times:['Thursday 11am','Saturday 10am'],
    avg_engagement_rate:4.9,
    tips:['Tag up to 5 products per image','Lifestyle photos convert better than product shots','Include price in caption for qualified clicks'] },
  { platform:'instagram', content_type:'igtv', display_name:'Instagram IGTV',
    max_chars:2200, max_images:0, max_video_mb:3500, max_duration_seconds:3600,
    supported_aspect_ratios:['9:16','16:9'],
    required_fields:['media_urls','title'],
    optional_fields:['description','thumbnail_url'],
    best_posting_times:['Wednesday 1pm','Saturday 11am'],
    avg_engagement_rate:3.9,
    tips:['Series format builds subscribers','Promote on feed + stories','Add chapters for long content'] },

  // ── Twitter/X ─────────────────────────────────────────────────────────
  { platform:'x_twitter', content_type:'tweet', display_name:'X/Twitter Tweet',
    max_chars:280, max_images:4, max_video_mb:512, max_duration_seconds:140,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['caption'],
    optional_fields:['media_urls','hashtags'],
    best_posting_times:['Tuesday 9am','Thursday 8am','Wednesday 12pm'],
    avg_engagement_rate:1.8,
    tips:['No links = 3× more reach','Images get 150% more retweets','Ask questions to drive replies','Tweet at conversations, not at void'] },
  { platform:'x_twitter', content_type:'thread', display_name:'X/Twitter Thread',
    max_chars:280, max_images:4, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['caption'],
    optional_fields:['media_urls','hashtags'],
    best_posting_times:['Tuesday 8am','Thursday 7am'],
    avg_engagement_rate:4.2,
    tips:['Hook in tweet 1','Number each tweet (1/n)','End with CTA in final tweet','Thread bookmarks drive discoverability'] },
  { platform:'x_twitter', content_type:'poll', display_name:'X/Twitter Poll',
    max_chars:280, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['caption','options'],
    optional_fields:[],
    best_posting_times:['Monday 10am','Wednesday 11am'],
    avg_engagement_rate:5.1,
    tips:['Ask provocative yes/no for max engagement','7-day polls generate most votes','Comment your own take to drive discussion'] },
  { platform:'x_twitter', content_type:'image_tweet', display_name:'X/Twitter Image Tweet',
    max_chars:280, max_images:4, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['caption','media_urls'],
    optional_fields:['hashtags'],
    best_posting_times:['Tuesday 9am','Friday 10am'],
    avg_engagement_rate:3.2,
    tips:['Alt text improves accessibility + SEO','4 images in grid = most engagement','Infographic images drive retweets'] },
  { platform:'x_twitter', content_type:'spaces', display_name:'X/Twitter Spaces',
    max_chars:280, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','scheduled_time'],
    optional_fields:['description'],
    best_posting_times:['Tuesday 7pm','Thursday 8pm'],
    avg_engagement_rate:3.8,
    tips:['Promote 24h in advance via pinned tweet','Co-hosts bring their audience','Record and share replay after'] },
  { platform:'x_twitter', content_type:'video_tweet', display_name:'X/Twitter Video Tweet',
    max_chars:280, max_images:0, max_video_mb:512, max_duration_seconds:140,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['caption','media_urls'],
    optional_fields:['thumbnail_url'],
    best_posting_times:['Tuesday 10am','Thursday 6pm'],
    avg_engagement_rate:2.7,
    tips:['Add captions — autoplay muted','Hook in first 2 seconds','Native video outperforms YouTube links'] },

  // ── LinkedIn ─────────────────────────────────────────────────────────
  { platform:'linkedin', content_type:'text_post', display_name:'LinkedIn Text Post',
    max_chars:3000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['caption'],
    optional_fields:['hashtags'],
    best_posting_times:['Tuesday 8am','Wednesday 12pm','Thursday 5pm'],
    avg_engagement_rate:5.4,
    tips:['3-5 line hook before "see more"','Hashtags in comments not caption','Dwell time matters — long form wins','Personal stories outperform tips posts','End every post with a question'] },
  { platform:'linkedin', content_type:'image_post', display_name:'LinkedIn Image Post',
    max_chars:3000, max_images:9, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','16:9','4:5'],
    required_fields:['caption'],
    optional_fields:['media_urls','hashtags'],
    best_posting_times:['Tuesday 9am','Thursday 11am'],
    avg_engagement_rate:4.8,
    tips:['Infographics perform 94% better','Bold text in design for key stats','Alt text for accessibility + reach'] },
  { platform:'linkedin', content_type:'video_post', display_name:'LinkedIn Video Post',
    max_chars:3000, max_images:0, max_video_mb:5120, max_duration_seconds:600,
    supported_aspect_ratios:['1:1','16:9'],
    required_fields:['media_urls'],
    optional_fields:['caption','thumbnail_url'],
    best_posting_times:['Wednesday 10am','Thursday 12pm'],
    avg_engagement_rate:6.1,
    tips:['Square 1:1 performs best','Add captions — 80% watch muted','LinkedIn native video gets 5× more reach than YouTube links','Keep under 2 min for decision-makers'] },
  { platform:'linkedin', content_type:'article', display_name:'LinkedIn Article',
    max_chars:120000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','description'],
    optional_fields:['thumbnail_url','hashtags'],
    best_posting_times:['Tuesday 8am','Thursday 8am'],
    avg_engagement_rate:4.3,
    tips:['Titles with numbers get 36% more views','Republish after 7 days if low reach','Cross-post to newsletter for double reach','1500–2000 words is ideal length'] },
  { platform:'linkedin', content_type:'document_post', display_name:'LinkedIn Document Post',
    max_chars:3000, max_images:300, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','4:3'],
    required_fields:['media_urls'],
    optional_fields:['caption','title'],
    best_posting_times:['Tuesday 7am','Wednesday 8am'],
    avg_engagement_rate:7.3,
    tips:['Carousel PDFs get 3× engagement vs images','Use "swipe" hooks in caption','Bold headlines on each slide','Add page numbers for professionalism'] },
  { platform:'linkedin', content_type:'event', display_name:'LinkedIn Event',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','scheduled_time'],
    optional_fields:['description','media_urls'],
    best_posting_times:['Monday 9am','Wednesday 10am'],
    avg_engagement_rate:4.6,
    tips:['Invite connections personally for first 100 RSVPs','Go live during event for reach boost'] },
  { platform:'linkedin', content_type:'newsletter', display_name:'LinkedIn Newsletter',
    max_chars:120000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','description'],
    optional_fields:['thumbnail_url'],
    best_posting_times:['Tuesday 7am','Thursday 7am'],
    avg_engagement_rate:5.2,
    tips:['Weekly cadence builds subscriber habit','Niche > broad audience for B2B','Consistent publishing day trains subscribers','Teaser post to feed before publishing'] },
  { platform:'linkedin', content_type:'poll', display_name:'LinkedIn Poll',
    max_chars:300, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['caption','options'],
    optional_fields:[],
    best_posting_times:['Monday 10am','Wednesday 2pm'],
    avg_engagement_rate:6.4,
    tips:['4 options outperform 2 on LinkedIn','Industry-relevant questions drive B2B engagement','Share results with commentary after'] },

  // ── TikTok ────────────────────────────────────────────────────────────
  { platform:'tiktok', content_type:'video_post', display_name:'TikTok Video',
    max_chars:2200, max_images:0, max_video_mb:287, max_duration_seconds:600,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption','hashtags','thumbnail_url'],
    best_posting_times:['Tuesday 9am','Thursday 7pm','Friday 5pm'],
    avg_engagement_rate:9.4,
    tips:['Hook in first 1 second','Jump cuts every 2-3 seconds','Use trending sounds (3× discovery)','Text overlay for accessibility','CTA at 80% of video = higher completion','Reply to comments with video for extra reach'] },
  { platform:'tiktok', content_type:'live', display_name:'TikTok Live',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['9:16'],
    required_fields:['title'],
    optional_fields:['thumbnail_url'],
    best_posting_times:['Evening 7pm','Weekend 2pm'],
    avg_engagement_rate:7.8,
    tips:['Go live when audience is online','Gifts spike algorithm visibility','Engage every comment by name','Save and post replay as regular video'] },
  { platform:'tiktok', content_type:'story', display_name:'TikTok Story',
    max_chars:150, max_images:1, max_video_mb:null, max_duration_seconds:15,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls'],
    optional_fields:['caption'],
    best_posting_times:['Morning 8am','Evening 8pm'],
    avg_engagement_rate:5.1,
    tips:['24h window — post daily for consistency','Behind-scenes content performs well','Link to latest video for traffic'] },
  { platform:'tiktok', content_type:'photo_post', display_name:'TikTok Photo Slideshow',
    max_chars:2200, max_images:35, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['9:16','1:1'],
    required_fields:['media_urls'],
    optional_fields:['caption','hashtags'],
    best_posting_times:['Tuesday 12pm','Thursday 5pm'],
    avg_engagement_rate:4.2,
    tips:['Use trending audio with photos','Tell a story across slides','First image = hook image','Add text overlay on key slides'] },

  // ── WhatsApp Business ─────────────────────────────────────────────────
  { platform:'whatsapp_business', content_type:'text_message', display_name:'WhatsApp Text Message',
    max_chars:4096, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['phone_number'],
    optional_fields:['text'],
    best_posting_times:['Tuesday 10am','Thursday 2pm'],
    avg_engagement_rate:8.5,
    tips:['Business opt-in required before messaging','Response window: 24h for customer-initiated messages','Use template messages for proactive outreach (policy-compliant)','Keep messages concise — WhatsApp is a conversational channel','Never send unsolicited bulk messages'] },
  { platform:'whatsapp_business', content_type:'image_message', display_name:'WhatsApp Image Message',
    max_chars:1024, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','16:9','4:5'],
    required_fields:['phone_number','image_url'],
    optional_fields:['caption'],
    best_posting_times:['Wednesday 11am','Friday 1pm'],
    avg_engagement_rate:9.1,
    tips:['Max 5MB image size','JPEG or PNG only','Caption under 1024 chars'] },
  { platform:'whatsapp_business', content_type:'video_message', display_name:'WhatsApp Video Message',
    max_chars:1024, max_images:0, max_video_mb:16, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','9:16'],
    required_fields:['phone_number','video_url'],
    optional_fields:['caption'],
    best_posting_times:['Thursday 3pm'],
    avg_engagement_rate:8.8,
    tips:['Max 16MB video','MP4 or 3GP format','Short clips under 60s perform best'] },
  { platform:'whatsapp_business', content_type:'template_message', display_name:'WhatsApp Template Message',
    max_chars:1024, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['template_name','language_code'],
    optional_fields:['components'],
    best_posting_times:['Monday 9am','Thursday 10am'],
    avg_engagement_rate:7.2,
    tips:['Pre-approved templates only for proactive outreach','Register templates in Meta Business Manager','Templates must be approved before use — allow 24-48h','Personalize with parameter substitution for higher CTR'] },
  { platform:'whatsapp_business', content_type:'document_message', display_name:'WhatsApp Document Message',
    max_chars:1024, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['phone_number','document_url'],
    optional_fields:['filename','caption'],
    best_posting_times:['Tuesday 9am','Wednesday 10am'],
    avg_engagement_rate:6.5,
    tips:['Max 100MB','PDF, DOCX, XLSX supported','Great for sending invoices, brochures, guides'] },
  { platform:'whatsapp_business', content_type:'catalog_message', display_name:'WhatsApp Catalog Message',
    max_chars:4096, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['catalog_id'],
    optional_fields:['body','footer'],
    best_posting_times:['Saturday 11am'],
    avg_engagement_rate:10.2,
    tips:['Set up catalog in Commerce Manager first','Product images must be square 1:1','Catalog browsing in-chat drives 25% more product views'] },

  // ── Pinterest ─────────────────────────────────────────────────────────
  { platform:'pinterest', content_type:'pin', display_name:'Pinterest Pin',
    max_chars:500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['2:3','1:1','16:9'],
    required_fields:['image_url','board_id'],
    optional_fields:['description','link','title'],
    best_posting_times:['Saturday 8pm','Sunday 8pm','Friday 3pm'],
    avg_engagement_rate:3.5,
    tips:['Vertical images (2:3 ratio) get 60% more repins','Include price for shopping pins','Use keywords in title and description for SEO','Pin to the most relevant board first','Bright backgrounds outperform white for CTR'] },
  { platform:'pinterest', content_type:'idea_pin', display_name:'Pinterest Idea Pin',
    max_chars:250, max_images:10, max_video_mb:null, max_duration_seconds:60,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_urls','board_id'],
    optional_fields:['title','description'],
    best_posting_times:['Saturday 8pm','Sunday 3pm'],
    avg_engagement_rate:5.2,
    tips:['Step-by-step content gets 9× more comments','Use text overlay on each page','Add ingredient or supply lists for how-to content','Idea Pins are not linkable — use for awareness, not conversion'] },
  { platform:'pinterest', content_type:'video_pin', display_name:'Pinterest Video Pin',
    max_chars:500, max_images:0, max_video_mb:2048, max_duration_seconds:900,
    supported_aspect_ratios:['9:16','1:1','16:9'],
    required_fields:['video_url','board_id'],
    optional_fields:['title','description','thumbnail_url'],
    best_posting_times:['Friday 3pm','Saturday 8pm'],
    avg_engagement_rate:4.8,
    tips:['Autoplay on scroll — hook in first 2 seconds','Add captions for silent viewing','Include link in description for traffic','Videos between 15s–60s perform best'] },
  { platform:'pinterest', content_type:'rich_pin', display_name:'Pinterest Rich Pin',
    max_chars:500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['2:3'],
    required_fields:['image_url','board_id'],
    optional_fields:['link'],
    best_posting_times:['Saturday 8pm'],
    avg_engagement_rate:4.2,
    tips:['Requires meta tags on your website for data sync','Product Rich Pins auto-update prices','Recipe Rich Pins include ingredients automatically','App Rich Pins drive installs directly'] },
  { platform:'pinterest', content_type:'board_section', display_name:'Pinterest Board Section',
    max_chars:250, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['board_id','section_name'],
    optional_fields:[],
    best_posting_times:[],
    avg_engagement_rate:2.0,
    tips:['Organize pins into sections for better discovery','Use keyword-rich section names','Section-level analytics available in Pinterest Analytics'] },

  // ── Reddit ────────────────────────────────────────────────────────────
  { platform:'reddit', content_type:'text_post', display_name:'Reddit Text Post',
    max_chars:40000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['subreddit','title'],
    optional_fields:['body','flair'],
    best_posting_times:['Monday 9am','Tuesday 10am','Wednesday 9am'],
    avg_engagement_rate:6.2,
    tips:['Read subreddit rules before posting','Value-first content — no overt promotion','Build karma by commenting before posting','Title is everything — spend 50% effort on it','Post at peak subreddit activity time — check r/subreddit/about'] },
  { platform:'reddit', content_type:'link_post', display_name:'Reddit Link Post',
    max_chars:300, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['url','title','subreddit'],
    optional_fields:['flair'],
    best_posting_times:['Tuesday 10am','Wednesday 9am'],
    avg_engagement_rate:5.8,
    tips:['Link posts can be removed if the domain is blocked — check subreddit rules','Engage in comments immediately after posting','Cross-post to related subreddits for reach'] },
  { platform:'reddit', content_type:'image_post', display_name:'Reddit Image Post',
    max_chars:500, max_images:20, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','16:9','4:3'],
    required_fields:['media_urls','title','subreddit'],
    optional_fields:['caption'],
    best_posting_times:['Tuesday 10am','Thursday 9am'],
    avg_engagement_rate:7.1,
    tips:['Infographics get more upvotes than stock photos','Add captions to explain complex images','Gallery posts (multiple images) perform well for tutorials'] },
  { platform:'reddit', content_type:'video_post', display_name:'Reddit Video Post',
    max_chars:500, max_images:0, max_video_mb:1024, max_duration_seconds:900,
    supported_aspect_ratios:['16:9','9:16'],
    required_fields:['media_urls','title','subreddit'],
    optional_fields:['caption'],
    best_posting_times:['Wednesday 12pm'],
    avg_engagement_rate:6.4,
    tips:['Reddit native video auto-plays','Videos under 3 min get more completion','Add subtitles for silent viewers'] },
  { platform:'reddit', content_type:'poll', display_name:'Reddit Poll',
    max_chars:300, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','subreddit','options'],
    optional_fields:[],
    best_posting_times:['Monday 10am','Wednesday 9am'],
    avg_engagement_rate:5.1,
    tips:['Polls expire after 7 days — pick a good window','2-6 options work best','Share results in follow-up comment'] },

  // ── Snapchat ──────────────────────────────────────────────────────────
  { platform:'snapchat', content_type:'story', display_name:'Snapchat Story',
    max_chars:250, max_images:0, max_video_mb:1024, max_duration_seconds:10,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_file'],
    optional_fields:['caption'],
    best_posting_times:['Evening 8pm','Weekend 2pm'],
    avg_engagement_rate:4.2,
    tips:['Vertical 9:16 full screen only','Add text + stickers for engagement','Stories visible 24h then disappear','Post consistently — Snap score affects reach'] },
  { platform:'snapchat', content_type:'spotlight', display_name:'Snapchat Spotlight',
    max_chars:250, max_images:0, max_video_mb:1024, max_duration_seconds:60,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_file'],
    optional_fields:['caption','hashtags'],
    best_posting_times:['Evening 7pm'],
    avg_engagement_rate:5.5,
    tips:['Spotlight is Snapchat\'s TikTok — public discovery feed','Trending sounds increase spotlight reach','Earn Snapchat Spotlight money if content goes viral'] },
  { platform:'snapchat', content_type:'snap_ad', display_name:'Snapchat Snap Ad',
    max_chars:34, max_images:0, max_video_mb:512, max_duration_seconds:180,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_url','headline','cta'],
    optional_fields:['brand_name'],
    best_posting_times:['Saturday 10am'],
    avg_engagement_rate:3.8,
    tips:['6-second non-skippable format has highest completion','Brand name top-left for awareness','Single CTA button — keep copy short'] },
  { platform:'snapchat', content_type:'collection_ad', display_name:'Snapchat Collection Ad',
    max_chars:34, max_images:4, max_video_mb:512, max_duration_seconds:180,
    supported_aspect_ratios:['9:16'],
    required_fields:['media_url','products'],
    optional_fields:['headline'],
    best_posting_times:['Saturday 10am'],
    avg_engagement_rate:4.5,
    tips:['4-tile product grid for e-commerce','Swipe-up to browse catalog without leaving app','Great for fashion and beauty brands'] },

  // ── Discord ───────────────────────────────────────────────────────────
  { platform:'discord', content_type:'channel_message', display_name:'Discord Channel Message',
    max_chars:2000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['channel_id','server_id'],
    optional_fields:['embeds'],
    best_posting_times:['Wednesday 7pm','Friday 6pm','Saturday 3pm'],
    avg_engagement_rate:7.2,
    tips:['Use @mentions sparingly — reserve for important announcements','Plain text messages feel more authentic than bots','Use #channel-name references to guide users to other channels'] },
  { platform:'discord', content_type:'embed', display_name:'Discord Embed',
    max_chars:4096, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['channel_id'],
    optional_fields:['title','description','color','thumbnail_url','image_url','footer','fields'],
    best_posting_times:['Friday 6pm','Saturday 2pm'],
    avg_engagement_rate:8.1,
    tips:['Color code embeds by content type (blue=info, green=success, red=alert)','Use fields for structured data (key-value pairs)','Embeds support rich markdown within description'] },
  { platform:'discord', content_type:'announcement', display_name:'Discord Announcement',
    max_chars:2000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['server_id'],
    optional_fields:['channel_id'],
    best_posting_times:['Tuesday 5pm','Friday 5pm'],
    avg_engagement_rate:9.5,
    tips:['Use for product releases and major updates only','Announcement channels can be followed by other servers','Cross-publish automatically to followers'] },
  { platform:'discord', content_type:'forum_post', display_name:'Discord Forum Post',
    max_chars:4000, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['channel_id','title'],
    optional_fields:['tags','body'],
    best_posting_times:['Wednesday 6pm'],
    avg_engagement_rate:6.8,
    tips:['Forum posts are indexed and searchable — great for FAQs','Tag posts for discoverability','Pin best answers as starter messages'] },

  // ── Twitch ────────────────────────────────────────────────────────────
  { platform:'twitch', content_type:'stream_title_update', display_name:'Twitch Stream Title Update',
    max_chars:140, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['channel_id'],
    optional_fields:['game_name','tags'],
    best_posting_times:['Before stream start'],
    avg_engagement_rate:5.2,
    tips:['Include game name + unique hook in title','Update title before every stream','Use tags for discoverability in browse','Stream consistently same days/times to build habit'] },
  { platform:'twitch', content_type:'clip_promotion', display_name:'Twitch Clip Cross-Promotion',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:60,
    supported_aspect_ratios:['16:9'],
    required_fields:['clip_id'],
    optional_fields:['caption'],
    best_posting_times:['Day after stream'],
    avg_engagement_rate:6.8,
    tips:['Clips are the organic viral unit on Twitch','Cross-post clips to Twitter/TikTok for cross-platform growth','Pin best clips on your channel page','Compile clips into YouTube highlights'] },
  { platform:'twitch', content_type:'channel_points_reward', display_name:'Twitch Channel Points Reward',
    max_chars:100, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['channel_id','reward_title'],
    optional_fields:['cost','prompt'],
    best_posting_times:[],
    avg_engagement_rate:7.5,
    tips:['Redemption rewards drive engagement during streams','Balance point costs to prevent reward spam','Custom rewards create unique community moments'] },

  // ── Medium ────────────────────────────────────────────────────────────
  { platform:'medium', content_type:'article', display_name:'Medium Article',
    max_chars:100000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title'],
    optional_fields:['subtitle','tags','canonical_url'],
    best_posting_times:['Tuesday 9am','Thursday 10am','Sunday 11am'],
    avg_engagement_rate:4.1,
    tips:['Import from URL if already published elsewhere to avoid duplicate content','Add publication for distribution boost','SEO: title + first paragraph matter most','1500-2000 words is the sweet spot for Medium readership','Use canonical URL to protect SEO on your own domain'] },
  { platform:'medium', content_type:'response', display_name:'Medium Response (Comment)',
    max_chars:5000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['parent_post_url'],
    optional_fields:['body'],
    best_posting_times:['Within 2h of parent post'],
    avg_engagement_rate:3.2,
    tips:['Thoughtful responses drive profile traffic','Link to your relevant articles naturally','Responses on trending articles get wide exposure'] },
  { platform:'medium', content_type:'series', display_name:'Medium Series',
    max_chars:100000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['series_name','article_title'],
    optional_fields:['tags'],
    best_posting_times:['Tuesday 9am','Saturday 11am'],
    avg_engagement_rate:5.4,
    tips:['Series keep readers coming back','Announce series schedule in first post','Consistent naming: "Part 1 of 5" builds commitment'] },

  // ── Substack ──────────────────────────────────────────────────────────
  { platform:'substack', content_type:'newsletter', display_name:'Substack Newsletter Issue',
    max_chars:500000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['subject','body'],
    optional_fields:['subtitle','section'],
    best_posting_times:['Tuesday 9am','Thursday 10am'],
    avg_engagement_rate:28.5,
    tips:['Subscriber-first content wins — no promotional fluff','Consistent send day/time builds open-rate habit','Subject line open rate > body engagement — A/B test subjects','Paywall content after the hook paragraph for conversion','Personal voice outperforms corporate tone every time'] },
  { platform:'substack', content_type:'thread', display_name:'Substack Thread (Note)',
    max_chars:500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1','16:9'],
    required_fields:['body'],
    optional_fields:['image_url'],
    best_posting_times:['Daily 10am'],
    avg_engagement_rate:5.8,
    tips:['Twitter-like short posts for discovery','Notes reach the wider Substack network','Use to tease upcoming newsletter content'] },
  { platform:'substack', content_type:'podcast_episode', display_name:'Substack Podcast Episode',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['title','audio_url'],
    optional_fields:['description','image_url'],
    best_posting_times:['Wednesday 8am'],
    avg_engagement_rate:12.3,
    tips:['Audio newsletters have 65% higher completion than written','Transcript boosts SEO and accessibility','Pair audio with a short written summary for skim-readers'] },

  // ── GitHub ────────────────────────────────────────────────────────────
  { platform:'github', content_type:'release', display_name:'GitHub Release',
    max_chars:50000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['tag_name','title','body'],
    optional_fields:['draft','prerelease','assets'],
    best_posting_times:['Tuesday 10am','Thursday 10am'],
    avg_engagement_rate:6.5,
    tips:['Semantic versioning (v1.2.3) is the standard','Include changelog, migration notes, and breaking changes','Attach binaries for desktop apps','Auto-generate release notes from merged PRs','Tag with prerelease for beta versions'] },
  { platform:'github', content_type:'discussion', display_name:'GitHub Discussion',
    max_chars:65536, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','body','category_id'],
    optional_fields:['labels'],
    best_posting_times:['Monday 10am'],
    avg_engagement_rate:5.1,
    tips:['Great for RFC and community feedback','Pin important discussions to repository','Lock discussions when they become outdated'] },
  { platform:'github', content_type:'gist', display_name:'GitHub Gist',
    max_chars:100000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['description','files'],
    optional_fields:['public'],
    best_posting_times:['Wednesday 10am'],
    avg_engagement_rate:3.8,
    tips:['Gists are ideal for sharing code snippets','Embed gists in blog posts for syntax highlighting','Star count tracks popularity'] },

  // ── GitLab ────────────────────────────────────────────────────────────
  { platform:'gitlab', content_type:'release', display_name:'GitLab Release',
    max_chars:50000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['tag_name','title','description'],
    optional_fields:['milestones','assets'],
    best_posting_times:['Tuesday 10am','Thursday 10am'],
    avg_engagement_rate:5.8,
    tips:['Link release to a milestone for traceability','GitLab Releases support deployment links','Use evidence collection to attach deployment artifacts'] },
  { platform:'gitlab', content_type:'snippet', display_name:'GitLab Snippet',
    max_chars:1000000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','content'],
    optional_fields:['file_name','visibility'],
    best_posting_times:[],
    avg_engagement_rate:2.5,
    tips:['Supports syntax highlighting for 100+ languages','Snippets can be embedded on external sites','Group snippets for shared team code'] },

  // ── Google Business Profile ───────────────────────────────────────────
  { platform:'google_business', content_type:'standard_post', display_name:'Google Business Standard Post',
    max_chars:1500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:3','16:9'],
    required_fields:['summary'],
    optional_fields:['call_to_action','media_url'],
    best_posting_times:['Tuesday 9am','Thursday 9am'],
    avg_engagement_rate:3.2,
    tips:['Post 1-2x per week minimum to stay relevant','Include a photo — 40% more clicks','Add a CTA button (Call Now, Book, Order Online)','Posts expire after 7 days — schedule recurring content','Mention offers in post for conversion lift'] },
  { platform:'google_business', content_type:'event_post', display_name:'Google Business Event Post',
    max_chars:1500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:3','16:9'],
    required_fields:['title','start_date','end_date'],
    optional_fields:['summary','call_to_action','media_url'],
    best_posting_times:['Monday 9am','Wednesday 9am'],
    avg_engagement_rate:4.1,
    tips:['Events appear in local Google Search results','Promote 2 weeks before event start','Add ticket/registration link as CTA'] },
  { platform:'google_business', content_type:'offer_post', display_name:'Google Business Offer Post',
    max_chars:1500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:3','16:9'],
    required_fields:['title'],
    optional_fields:['coupon_code','terms','start_date','end_date','redeem_url'],
    best_posting_times:['Monday 9am','Friday 9am'],
    avg_engagement_rate:5.3,
    tips:['Offers drive foot traffic 25% more than standard posts','Add coupon code for tracking redemptions','Offers show with a special badge in local pack results','Link to redemption page for e-commerce'] },
  { platform:'google_business', content_type:'product_post', display_name:'Google Business Product Post',
    max_chars:1000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['product_name','price'],
    optional_fields:['description','landing_page_url','media_url'],
    best_posting_times:['Tuesday 10am','Saturday 10am'],
    avg_engagement_rate:4.6,
    tips:['Products appear in Google Shopping for local queries','High-quality product images are critical','Keep descriptions benefit-focused, not feature-focused'] },

  // ── Yelp ──────────────────────────────────────────────────────────────
  { platform:'yelp', content_type:'business_response', display_name:'Yelp Review Response',
    max_chars:5000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['review_id','text'],
    optional_fields:[],
    best_posting_times:['Within 24h of review'],
    avg_engagement_rate:0.0,
    tips:['Respond to ALL reviews within 24h — positive and negative','Acknowledge negative feedback professionally','Never argue — potential customers read your responses','Thank positive reviewers by name for personal touch'] },
  { platform:'yelp', content_type:'owner_post', display_name:'Yelp Business Update',
    max_chars:5000, max_images:8, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:3','1:1'],
    required_fields:['text'],
    optional_fields:['media_urls'],
    best_posting_times:['Tuesday 10am','Thursday 10am'],
    avg_engagement_rate:1.8,
    tips:['Keep business info updated — hours, phone, website','COVID/Special hours alerts visible prominently','High-quality interior photos increase calls by 25%'] },

  // ── TripAdvisor ───────────────────────────────────────────────────────
  { platform:'tripadvisor', content_type:'management_response', display_name:'TripAdvisor Management Response',
    max_chars:2000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['review_id','text'],
    optional_fields:[],
    best_posting_times:['Within 48h of review'],
    avg_engagement_rate:0.0,
    tips:['Respond within 48h — speed signals professionalism','Thank positive reviewers by name','Address specific complaints in negative responses','Never copy-paste generic responses — travelers can tell','A good response can convert a hesitant booker'] },
  { platform:'tripadvisor', content_type:'experience_update', display_name:'TripAdvisor Experience Update',
    max_chars:2000, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:3','16:9'],
    required_fields:['text'],
    optional_fields:['media_urls'],
    best_posting_times:['Monday 10am'],
    avg_engagement_rate:2.1,
    tips:['Updated seasonal photos improve click-through','Highlight unique experiences competitors don\'t offer','Amenity updates directly affect ranking algorithm'] },

  // ── Trustpilot ────────────────────────────────────────────────────────
  { platform:'trustpilot', content_type:'review_invitation', display_name:'Trustpilot Review Invitation',
    max_chars:2000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['consumer_email','consumer_name'],
    optional_fields:['reference_id','template_id'],
    best_posting_times:['Within 24h of purchase/service'],
    avg_engagement_rate:22.0,
    tips:['Send within 24h of service delivery for best response rate','Personalized email subject lines increase response 35%','Keep reminder to one follow-up only — don\'t spam','Average review request has 22% response rate'] },
  { platform:'trustpilot', content_type:'review_response', display_name:'Trustpilot Review Response',
    max_chars:3000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['review_id','text'],
    optional_fields:[],
    best_posting_times:['Within 24h of review'],
    avg_engagement_rate:0.0,
    tips:['Public responses build trust with prospective buyers','Acknowledge issues and explain resolution step','Offer to resolve offline for 1-star reviews','Never be defensive — empathy converts doubters'] },
  { platform:'trustpilot', content_type:'service_review', display_name:'Trustpilot Service Review',
    max_chars:1000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['consumer_email','consumer_name'],
    optional_fields:[],
    best_posting_times:[],
    avg_engagement_rate:0.0,
    tips:['Service reviews are submitted by customers — invite via API','Automatic invitation workflows drive 3× more reviews','Trustpilot widget on website boosts organic review volume'] },

  // ── Vimeo ─────────────────────────────────────────────────────────────
  { platform:'vimeo', content_type:'video_upload', display_name:'Vimeo Video Upload',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','4:3','1:1'],
    required_fields:['video_url','title'],
    optional_fields:['description','tags','privacy','thumbnail_url','chapter_timestamps'],
    best_posting_times:['Tuesday 10am','Thursday 3pm'],
    avg_engagement_rate:4.8,
    tips:['Custom thumbnail increases CTR by 30%','Add chapters for videos over 5 minutes','Vimeo embeds support password protection','Review links allow client feedback without publishing','Upload at 1080p minimum — Vimeo transcodes to multiple resolutions'] },
  { platform:'vimeo', content_type:'showcase', display_name:'Vimeo Showcase',
    max_chars:2000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title'],
    optional_fields:['description','custom_domain'],
    best_posting_times:['Monday 9am'],
    avg_engagement_rate:3.5,
    tips:['Showcases replace playlists — great for portfolio/reel','Custom domain for white-label client delivery','Set showcase password for exclusive client access'] },

  // ── Dailymotion ───────────────────────────────────────────────────────
  { platform:'dailymotion', content_type:'video_upload', display_name:'Dailymotion Video Upload',
    max_chars:2000, max_images:1, max_video_mb:4096, max_duration_seconds:3600,
    supported_aspect_ratios:['16:9','4:3'],
    required_fields:['video_url','title','tags'],
    optional_fields:['description','channel','thumbnail_url'],
    best_posting_times:['Tuesday 10am','Thursday 3pm'],
    avg_engagement_rate:2.8,
    tips:['100MB max per API upload — use pull URL for larger files','Add to a channel for organization','Tags are critical for Dailymotion search — use 10+ tags','Title and description in multiple languages for international reach'] },
  { platform:'dailymotion', content_type:'live_stream', display_name:'Dailymotion Live Stream',
    max_chars:2000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','stream_key'],
    optional_fields:['description','thumbnail_url'],
    best_posting_times:['Weekend 2pm'],
    avg_engagement_rate:3.2,
    tips:['Promote stream at least 24h in advance','Dailymotion Live supports RTMP streams','VOD replay auto-published after stream ends'] },

  // ── Spotify ───────────────────────────────────────────────────────────
  { platform:'spotify', content_type:'podcast_episode', display_name:'Spotify Podcast Episode',
    max_chars:4000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['audio_url','title','description'],
    optional_fields:['episode_number','season','explicit','transcript_url'],
    best_posting_times:['Tuesday 8am','Wednesday 8am'],
    avg_engagement_rate:18.5,
    tips:['Submit RSS feed to Spotify for Podcasters for distribution','Transcript boosts discoverability in Spotify search','Episode descriptions improve podcast SEO','Consistent release schedule builds listener habit','Cross-promote on social with audiogram clips'] },
  { platform:'spotify', content_type:'show_update', display_name:'Spotify Show Notes Update',
    max_chars:500, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['description'],
    optional_fields:['cover_art_url'],
    best_posting_times:['Monday 9am'],
    avg_engagement_rate:5.0,
    tips:['Cover art is 3000×3000px minimum','Show description is indexed by Spotify search','Update cover art seasonally to signal active production'] },

  // ── Apple Podcasts ─────────────────────────────────────────────────────
  { platform:'apple_podcasts', content_type:'podcast_episode', display_name:'Apple Podcasts Episode',
    max_chars:4000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['title','description','audio_url'],
    optional_fields:['keywords','episode_type','season','episode_number'],
    best_posting_times:['Tuesday 8am'],
    avg_engagement_rate:21.0,
    tips:['Submit via RSS through Apple Podcasts Connect','Podcast Connect dashboard for analytics','Episode descriptions indexed by Apple search','Apple uses 1400×3000px cover art minimum','Consistency is the #1 growth driver — same day every week'] },
  { platform:'apple_podcasts', content_type:'show_notes', display_name:'Apple Podcasts Show Notes',
    max_chars:2000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['notes'],
    optional_fields:[],
    best_posting_times:[],
    avg_engagement_rate:0.0,
    tips:['Show notes appear in podcast players — make them useful','Include timestamps for long episodes','Add links mentioned in episode for listener follow-up'] },

  // ── SoundCloud ────────────────────────────────────────────────────────
  { platform:'soundcloud', content_type:'track_upload', display_name:'SoundCloud Track Upload',
    max_chars:5000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['audio_url','title'],
    optional_fields:['description','tags','genre','artwork_url'],
    best_posting_times:['Friday 12pm','Saturday 10am'],
    avg_engagement_rate:6.2,
    tips:['Good metadata title/tags for SoundCloud search','Waveform comments build community engagement','Crosspost to social with SoundCloud share link','Reposts from popular accounts are the main discovery mechanism','SoundCloud Go+ placement = major reach boost'] },
  { platform:'soundcloud', content_type:'playlist', display_name:'SoundCloud Playlist',
    max_chars:2000, max_images:1, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['1:1'],
    required_fields:['title','track_ids'],
    optional_fields:['description','artwork_url'],
    best_posting_times:['Friday 12pm'],
    avg_engagement_rate:4.8,
    tips:['Organize tracks by theme or mood','Public playlists appear in profile discovery','Include tracks from other artists for community goodwill'] },
  { platform:'soundcloud', content_type:'repost', display_name:'SoundCloud Repost',
    max_chars:0, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['track_id'],
    optional_fields:[],
    best_posting_times:['Saturday 12pm'],
    avg_engagement_rate:3.1,
    tips:['Reposts appear in followers\' streams','Strategic reposts of peers build reciprocal relationships'] },

  // ── Patreon ───────────────────────────────────────────────────────────
  { platform:'patreon', content_type:'creator_post', display_name:'Patreon Creator Post',
    max_chars:50000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','content'],
    optional_fields:['access_rule','tags','thumbnail_url'],
    best_posting_times:['Tuesday 9am','Thursday 11am'],
    avg_engagement_rate:12.8,
    tips:['Mix public/patron content ratio 30/70 for sustainable growth','Behind-the-scenes posts convert free followers to patrons','Monthly exclusive = key retention driver','Polls and early access are top patron benefits','Consistent posting schedule = lower churn rate'] },
  { platform:'patreon', content_type:'patron_only_post', display_name:'Patreon Patron-Only Post',
    max_chars:50000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','content','min_tier_cents'],
    optional_fields:['tags'],
    best_posting_times:['Wednesday 10am'],
    avg_engagement_rate:18.5,
    tips:['Tier-gate exclusive content to drive upgrades','Early access (48h before public) is the highest-value benefit','Patron comment engagement is a direct retention signal'] },
  { platform:'patreon', content_type:'audio_post', display_name:'Patreon Audio Post',
    max_chars:5000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','audio_url'],
    optional_fields:['description','access_rule'],
    best_posting_times:['Wednesday 8am'],
    avg_engagement_rate:15.2,
    tips:['Patron podcast feeds deliver directly to podcast apps','Audio posts have 65% completion vs 40% for video','Great for q&a recordings and creator commentary'] },
  { platform:'patreon', content_type:'poll', display_name:'Patreon Patron Poll',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['question','options'],
    optional_fields:['end_date'],
    best_posting_times:['Monday 10am'],
    avg_engagement_rate:22.0,
    tips:['Patron polls drive 2× higher engagement than regular posts','Use polls to decide next content direction','Announce poll results publicly to attract new patrons'] },

  // ── Mastodon ──────────────────────────────────────────────────────────
  { platform:'mastodon', content_type:'toot', display_name:'Mastodon Toot',
    max_chars:500, max_images:4, max_video_mb:40, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1','4:5'],
    required_fields:[],
    optional_fields:['content_warning','poll','sensitive'],
    best_posting_times:['Tuesday 10am','Thursday 9am'],
    avg_engagement_rate:4.5,
    tips:['Use content warnings for sensitive topics — required by community norms','Hashtags are the discovery mechanism — no algorithm','No algorithm — recency + following matters most','Federated timeline = cross-instance reach','Public posts boosted by followers reach new audiences quickly'] },
  { platform:'mastodon', content_type:'boost', display_name:'Mastodon Boost (Repost)',
    max_chars:0, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['status_id'],
    optional_fields:[],
    best_posting_times:[],
    avg_engagement_rate:2.5,
    tips:['Boosting quality content builds reciprocal community','Boosted toots reach your followers who don\'t follow the original poster'] },
  { platform:'mastodon', content_type:'poll', display_name:'Mastodon Poll',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['options'],
    optional_fields:['expires_in'],
    best_posting_times:['Tuesday 10am'],
    avg_engagement_rate:5.8,
    tips:['Polls are attached to toots — include context in the toot text','Expiry 24h-72h for best participation'] },
  { platform:'mastodon', content_type:'thread', display_name:'Mastodon Thread',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:[],
    optional_fields:['content_warning'],
    best_posting_times:['Wednesday 10am'],
    avg_engagement_rate:6.2,
    tips:['Number threads (1/N) for easier reading','Add CW to first post for long threads','Reply to your own toot to extend the thread'] },

  // ── Bluesky ───────────────────────────────────────────────────────────
  { platform:'bluesky', content_type:'post', display_name:'Bluesky Post',
    max_chars:300, max_images:4, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1','4:5'],
    required_fields:[],
    optional_fields:['images','link_card','lang'],
    best_posting_times:['Tuesday 10am','Thursday 10am'],
    avg_engagement_rate:5.2,
    tips:['AT Protocol — open and decentralized','Starter packs for community building drive follows','Custom feeds for content curation and discovery','Link cards auto-embed when URL is the last thing in the post','Hashtags not required — search works across post text'] },
  { platform:'bluesky', content_type:'thread', display_name:'Bluesky Thread',
    max_chars:300, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:[],
    optional_fields:[],
    best_posting_times:['Tuesday 10am'],
    avg_engagement_rate:7.1,
    tips:['Threads have higher completion on Bluesky than Twitter/X','Number posts (1/N) for thread clarity','Reply to own post with 🧵 to signal thread start'] },
  { platform:'bluesky', content_type:'quote_post', display_name:'Bluesky Quote Post',
    max_chars:300, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['quoted_post_uri'],
    optional_fields:[],
    best_posting_times:[],
    avg_engagement_rate:4.8,
    tips:['Quote posts add commentary to curated content','Great for building discourse in open communities'] },

  // ── Tumblr ────────────────────────────────────────────────────────────
  { platform:'tumblr', content_type:'text_post', display_name:'Tumblr Text Post',
    max_chars:500000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['body'],
    optional_fields:['title','tags'],
    best_posting_times:['Saturday 7pm','Sunday 2pm'],
    avg_engagement_rate:3.8,
    tips:['Tumblr thrives on niche communities — find your fandom','Tags are discovery on Tumblr (use all 30)','Long-form essays and rants are native to the platform','Reblog culture = organic reach with proper sourcing'] },
  { platform:'tumblr', content_type:'photo_post', display_name:'Tumblr Photo Post',
    max_chars:10000, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['4:5','16:9','1:1'],
    required_fields:['media_urls'],
    optional_fields:['caption','tags','link'],
    best_posting_times:['Saturday 7pm','Sunday 3pm'],
    avg_engagement_rate:5.1,
    tips:['High-quality aesthetic images are the Tumblr currency','Add source links on all image posts for attribution','Photosets (multiple images) reblog at 3× rate of single images'] },
  { platform:'tumblr', content_type:'video_post', display_name:'Tumblr Video Post',
    max_chars:500, max_images:0, max_video_mb:100, max_duration_seconds:600,
    supported_aspect_ratios:['16:9'],
    required_fields:['media_url'],
    optional_fields:['caption','tags'],
    best_posting_times:['Friday 6pm','Saturday 7pm'],
    avg_engagement_rate:4.4,
    tips:['Autoplay videos start muted — hook visually','Caption under video for context','Max 100MB or 5 min for direct upload'] },
  { platform:'tumblr', content_type:'audio_post', display_name:'Tumblr Audio Post',
    max_chars:500, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['audio_url'],
    optional_fields:['caption','tags','artist','track_name'],
    best_posting_times:['Friday 9pm','Saturday 8pm'],
    avg_engagement_rate:3.2,
    tips:['Spotify track linking is native on Tumblr','Music + quote posts reblog well in music communities'] },
  { platform:'tumblr', content_type:'quote_post', display_name:'Tumblr Quote Post',
    max_chars:1000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['quote','source'],
    optional_fields:['tags'],
    best_posting_times:['Sunday 2pm'],
    avg_engagement_rate:4.9,
    tips:['Inspiring/witty quotes reblog virally on Tumblr','Always attribute the source','Pair with aesthetic image for higher reblog rate'] },
  { platform:'tumblr', content_type:'link_post', display_name:'Tumblr Link Post',
    max_chars:1000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['url','title'],
    optional_fields:['description','tags'],
    best_posting_times:['Saturday 3pm'],
    avg_engagement_rate:2.8,
    tips:['Link posts pull thumbnails from Open Graph tags','Description explains why the link is worth clicking'] },
  { platform:'tumblr', content_type:'chat_post', display_name:'Tumblr Chat/Dialogue Post',
    max_chars:10000, max_images:0, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['dialogue'],
    optional_fields:['title','tags'],
    best_posting_times:['Saturday 8pm'],
    avg_engagement_rate:6.2,
    tips:['Chat posts format dialogue automatically','Fictional conversation posts go viral in fandom communities','Humorous back-and-forth content is highly reblogged'] },

  // ── Quora ─────────────────────────────────────────────────────────────
  { platform:'quora', content_type:'answer', display_name:'Quora Answer',
    max_chars:100000, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9','1:1'],
    required_fields:['question_url','answer_text'],
    optional_fields:['images'],
    best_posting_times:['Tuesday 10am','Thursday 11am'],
    avg_engagement_rate:5.8,
    tips:['Find high-traffic questions with Quora ads tool (free)','Format answers with bullet points for readability','First 2 sentences shown in preview — make them compelling','Personal experience in answers gets 3× more upvotes','Link to relevant resources — Quora allows contextual links'] },
  { platform:'quora', content_type:'space_post', display_name:'Quora Space Post',
    max_chars:50000, max_images:5, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['space_id','body'],
    optional_fields:['title','images'],
    best_posting_times:['Wednesday 10am'],
    avg_engagement_rate:4.2,
    tips:['Spaces are Quora\'s communities — build your own for brand authority','Invite experts to your Space to increase credibility','Space content shown to all followers in their feeds'] },
  { platform:'quora', content_type:'blog_post', display_name:'Quora Blog Post',
    max_chars:100000, max_images:5, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:['16:9'],
    required_fields:['title','body'],
    optional_fields:['tags'],
    best_posting_times:['Tuesday 9am'],
    avg_engagement_rate:3.5,
    tips:['Quora Blogs rank in Google for long-tail keywords','500-1500 words is optimal blog length on Quora','Internal links to your answers boost both pieces'] },

  // ── Stack Overflow ────────────────────────────────────────────────────
  { platform:'stack_overflow', content_type:'question', display_name:'Stack Overflow Question',
    max_chars:30000, max_images:5, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','body','tags'],
    optional_fields:[],
    best_posting_times:['Tuesday 10am','Wednesday 10am'],
    avg_engagement_rate:4.5,
    tips:['Only post genuine technical questions — no marketing','Include minimal reproducible example','Search before posting — most questions already have answers','Use precise technical tags for visibility','Edit the question if no answers after 48h'] },
  { platform:'stack_overflow', content_type:'answer', display_name:'Stack Overflow Answer',
    max_chars:30000, max_images:5, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['question_id','body'],
    optional_fields:[],
    best_posting_times:['Tuesday 10am','Thursday 10am'],
    avg_engagement_rate:5.2,
    tips:['Build reputation through consistent helpful answers','Code blocks with explanation outperform code-only','Answer old questions with better explanations for steady upvote stream'] },
  { platform:'stack_overflow', content_type:'documentation_article', display_name:'Stack Overflow for Teams Article',
    max_chars:50000, max_images:10, max_video_mb:null, max_duration_seconds:null,
    supported_aspect_ratios:[],
    required_fields:['title','body'],
    optional_fields:['tags'],
    best_posting_times:[],
    avg_engagement_rate:0.0,
    tips:['Stack Overflow for Teams is an internal knowledge base product','Job listings and content marketing are separate SO products','Use for internal developer documentation and runbooks'] },
];

interface TenantConfigDef {
  tenant_type: string;
  platform: string;
  posting_frequency: string;
  primary_content_types: string[];
  tone: string;
  top_hashtags: string[];
  best_times: string[];
  kpi_focus: string;
  notes: string;
}

const TENANT_CONFIGS: TenantConfigDef[] = [
  // yoga_studio
  { tenant_type:'yoga_studio', platform:'instagram', posting_frequency:'daily', primary_content_types:['reel','story','image_post'], tone:'inspirational', top_hashtags:['yoga','yogalife','morningyoga','yogainspiration','yogatransformation'], best_times:['Monday 9am','Wednesday 8am','Friday 9am'], kpi_focus:'engagement', notes:'Reels with class previews drive new student inquiries' },
  { tenant_type:'yoga_studio', platform:'facebook', posting_frequency:'3x/week', primary_content_types:['image_post','video_post','event'], tone:'conversational', top_hashtags:['yoga','wellness','yogacommunity'], best_times:['Wednesday 11am','Friday 12pm'], kpi_focus:'reach', notes:'Events + community posts work well for existing student retention' },
  { tenant_type:'yoga_studio', platform:'youtube', posting_frequency:'weekly', primary_content_types:['video_post','short'], tone:'educational', top_hashtags:['yoga','yogaforbeginners','yogatutorial'], best_times:['Saturday 11am','Tuesday 10am'], kpi_focus:'followers', notes:'Tutorial videos and 15-min class recordings perform best' },
  { tenant_type:'yoga_studio', platform:'linkedin', posting_frequency:'weekly', primary_content_types:['text_post','article'], tone:'educational', top_hashtags:['wellness','corporatewellness','mindfulness'], best_times:['Tuesday 8am','Thursday 5pm'], kpi_focus:'conversion', notes:'Corporate wellness angle — reach HR/L&D managers for B2B classes' },
  { tenant_type:'yoga_studio', platform:'tiktok', posting_frequency:'daily', primary_content_types:['video_post','story'], tone:'humorous', top_hashtags:['yoga','yogatok','morningyoga','flexibilitycheck'], best_times:['Thursday 7pm','Friday 5pm'], kpi_focus:'reach', notes:'Before/after flexibility videos and funny yoga fails go viral' },
  { tenant_type:'yoga_studio', platform:'x_twitter', posting_frequency:'3x/week', primary_content_types:['tweet','image_tweet'], tone:'inspirational', top_hashtags:['yoga','mondaymotivation','wellness'], best_times:['Monday 8am','Wednesday 9am'], kpi_focus:'engagement', notes:'Inspirational quotes and wellness tips for morning scroll' },

  // fitness_center
  { tenant_type:'fitness_center', platform:'instagram', posting_frequency:'daily', primary_content_types:['reel','image_post','story'], tone:'motivational', top_hashtags:['fitness','gym','workout','fitlife','fitnessmotivation'], best_times:['Monday 6am','Wednesday 12pm','Friday 5pm'], kpi_focus:'followers', notes:'Transformation photos and workout demo reels drive follows' },
  { tenant_type:'fitness_center', platform:'facebook', posting_frequency:'daily', primary_content_types:['image_post','video_post','poll'], tone:'conversational', top_hashtags:['fitness','gym','workout'], best_times:['Tuesday 12pm','Thursday 5pm'], kpi_focus:'engagement', notes:'Member spotlights and challenge posts build community' },
  { tenant_type:'fitness_center', platform:'youtube', posting_frequency:'2x/week', primary_content_types:['video_post','short'], tone:'educational', top_hashtags:['workout','homeworkout','exercise'], best_times:['Thursday 3pm','Saturday 10am'], kpi_focus:'reach', notes:'Full workout videos with full episodes outperform clip compilations' },
  { tenant_type:'fitness_center', platform:'linkedin', posting_frequency:'weekly', primary_content_types:['text_post','article'], tone:'educational', top_hashtags:['health','corporatefitness','employeewellness'], best_times:['Tuesday 8am'], kpi_focus:'conversion', notes:'Target HR managers for corporate gym memberships' },
  { tenant_type:'fitness_center', platform:'tiktok', posting_frequency:'daily', primary_content_types:['video_post'], tone:'humorous', top_hashtags:['gym','gymmotivation','workout','gains'], best_times:['Tuesday 9am','Friday 5pm'], kpi_focus:'reach', notes:'Gym humor + impressive lifts reach young demographic' },
  { tenant_type:'fitness_center', platform:'x_twitter', posting_frequency:'3x/week', primary_content_types:['tweet','poll'], tone:'motivational', top_hashtags:['fitness','workout','mondaymotivation'], best_times:['Monday 6am','Wednesday 12pm'], kpi_focus:'engagement', notes:'Early morning motivational content gets morning commute traffic' },

  // wellness_brand
  { tenant_type:'wellness_brand', platform:'instagram', posting_frequency:'daily', primary_content_types:['image_post','carousel','reel'], tone:'inspirational', top_hashtags:['wellness','selfcare','mindfulness','mentalhealth','holistichealth'], best_times:['Tuesday 9am','Thursday 10am','Sunday 11am'], kpi_focus:'conversion', notes:'Educational carousels drive saves and product clicks' },
  { tenant_type:'wellness_brand', platform:'facebook', posting_frequency:'3x/week', primary_content_types:['image_post','article','event'], tone:'educational', top_hashtags:['wellness','health','selfcare'], best_times:['Wednesday 10am','Friday 1pm'], kpi_focus:'reach', notes:'Long-form educational posts + webinar events perform well' },
  { tenant_type:'wellness_brand', platform:'youtube', posting_frequency:'weekly', primary_content_types:['video_post'], tone:'educational', top_hashtags:['wellness','health','mindfulness'], best_times:['Tuesday 10am','Saturday 11am'], kpi_focus:'followers', notes:'Deep-dive wellness topics build authority and trust' },
  { tenant_type:'wellness_brand', platform:'linkedin', posting_frequency:'3x/week', primary_content_types:['article','document_post','text_post'], tone:'educational', top_hashtags:['wellness','mentalhealth','workplacewellness'], best_times:['Tuesday 8am','Thursday 8am'], kpi_focus:'conversion', notes:'B2B wellness consulting — target C-suite and HR' },
  { tenant_type:'wellness_brand', platform:'tiktok', posting_frequency:'5x/week', primary_content_types:['video_post','story'], tone:'educational', top_hashtags:['wellness','healthtips','selfcare','mentalhealth'], best_times:['Wednesday 7pm','Friday 5pm'], kpi_focus:'followers', notes:'Quick wellness tips and myth-busting content for Gen Z' },
  { tenant_type:'wellness_brand', platform:'x_twitter', posting_frequency:'daily', primary_content_types:['tweet','thread'], tone:'educational', top_hashtags:['wellness','mentalhealth','selfcare'], best_times:['Tuesday 9am','Thursday 10am'], kpi_focus:'engagement', notes:'Thread series on wellness topics build authority' },

  // b2b_agency
  { tenant_type:'b2b_agency', platform:'linkedin', posting_frequency:'daily', primary_content_types:['text_post','article','document_post'], tone:'educational', top_hashtags:['marketing','digitalmarketing','b2b','growthhacking','contentmarketing'], best_times:['Tuesday 8am','Wednesday 7am','Thursday 8am'], kpi_focus:'conversion', notes:'Case studies and data-driven posts drive inbound leads' },
  { tenant_type:'b2b_agency', platform:'twitter', posting_frequency:'3x/week', primary_content_types:['tweet','thread'], tone:'educational', top_hashtags:['marketing','b2b','digitalmarketing'], best_times:['Tuesday 9am','Thursday 8am'], kpi_focus:'followers', notes:'Marketing insights threads build thought leadership' },
  { tenant_type:'b2b_agency', platform:'youtube', posting_frequency:'weekly', primary_content_types:['video_post'], tone:'educational', top_hashtags:['digitalmarketing','marketing','b2bmarketing'], best_times:['Wednesday 10am'], kpi_focus:'reach', notes:'Strategy breakdowns and case study walkthroughs' },
  { tenant_type:'b2b_agency', platform:'instagram', posting_frequency:'3x/week', primary_content_types:['carousel','image_post'], tone:'educational', top_hashtags:['marketing','digitalmarketing','agencylife'], best_times:['Tuesday 10am','Thursday 10am'], kpi_focus:'engagement', notes:'Stats carousels and behind-scenes agency content' },
  { tenant_type:'b2b_agency', platform:'facebook', posting_frequency:'weekly', primary_content_types:['video_post','article'], tone:'educational', top_hashtags:['marketing','b2b'], best_times:['Wednesday 11am'], kpi_focus:'reach', notes:'Facebook less priority for B2B — repurpose LinkedIn content here' },
  { tenant_type:'b2b_agency', platform:'tiktok', posting_frequency:'3x/week', primary_content_types:['video_post'], tone:'educational', top_hashtags:['marketingtips','b2btiktok','digitalmarketing'], best_times:['Thursday 7pm'], kpi_focus:'followers', notes:'Marketing tips and industry myth-busting for younger marketers' },

  // corporate
  { tenant_type:'corporate', platform:'linkedin', posting_frequency:'daily', primary_content_types:['text_post','article','video_post'], tone:'educational', top_hashtags:['innovation','leadership','futureofwork','corporateculture','sustainability'], best_times:['Tuesday 7am','Wednesday 8am','Thursday 7am'], kpi_focus:'followers', notes:'Thought leadership and culture content for talent attraction' },
  { tenant_type:'corporate', platform:'twitter', posting_frequency:'daily', primary_content_types:['tweet','image_tweet'], tone:'conversational', top_hashtags:['innovation','technology','leadership'], best_times:['Tuesday 9am','Thursday 8am'], kpi_focus:'reach', notes:'Real-time industry commentary and news response' },
  { tenant_type:'corporate', platform:'youtube', posting_frequency:'monthly', primary_content_types:['video_post'], tone:'educational', top_hashtags:['corporate','leadership','innovation'], best_times:['Tuesday 10am'], kpi_focus:'reach', notes:'Annual reports, product launches, executive thought leadership' },
  { tenant_type:'corporate', platform:'instagram', posting_frequency:'3x/week', primary_content_types:['image_post','story','reel'], tone:'inspirational', top_hashtags:['corporateculture','teamwork','innovation','sustainability'], best_times:['Wednesday 12pm','Friday 11am'], kpi_focus:'followers', notes:'Culture, CSR, and employee spotlight content' },
  { tenant_type:'corporate', platform:'facebook', posting_frequency:'3x/week', primary_content_types:['image_post','video_post','event'], tone:'conversational', top_hashtags:['corporate','community','innovation'], best_times:['Wednesday 11am','Friday 1pm'], kpi_focus:'engagement', notes:'Community events, CSR initiatives, product updates' },
  { tenant_type:'corporate', platform:'tiktok', posting_frequency:'3x/week', primary_content_types:['video_post'], tone:'humorous', top_hashtags:['corporatelife','officetok','careertips'], best_times:['Thursday 7pm','Friday 5pm'], kpi_focus:'followers', notes:'Behind-scenes corporate culture content for employer branding' },
];

interface HashtagDef {
  platform: string;
  hashtag: string;
  niche: string;
  avg_reach: number;
  avg_engagement: number;
  post_count_this_week: number;
  trending_score: number;
  competition_level: string;
  recommended_for: string[];
}

function makeHashtags(): HashtagDef[] {
  const tags: HashtagDef[] = [];
  const platforms = ['youtube','facebook','instagram','x_twitter','linkedin','tiktok'];

  const yogaTags = [
    { hashtag:'yoga', avg_reach:850000, avg_engagement:4.2, trending_score:88, competition_level:'high', recommended_for:['reel','image_post','video_post'] },
    { hashtag:'yogalife', avg_reach:420000, avg_engagement:5.1, trending_score:72, competition_level:'high', recommended_for:['image_post','story'] },
    { hashtag:'morningyoga', avg_reach:280000, avg_engagement:6.3, trending_score:68, competition_level:'medium', recommended_for:['reel','short','video_post'] },
    { hashtag:'yogainspiration', avg_reach:195000, avg_engagement:5.8, trending_score:61, competition_level:'medium', recommended_for:['image_post','carousel'] },
    { hashtag:'yogaeveryday', avg_reach:310000, avg_engagement:5.5, trending_score:65, competition_level:'high', recommended_for:['story','reel'] },
    { hashtag:'yogapose', avg_reach:175000, avg_engagement:7.2, trending_score:55, competition_level:'medium', recommended_for:['image_post','carousel'] },
    { hashtag:'yogateacher', avg_reach:95000, avg_engagement:8.1, trending_score:48, competition_level:'low', recommended_for:['text_post','video_post'] },
    { hashtag:'yogaforbeginners', avg_reach:220000, avg_engagement:7.5, trending_score:70, competition_level:'medium', recommended_for:['video_post','reel'] },
    { hashtag:'yogacommunity', avg_reach:110000, avg_engagement:8.4, trending_score:52, competition_level:'low', recommended_for:['image_post','text_post'] },
    { hashtag:'yogaflow', avg_reach:145000, avg_engagement:6.9, trending_score:58, competition_level:'medium', recommended_for:['reel','video_post'] },
    { hashtag:'mindfulyoga', avg_reach:88000, avg_engagement:9.2, trending_score:45, competition_level:'low', recommended_for:['image_post','reel'] },
    { hashtag:'yogatransformation', avg_reach:67000, avg_engagement:10.1, trending_score:42, competition_level:'low', recommended_for:['carousel','image_post'] },
    { hashtag:'yogachallenge', avg_reach:198000, avg_engagement:8.7, trending_score:73, competition_level:'medium', recommended_for:['reel','video_post'] },
    { hashtag:'hathayoga', avg_reach:72000, avg_engagement:7.8, trending_score:40, competition_level:'low', recommended_for:['video_post','article'] },
    { hashtag:'vinyasa', avg_reach:155000, avg_engagement:6.5, trending_score:60, competition_level:'medium', recommended_for:['reel','video_post'] },
    { hashtag:'wellness', avg_reach:950000, avg_engagement:3.8, trending_score:85, competition_level:'high', recommended_for:['image_post','text_post','article'] },
    { hashtag:'selfcare', avg_reach:780000, avg_engagement:4.5, trending_score:81, competition_level:'high', recommended_for:['image_post','reel'] },
    { hashtag:'mindfulness', avg_reach:560000, avg_engagement:4.9, trending_score:79, competition_level:'high', recommended_for:['text_post','image_post'] },
    { hashtag:'holistichealth', avg_reach:210000, avg_engagement:6.1, trending_score:64, competition_level:'medium', recommended_for:['article','text_post','video_post'] },
    { hashtag:'mentalhealth', avg_reach:1100000, avg_engagement:5.2, trending_score:90, competition_level:'high', recommended_for:['text_post','reel','image_post'] },
  ];

  for (const platform of platforms) {
    for (const tag of yogaTags) {
      tags.push({
        platform,
        niche: 'yoga',
        ...tag,
        post_count_this_week: Math.floor(tag.avg_reach / 1000),
      });
    }
  }
  return tags;
}

interface AlertRuleDef {
  platform: string | null;
  alert_type: string;
  metric: string;
  threshold_value: number;
  comparison: string;
  window_minutes: number;
  severity: string;
  notification_channels: string[];
}

function makeAlertRules(): AlertRuleDef[] {
  const platforms = ['youtube','facebook','instagram','x_twitter','linkedin','tiktok'];
  const rules: AlertRuleDef[] = [];

  for (const platform of platforms) {
    rules.push(
      { platform, alert_type:'viral_spike', metric:'impressions', threshold_value:10000, comparison:'gt', window_minutes:60, severity:'info', notification_channels:['email'] },
      { platform, alert_type:'negative_surge', metric:'negative_comments', threshold_value:20, comparison:'gt', window_minutes:30, severity:'high', notification_channels:['email','sms'] },
      { platform, alert_type:'post_failed', metric:'post_status', threshold_value:1, comparison:'gt', window_minutes:5, severity:'critical', notification_channels:['email','sms','push'] },
      { platform, alert_type:'engagement_drop', metric:'engagement_rate', threshold_value:30, comparison:'pct_change', window_minutes:10080, severity:'medium', notification_channels:['email'] },
      { platform, alert_type:'follower_loss', metric:'follower_delta', threshold_value:-100, comparison:'lt', window_minutes:1440, severity:'high', notification_channels:['email'] },
    );
  }
  return rules;
}

export async function POST(req: NextRequest) {

  const denied = await requireAdmin(req);
  if (denied) return denied;
  await ensureSocialIntelligenceSchema();

  let configsInserted = 0;
  let tenantsInserted = 0;
  let hashtagsInserted = 0;
  let alertsInserted = 0;

  // Seed content type configs
  for (const cfg of CONTENT_TYPE_CONFIGS) {
    const r = await query(
      `INSERT INTO social_content_type_config
         (platform, content_type, display_name, max_chars, max_images, max_video_mb, max_duration_seconds,
          supported_aspect_ratios, required_fields, optional_fields, best_posting_times, avg_engagement_rate, tips)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
       ON CONFLICT (platform, content_type) DO NOTHING`,
      [cfg.platform, cfg.content_type, cfg.display_name, cfg.max_chars, cfg.max_images, cfg.max_video_mb, cfg.max_duration_seconds,
       cfg.supported_aspect_ratios, cfg.required_fields, cfg.optional_fields, cfg.best_posting_times, cfg.avg_engagement_rate, cfg.tips],
    );
    if ((r.rowCount ?? 0) > 0) configsInserted++;
  }

  // Seed tenant configs
  for (const tc of TENANT_CONFIGS) {
    const r = await query(
      `INSERT INTO social_tenant_config
         (tenant_type, platform, posting_frequency, primary_content_types, tone, top_hashtags, best_times, kpi_focus, notes)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT (tenant_type, platform) DO NOTHING`,
      [tc.tenant_type, tc.platform, tc.posting_frequency, tc.primary_content_types, tc.tone, tc.top_hashtags, tc.best_times, tc.kpi_focus, tc.notes],
    );
    if ((r.rowCount ?? 0) > 0) tenantsInserted++;
  }

  // Seed hashtags
  for (const ht of makeHashtags()) {
    const r = await query(
      `INSERT INTO social_hashtag_performance
         (platform, hashtag, niche, avg_reach, avg_engagement, post_count_this_week, trending_score, competition_level, recommended_for)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT (platform, hashtag) DO NOTHING`,
      [ht.platform, ht.hashtag, ht.niche, ht.avg_reach, ht.avg_engagement, ht.post_count_this_week, ht.trending_score, ht.competition_level, ht.recommended_for],
    );
    if ((r.rowCount ?? 0) > 0) hashtagsInserted++;
  }

  // Seed alert rules
  for (const ar of makeAlertRules()) {
    const r = await query(
      `INSERT INTO social_alert_rule
         (platform, alert_type, metric, threshold_value, comparison, window_minutes, severity, notification_channels)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
      [ar.platform, ar.alert_type, ar.metric, ar.threshold_value, ar.comparison, ar.window_minutes, ar.severity, ar.notification_channels],
    );
    if ((r.rowCount ?? 0) > 0) alertsInserted++;
  }

  return Response.json({
    ok: true,
    configsInserted,
    tenantsInserted,
    hashtagsInserted,
    alertsInserted,
  });
}
