#!/usr/bin/env python3
"""prompt_tracker.py — Per §21 prompt tracking system.

Dual write: SQLite (data/prompts.db) + markdown backup (data/prompt-history.md).
Crash log: data/crash-recovery.md.

Usage:
    python scripts/prompt_tracker.py --save "prompt text" [--source <source>] [--category <cat>]
    python scripts/prompt_tracker.py --list [--limit 20]
    python scripts/prompt_tracker.py --search "term"
    python scripts/prompt_tracker.py --export <out.csv>
    python scripts/prompt_tracker.py --stats
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import os
import sqlite3
import sys
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA_DIR = REPO / "data"
DB_PATH = DATA_DIR / "prompts.db"
MD_PATH = DATA_DIR / "prompt-history.md"
CRASH_LOG = DATA_DIR / "crash-recovery.md"

SCHEMA = """
CREATE TABLE IF NOT EXISTS prompts (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    session_id TEXT,
    prompt_text TEXT NOT NULL,
    category TEXT,
    source TEXT,
    status TEXT DEFAULT 'received'
);
CREATE INDEX IF NOT EXISTS idx_prompts_ts ON prompts(timestamp);
CREATE INDEX IF NOT EXISTS idx_prompts_session ON prompts(session_id);
CREATE INDEX IF NOT EXISTS idx_prompts_category ON prompts(category);

CREATE TABLE IF NOT EXISTS crash_log (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    event_type TEXT NOT NULL,
    details TEXT,
    prompt_id TEXT,
    recovery_status TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    total_prompts INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active'
);

PRAGMA journal_mode=WAL;
PRAGMA busy_timeout=5000;
"""


def _ensure_dirs() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)


def _db() -> sqlite3.Connection:
    _ensure_dirs()
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA)
    return conn


def _append_md(row: dict) -> None:
    """Markdown backup write — survives DB corruption."""
    if not MD_PATH.exists():
        MD_PATH.write_text("# Prompt History\n\nAuto-generated by prompt_tracker.py per §21.\n\n")
    line = (
        f"## {row['timestamp']} · {row['id'][:8]}\n"
        f"- **Source**: {row.get('source') or '-'}\n"
        f"- **Category**: {row.get('category') or '-'}\n"
        f"- **Session**: {row.get('session_id') or '-'}\n"
        f"- **Prompt**:\n\n  > {row['prompt_text'].replace(chr(10), chr(10)+'  > ')}\n\n"
    )
    with MD_PATH.open("a", encoding="utf-8") as f:
        f.write(line)


def save(prompt_text: str, source: str | None = None, category: str | None = None,
         session_id: str | None = None) -> str:
    """Save a prompt. Returns the prompt ID."""
    row = {
        "id": str(uuid.uuid4()),
        "timestamp": dt.datetime.now(dt.timezone.utc).isoformat(),
        "session_id": session_id or os.environ.get("CLAUDE_SESSION_ID", ""),
        "prompt_text": prompt_text,
        "category": category,
        "source": source,
        "status": "received",
    }
    # Dual write: SQLite + markdown
    try:
        conn = _db()
        conn.execute(
            "INSERT INTO prompts (id, timestamp, session_id, prompt_text, category, source, status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (row["id"], row["timestamp"], row["session_id"], row["prompt_text"],
             row["category"], row["source"], row["status"]),
        )
        conn.commit()
        conn.close()
    except sqlite3.Error as e:
        # Log crash; markdown write still proceeds
        _log_crash("sqlite_write_failed", str(e), prompt_id=row["id"])
    _append_md(row)
    return row["id"]


def _log_crash(event_type: str, details: str, prompt_id: str | None = None) -> None:
    _ensure_dirs()
    if not CRASH_LOG.exists():
        CRASH_LOG.write_text("# Crash Recovery Log\n\nAuto-generated per §21.\n\n")
    ts = dt.datetime.now(dt.timezone.utc).isoformat()
    line = f"- [{ts}] **{event_type}** · prompt_id={prompt_id or '-'} · {details}\n"
    with CRASH_LOG.open("a", encoding="utf-8") as f:
        f.write(line)


def list_prompts(limit: int = 20) -> list[dict]:
    conn = _db()
    cur = conn.execute(
        "SELECT id, timestamp, session_id, category, source, "
        "substr(prompt_text, 1, 100) AS preview "
        "FROM prompts ORDER BY timestamp DESC LIMIT ?", (limit,)
    )
    rows = [dict(zip([c[0] for c in cur.description], r)) for r in cur.fetchall()]
    conn.close()
    return rows


def search(term: str) -> list[dict]:
    conn = _db()
    cur = conn.execute(
        "SELECT id, timestamp, category, source, prompt_text "
        "FROM prompts WHERE prompt_text LIKE ? ORDER BY timestamp DESC",
        (f"%{term}%",),
    )
    rows = [dict(zip([c[0] for c in cur.description], r)) for r in cur.fetchall()]
    conn.close()
    return rows


def export_csv(out_path: str) -> int:
    conn = _db()
    cur = conn.execute("SELECT * FROM prompts ORDER BY timestamp DESC")
    rows = cur.fetchall()
    cols = [c[0] for c in cur.description]
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(cols)
        w.writerows(rows)
    conn.close()
    return len(rows)


def stats() -> dict:
    conn = _db()
    cur = conn.execute("SELECT COUNT(*), MIN(timestamp), MAX(timestamp) FROM prompts")
    total, first, last = cur.fetchone()
    cur = conn.execute(
        "SELECT category, COUNT(*) FROM prompts WHERE category IS NOT NULL GROUP BY category ORDER BY 2 DESC"
    )
    by_cat = dict(cur.fetchall())
    cur = conn.execute(
        "SELECT source, COUNT(*) FROM prompts WHERE source IS NOT NULL GROUP BY source ORDER BY 2 DESC"
    )
    by_src = dict(cur.fetchall())
    conn.close()
    return {"total": total, "first": first, "last": last,
            "by_category": by_cat, "by_source": by_src,
            "db_path": str(DB_PATH), "md_path": str(MD_PATH)}


def main() -> int:
    p = argparse.ArgumentParser(description="§21 prompt tracker · SQLite + markdown dual write")
    p.add_argument("--save", metavar="TEXT", help="Save a prompt")
    p.add_argument("--source", help="Source label (e.g. claude · operator · cron)")
    p.add_argument("--category", help="Category tag (e.g. policy · fix · audit)")
    p.add_argument("--session", help="Session ID (default: CLAUDE_SESSION_ID env)")
    p.add_argument("--list", action="store_true", help="List recent prompts")
    p.add_argument("--limit", type=int, default=20, help="List/limit")
    p.add_argument("--search", metavar="TERM", help="Search prompts")
    p.add_argument("--export", metavar="OUT", help="Export to CSV")
    p.add_argument("--stats", action="store_true", help="Show stats")
    args = p.parse_args()

    if args.save:
        pid = save(args.save, source=args.source, category=args.category, session_id=args.session)
        print(f"saved: {pid}")
        return 0
    if args.list:
        for r in list_prompts(args.limit):
            print(f"{r['timestamp']} · {r['id'][:8]} · [{r['category'] or '-'}] {r['preview']}")
        return 0
    if args.search:
        for r in search(args.search):
            print(f"{r['timestamp']} · [{r['category'] or '-'}] {r['prompt_text'][:200]}")
        return 0
    if args.export:
        n = export_csv(args.export)
        print(f"exported {n} rows to {args.export}")
        return 0
    if args.stats:
        print(json.dumps(stats(), indent=2))
        return 0
    p.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
