'use client';
import Link from 'next/link'; import {experienceConfig as cfg} from '@/config/experience.config';
const gaps=[
 ['Critical','Authentication/TLS before public exposure','Do not expose admin services until SSO, TLS, secret rotation and network policy are verified.'],
 ['Critical','Commerce catalogue is fragmented','Static class data, .NET services and PostgreSQL products are not yet one transactional catalogue.'],
 ['High','No public trainer directory/detail journey','Admin teacher detail exists; customer discovery, comparison and trainer booking need a public model.'],
 ['High','No screenshot accessibility regression','112 routes have HTTP evidence, but axe/Playwright visual and keyboard journeys are absent.'],
 ['High','23 integrations are folders, not integrations','They need credentials, lifecycle ownership, health checks, data contracts and acceptance tests.'],
 ['Medium','Graph/RDF is not justified yet','PostgreSQL foreign keys already model 317 relations; add RDF only for a defined semantic-query use case.'],
 ['Medium','Vector coverage is selective','Marketing/content RAG exists; blindly embedding payments, secrets and operational rows would be unsafe and expensive.'],
] as const;
const c4=[['Context','Customers, trainers, tenant admins and service providers use SohamYoga; external social/payment/content systems sit outside the trust boundary.'],['Containers','Next.js web/PWA · .NET API · PostgreSQL · SQLite job ledger · Ollama · OpenClaw · Paperclip · scheduled workers.'],['Components','Identity, catalogue, booking, commerce, marketing, social, AI director, assurance, observability and notification modules.'],['Code','TypeScript domain/API/UI · C# controllers/services/EF · Python agents/router/worker · shell/systemd automation · SQL migrations/triggers.']];
export default function Page(){return <div className="mx-auto max-w-7xl space-y-6 p-6"><header className="border-l-4 border-primary-600 pl-4"><h1 className="text-2xl font-bold">Architecture & Process Centre</h1><p className="text-sm text-gray-500">Training, C4 views, process flows, standards and candid platform gaps.</p></header>
<section className="grid gap-3 md:grid-cols-4">{c4.map(([k,v])=><article key={k} className="app-card" data-category="platform"><h2 className="font-bold">C4 · {k}</h2><p className="mt-2 text-sm text-gray-600">{v}</p></article>)}</section>
<section><h2 className="mb-3 text-xl font-bold">Process training</h2><div className="space-y-4">{cfg.processes.map(p=><article key={p.key} className="app-card" data-category="operations"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{p.name}</h3><span className="text-xs text-gray-500">Actors: {p.actors.join(' · ')}</span></div><div className="mt-3 grid gap-2 md:grid-cols-3 lg:grid-cols-5">{p.steps.map((s,i)=><div key={s} className="rounded-lg border bg-white p-3 text-sm"><b className="mr-2 text-primary-700">{i+1}</b>{s}</div>)}</div></article>)}</div></section>
<section><h2 className="mb-3 text-xl font-bold">Brutal gap assessment</h2><div className="space-y-2">{gaps.map(([risk,title,detail])=><article key={title} className="rounded-xl border bg-white p-4"><div className="flex gap-3"><span className={`h-fit rounded px-2 py-1 text-xs font-bold ${risk==='Critical'?'bg-red-100 text-red-800':risk==='High'?'bg-orange-100 text-orange-800':'bg-blue-100 text-blue-800'}`}>{risk} · {risk==='Critical'?'×':risk==='High'?'!':'ℹ'}</span><div><h3 className="font-semibold">{title}</h3><p className="text-sm text-gray-600">{detail}</p></div></div></article>)}</div></section>
<section className="grid gap-3 md:grid-cols-3"><Link href="/admin/module-assurance" className="app-card" data-category="education"><b>Module Assurance</b><p className="text-sm">Features, routes, integrations, models and tests.</p></Link><Link href="/admin/operations-history" className="app-card" data-category="operations"><b>Operations History</b><p className="text-sm">Errors, jobs, traces and circuits.</p></Link><Link href="/admin/schema-catalog" className="app-card" data-category="commerce"><b>Schema & Relationships</b><p className="text-sm">Tables, primary keys and references.</p></Link></section></div>}
