// Platform-specific tab configuration for all 36 social/content platforms.
// Each entry maps a platform key to its platform-specific feature tabs.
// Sourced from sohamyoga-frontend/src/lib/platform-tab-config.ts and extended.
// Pure data — no React, no Next.js.

import type { PlatformTab, PlatformHubMeta } from './types';
import { PLATFORM_REGISTRY } from './platform-registry';

export const PLATFORM_SPECIFIC_TABS: Record<string, PlatformTab[]> = {
  youtube: [
    { id: 'videos', label: '🎬 Videos', description: 'All uploaded videos with status, views, CTR, watch time' },
    { id: 'shorts', label: '⚡ Shorts', description: 'Short-form vertical videos under 60 seconds' },
    { id: 'live', label: '🔴 Live', description: 'Scheduled and past live streams' },
    { id: 'playlists', label: '📋 Playlists', description: 'Playlist management and performance' },
    { id: 'community', label: '💬 Community', description: 'Community posts, polls, Q&A' },
    { id: 'analytics', label: '📊 Analytics', description: 'Watch time, impressions, CTR, subscriber delta, revenue' },
    { id: 'comments', label: '🗨 Comments', description: 'Comment moderation, pinned comments, top comments' },
    { id: 'chapters', label: '📑 Chapters', description: 'Video chapter timestamps and descriptions' },
  ],
  facebook: [
    { id: 'posts', label: '📝 Posts', description: 'All page posts — text, image, video, links' },
    { id: 'stories', label: '⭕ Stories', description: '24-hour stories with view counts' },
    { id: 'reels', label: '🎭 Reels', description: 'Short video reels and their performance' },
    { id: 'groups', label: '👥 Groups', description: 'Group posts and member engagement' },
    { id: 'events', label: '📅 Events', description: 'Events created, RSVP counts, reach' },
    { id: 'analytics', label: '📊 Analytics', description: 'Page reach, engagement rate, follower growth, top posts' },
    { id: 'ads', label: '🎯 Ads', description: 'Facebook ad campaigns linked to this page' },
    { id: 'inbox', label: '📥 Inbox', description: 'Page messages and response rate' },
  ],
  instagram: [
    { id: 'feed', label: '🖼 Feed', description: 'Photo and video feed posts with engagement metrics' },
    { id: 'reels', label: '🎬 Reels', description: 'Reels with plays, shares, reach' },
    { id: 'stories', label: '⭕ Stories', description: 'Stories with views, taps forward/back, exits' },
    { id: 'carousel', label: '🎠 Carousel', description: 'Multi-image carousel posts' },
    { id: 'shopping', label: '🛍 Shopping', description: 'Product tags and shopping post performance' },
    { id: 'analytics', label: '📊 Analytics', description: 'Reach, profile visits, website clicks, follower demographics' },
    { id: 'hashtags', label: '#️⃣ Hashtags', description: 'Hashtag performance and discovery reach' },
    { id: 'collab', label: '🤝 Collab', description: 'Collaboration posts with other creators' },
  ],
  x_twitter: [
    { id: 'tweets', label: '🐦 Tweets', description: 'All tweets with impressions, engagements, link clicks' },
    { id: 'threads', label: '🧵 Threads', description: 'Multi-tweet threads and their reach' },
    { id: 'spaces', label: '🎙 Spaces', description: 'Twitter Spaces sessions — scheduled and past' },
    { id: 'polls', label: '📊 Polls', description: 'Polls with vote counts and engagement' },
    { id: 'lists', label: '📋 Lists', description: 'Twitter lists owned and subscribed' },
    { id: 'analytics', label: '📈 Analytics', description: 'Impressions, profile visits, mentions, retweets, followers' },
    { id: 'trending', label: '🔥 Trending', description: 'Trending hashtags and topics relevant to niche' },
    { id: 'dm', label: '✉️ DMs', description: 'Direct message campaigns (paid tier)' },
  ],
  linkedin: [
    { id: 'posts', label: '📝 Posts', description: 'Company and personal page posts' },
    { id: 'articles', label: '📰 Articles', description: 'Long-form LinkedIn articles' },
    { id: 'documents', label: '📄 Documents', description: 'PDF/carousel document posts' },
    { id: 'events', label: '📅 Events', description: 'LinkedIn Events and webinars' },
    { id: 'newsletter', label: '📬 Newsletter', description: 'LinkedIn Newsletter subscribers and issues' },
    { id: 'analytics', label: '📊 Analytics', description: 'Impressions, clicks, followers, engagement by role/seniority' },
    { id: 'company', label: '🏢 Company Page', description: 'Company page updates, follower stats, life tab' },
    { id: 'lead-gen', label: '🎯 Lead Gen', description: 'LinkedIn Lead Gen Forms performance' },
  ],
  tiktok: [
    { id: 'videos', label: '🎵 Videos', description: 'All TikTok videos with plays, completions, shares' },
    { id: 'live', label: '🔴 Live', description: 'TikTok LIVE sessions and peak viewer counts' },
    { id: 'sounds', label: '🎶 Sounds', description: 'Original sounds created and used by others' },
    { id: 'trends', label: '🔥 Trends', description: 'Trending hashtags and sounds in your niche' },
    { id: 'analytics', label: '📊 Analytics', description: 'Video views, profile visits, follower count, completion rate' },
    { id: 'ads', label: '🎯 Ads', description: 'TikTok For Business ad campaigns' },
    { id: 'duets', label: '🎭 Duets', description: 'Duets and stitches — collaborative content' },
    { id: 'effects', label: '✨ Effects', description: 'Custom effects and filters created' },
  ],
  whatsapp_business: [
    { id: 'messages', label: '💬 Messages', description: 'Sent/received messages, delivery and read rates' },
    { id: 'templates', label: '📋 Templates', description: 'Approved message templates for proactive outreach' },
    { id: 'broadcasts', label: '📡 Broadcasts', description: 'Broadcast lists and campaign message status' },
    { id: 'contacts', label: '👥 Contacts', description: 'Opted-in contacts, segments, labels' },
    { id: 'chatbot', label: '🤖 Chatbot', description: 'Auto-reply flows and bot conversation logs' },
    { id: 'catalog', label: '🛍 Catalog', description: 'Product catalog shared via WhatsApp' },
    { id: 'analytics', label: '📊 Analytics', description: 'Message sent, delivered, read, replied rates' },
    { id: 'compliance', label: '⚖️ Compliance', description: 'Opt-in records, 24h window tracking, policy compliance' },
  ],
  pinterest: [
    { id: 'pins', label: '📌 Pins', description: 'All pins with impressions, saves, outbound clicks' },
    { id: 'boards', label: '📋 Boards', description: 'Board performance and follower counts' },
    { id: 'idea-pins', label: '💡 Idea Pins', description: 'Multi-page idea pins (formerly Story Pins)' },
    { id: 'shopping', label: '🛍 Shopping', description: 'Product catalog pins and shopping performance' },
    { id: 'analytics', label: '📊 Analytics', description: 'Impressions, saves, outbound clicks, audience insights' },
    { id: 'trends', label: '🔥 Trends', description: 'Pinterest Trends for your niche and season' },
    { id: 'ads', label: '🎯 Promoted Pins', description: 'Pinterest ad campaigns and promoted pins' },
    { id: 'rich-pins', label: '✨ Rich Pins', description: 'Article, recipe, app, and product rich pins' },
  ],
  reddit: [
    { id: 'posts', label: '📝 Posts', description: 'Submitted posts across subreddits — upvotes, comments, awards' },
    { id: 'comments', label: '💬 Comments', description: 'Comment engagement and karma earned' },
    { id: 'subreddits', label: '🏘 Subreddits', description: 'Target subreddits, rules, moderation status' },
    { id: 'communities', label: '👥 Communities', description: 'Owned/moderated communities and member counts' },
    { id: 'analytics', label: '📊 Analytics', description: 'Post reach, upvote ratio, comment sentiment, karma trend' },
    { id: 'ads', label: '🎯 Reddit Ads', description: 'Reddit Promote campaigns and ad performance' },
    { id: 'awards', label: '🏆 Awards', description: 'Awards received and karma milestones' },
    { id: 'flair', label: '🏷 Flair', description: 'Post flair strategy per subreddit' },
  ],
  snapchat: [
    { id: 'stories', label: '⭕ Stories', description: 'Snap stories with views, screenshots, swipe-ups' },
    { id: 'spotlight', label: '🔦 Spotlight', description: 'Spotlight videos and viral reach' },
    { id: 'lenses', label: '🎭 Lenses', description: 'AR lens usage and community engagement' },
    { id: 'filters', label: '🖼 Filters', description: 'Geofilter performance and usage counts' },
    { id: 'ads', label: '🎯 Snap Ads', description: 'Snap Ad campaigns — video ads, collection ads' },
    { id: 'analytics', label: '📊 Analytics', description: 'Story views, swipe-ups, completion rate, follower growth' },
    { id: 'map', label: '🗺 Snap Map', description: 'Location-based Snap Map presence' },
    { id: 'score', label: '⭐ Score', description: 'Account score and engagement health' },
  ],
  discord: [
    { id: 'channels', label: '📢 Channels', description: 'Text, voice, and announcement channel activity' },
    { id: 'messages', label: '💬 Messages', description: 'Posted messages, reactions, threads created' },
    { id: 'bots', label: '🤖 Bots', description: 'Bot commands, automations, and webhook integrations' },
    { id: 'events', label: '📅 Events', description: 'Guild events, RSVP counts, attendance' },
    { id: 'members', label: '👥 Members', description: 'Member count trend, roles, join/leave rate' },
    { id: 'analytics', label: '📊 Analytics', description: 'Message volume, peak hours, top contributors, retention' },
    { id: 'forums', label: '🗂 Forums', description: 'Forum channel threads and engagement' },
    { id: 'stage', label: '🎙 Stage', description: 'Stage channel events and speaker roster' },
  ],
  twitch: [
    { id: 'streams', label: '🎮 Streams', description: 'Past streams with peak viewers, avg viewers, hours watched' },
    { id: 'clips', label: '✂️ Clips', description: 'Top clips — views, shares, cross-platform reposts' },
    { id: 'schedule', label: '📅 Schedule', description: 'Stream schedule and upcoming sessions' },
    { id: 'subscribers', label: '⭐ Subscribers', description: 'Sub count, Tier 1/2/3 breakdown, churn rate' },
    { id: 'channel-points', label: '💎 Channel Points', description: 'Custom rewards, redemption rate, viewer engagement' },
    { id: 'analytics', label: '📊 Analytics', description: 'Concurrent viewers, follower growth, revenue, hype train events' },
    { id: 'drops', label: '🎁 Drops', description: 'Drop campaigns and reward distribution' },
    { id: 'raids', label: '⚡ Raids', description: 'Raid history — incoming and outgoing' },
  ],
  medium: [
    { id: 'articles', label: '📰 Articles', description: 'Published articles — views, reads, claps, highlights' },
    { id: 'series', label: '📚 Series', description: 'Article series groupings' },
    { id: 'publications', label: '📖 Publications', description: 'Publications you write for — followers, traffic' },
    { id: 'analytics', label: '📊 Analytics', description: 'Views, reads, read ratio, claps, referrers' },
    { id: 'responses', label: '💬 Responses', description: 'Comment responses and engagement' },
    { id: 'drafts', label: '📝 Drafts', description: 'Draft articles in queue' },
    { id: 'earnings', label: '💰 Partner Program', description: 'Medium Partner Program earnings and reading time' },
    { id: 'seo', label: '🔍 SEO', description: 'Google search referrals and top keywords' },
  ],
  substack: [
    { id: 'posts', label: '📰 Posts', description: 'Newsletter issues — open rate, clicks, new subscribers' },
    { id: 'notes', label: '📝 Notes', description: 'Short-form Substack Notes posts' },
    { id: 'subscribers', label: '👥 Subscribers', description: 'Free vs paid subscriber counts, growth rate, churn' },
    { id: 'podcasts', label: '🎙 Podcast', description: 'Audio episodes and listen counts' },
    { id: 'analytics', label: '📊 Analytics', description: 'Open rates, click rates, top referrers, paid conversion' },
    { id: 'revenue', label: '💰 Revenue', description: 'Monthly recurring revenue, subscription tiers, churn' },
    { id: 'comments', label: '💬 Comments', description: 'Subscriber comments and discussion threads' },
    { id: 'referrals', label: '🔗 Referrals', description: 'Subscriber referral program performance' },
  ],
  github: [
    { id: 'repos', label: '📁 Repositories', description: 'Stars, forks, watchers, open issues per repo' },
    { id: 'releases', label: '🚀 Releases', description: 'Release notes, download counts, changelog' },
    { id: 'discussions', label: '💬 Discussions', description: 'Community discussions and Q&A threads' },
    { id: 'gists', label: '📋 Gists', description: 'Published gists and their stars/views' },
    { id: 'analytics', label: '📊 Analytics', description: 'Traffic — views, unique visitors, clones, referrers' },
    { id: 'sponsors', label: '💖 Sponsors', description: 'GitHub Sponsors tiers and sponsor count' },
    { id: 'actions', label: '⚙️ Actions', description: 'Workflow runs and CI/CD pipeline status' },
    { id: 'pages', label: '🌐 Pages', description: 'GitHub Pages site analytics' },
  ],
  gitlab: [
    { id: 'repos', label: '📁 Projects', description: 'GitLab projects with stars, forks, issues' },
    { id: 'releases', label: '🚀 Releases', description: 'Release notes and milestone tracking' },
    { id: 'snippets', label: '📋 Snippets', description: 'Code snippets and their views' },
    { id: 'wiki', label: '📖 Wiki', description: 'Project wiki pages' },
    { id: 'analytics', label: '📊 Analytics', description: 'Pipeline stats, code coverage, deployment frequency' },
    { id: 'merge-requests', label: '🔀 Merge Requests', description: 'Open MRs and review engagement' },
    { id: 'packages', label: '📦 Packages', description: 'Package registry downloads' },
    { id: 'registry', label: '🐳 Registry', description: 'Container registry image pulls' },
  ],
  google_business: [
    { id: 'posts', label: '📝 Posts', description: 'Standard, event, offer, and product posts' },
    { id: 'reviews', label: '⭐ Reviews', description: 'Customer reviews — rating, respond, flag inappropriate' },
    { id: 'photos', label: '🖼 Photos', description: 'Business photos — views, impressions per photo' },
    { id: 'products', label: '🛍 Products', description: 'Product catalog listings' },
    { id: 'q-and-a', label: '❓ Q&A', description: 'Customer questions and business answers' },
    { id: 'analytics', label: '📊 Analytics', description: 'Search views, map views, directions, calls, website clicks' },
    { id: 'locations', label: '📍 Locations', description: 'Multi-location management and per-location stats' },
    { id: 'messaging', label: '💬 Messaging', description: 'Customer messages via Business Profile chat' },
  ],
  trustpilot: [
    { id: 'reviews', label: '⭐ Reviews', description: 'All reviews — rating, date, content, response status' },
    { id: 'invitations', label: '📧 Invitations', description: 'Review invitation campaigns sent to customers' },
    { id: 'responses', label: '💬 Responses', description: 'Pending and completed review responses' },
    { id: 'analytics', label: '📊 Analytics', description: 'TrustScore trend, rating distribution, response rate, NPS' },
    { id: 'integrations', label: '🔌 Integrations', description: 'Trustpilot widget embed, API, and CRM sync' },
    { id: 'categories', label: '📑 Categories', description: 'Review categories and tagged themes' },
    { id: 'flagged', label: '🚩 Flagged', description: 'Flagged/reported reviews under investigation' },
    { id: 'widgets', label: '🖼 Widgets', description: 'TrustBox widget configurations and placements' },
  ],
  vimeo: [
    { id: 'videos', label: '🎬 Videos', description: 'All videos — plays, likes, comments, downloads' },
    { id: 'showcases', label: '🗂 Showcases', description: 'Video portfolios/showcases and their traffic' },
    { id: 'analytics', label: '📊 Analytics', description: 'Plays, finishes, finish rate, device breakdown, geography' },
    { id: 'privacy', label: '🔒 Privacy', description: 'Privacy settings per video — password, domain restriction' },
    { id: 'embed', label: '📤 Embed', description: 'Embed codes and player customization' },
    { id: 'review', label: '✅ Review', description: 'Review pages for client approvals' },
    { id: 'live', label: '🔴 Live', description: 'Vimeo Live streaming — past and upcoming' },
    { id: 'chapters', label: '📑 Chapters', description: 'Video chapters and table of contents' },
  ],
  soundcloud: [
    { id: 'tracks', label: '🎵 Tracks', description: 'Uploaded tracks — plays, likes, reposts, comments' },
    { id: 'playlists', label: '📋 Playlists', description: 'Curated playlists and sets' },
    { id: 'analytics', label: '📊 Analytics', description: 'Play counts, follower growth, geography, peak hours' },
    { id: 'reposts', label: '🔁 Reposts', description: 'Tracks reposted by followers' },
    { id: 'comments', label: '💬 Comments', description: 'Waveform comments and general comments' },
    { id: 'spotlight', label: '🔦 Spotlight', description: 'Spotlighted tracks on profile' },
    { id: 'followers', label: '👥 Followers', description: 'Follower growth and top followers' },
    { id: 'next-pro', label: '⭐ Next Pro', description: 'Pro stats — deep analytics and monetization' },
  ],
  spotify: [
    { id: 'episodes', label: '🎙 Episodes', description: 'Podcast episodes — streams, listeners, followers' },
    { id: 'shows', label: '📻 Shows', description: 'Show overview — total streams, unique listeners' },
    { id: 'analytics', label: '📊 Analytics', description: 'Streams, listeners, followers, platform breakdown, geography' },
    { id: 'audience', label: '👥 Audience', description: 'Age, gender, location breakdown of listeners' },
    { id: 'ads', label: '🎯 Spotify Ads', description: 'Spotify Ad Studio campaigns and audio ad performance' },
    { id: 'distribution', label: '📡 Distribution', description: 'Distribution to Apple Podcasts, Google, Amazon via RSS' },
    { id: 'chapters', label: '📑 Chapters', description: 'Episode chapter markers for navigation' },
    { id: 'transcripts', label: '📝 Transcripts', description: 'Auto-generated transcripts for accessibility and SEO' },
  ],
  apple_podcasts: [
    { id: 'episodes', label: '🎙 Episodes', description: 'Episode list with plays and unique devices' },
    { id: 'shows', label: '📻 Shows', description: 'Show metadata — title, description, artwork, category' },
    { id: 'analytics', label: '📊 Analytics', description: 'Listeners, plays, follows, average consumption' },
    { id: 'reviews', label: '⭐ Reviews', description: 'User ratings and written reviews by country' },
    { id: 'distribution', label: '📡 RSS Feed', description: 'RSS feed URL and submission status' },
    { id: 'chapters', label: '📑 Chapters', description: 'Chapter markers and show notes' },
    { id: 'search', label: '🔍 Search', description: 'Search ranking position for keywords' },
    { id: 'subscriptions', label: '💰 Subscriptions', description: 'Apple Podcasts Subscriptions premium tier' },
  ],
  patreon: [
    { id: 'posts', label: '📝 Posts', description: 'Creator posts — public and patron-only, likes, comments' },
    { id: 'patrons', label: '💖 Patrons', description: 'Patron count, tier breakdown, churn rate, lifetime value' },
    { id: 'tiers', label: '🏆 Tiers', description: 'Membership tier management — benefits, price, patron count' },
    { id: 'revenue', label: '💰 Revenue', description: 'Monthly revenue, fees, net payout, growth trend' },
    { id: 'analytics', label: '📊 Analytics', description: 'Patron acquisition, churn, upgrade/downgrade, LTV' },
    { id: 'benefits', label: '🎁 Benefits', description: 'Deliverable benefits tracking — fulfilled vs outstanding' },
    { id: 'polls', label: '📊 Polls', description: 'Patron polls and voting results' },
    { id: 'messages', label: '✉️ Messages', description: 'Direct messages to patron segments' },
  ],
  mastodon: [
    { id: 'toots', label: '📣 Toots', description: 'Posts (toots) — boosts, favourites, replies' },
    { id: 'following', label: '👥 Following', description: 'Accounts followed and follower graph' },
    { id: 'local', label: '🏘 Local', description: 'Instance local timeline activity' },
    { id: 'federated', label: '🌐 Federated', description: 'Federated timeline reach across instances' },
    { id: 'analytics', label: '📊 Analytics', description: 'Followers, reblogs, favourites, mentions' },
    { id: 'lists', label: '📋 Lists', description: 'Curated follow lists for content filtering' },
    { id: 'bookmarks', label: '🔖 Bookmarks', description: 'Saved toots for reference' },
    { id: 'instances', label: '⚙️ Instance', description: 'Connected Mastodon instance and admin tools' },
  ],
  bluesky: [
    { id: 'posts', label: '🦋 Posts', description: 'Bluesky posts — likes, reposts, replies, quotes' },
    { id: 'feeds', label: '📡 Feeds', description: 'Custom algorithmic feeds created' },
    { id: 'starter-packs', label: '🎒 Starter Packs', description: 'Curated follow lists for community onboarding' },
    { id: 'threads', label: '🧵 Threads', description: 'Long-form thread posts' },
    { id: 'analytics', label: '📊 Analytics', description: 'Followers, engagement rate, profile views' },
    { id: 'labelers', label: '🏷 Labelers', description: 'Content label providers followed' },
    { id: 'lists', label: '📋 Lists', description: 'Curated follow lists' },
    { id: 'following', label: '👥 Following', description: 'Following/follower network graph' },
  ],
  threads: [
    { id: 'threads', label: '🧵 Threads', description: 'Posted threads — likes, reposts, replies, quotes' },
    { id: 'replies', label: '💬 Replies', description: 'Reply engagement on your threads' },
    { id: 'analytics', label: '📊 Analytics', description: 'Views, likes, reposts, replies, follower growth' },
    { id: 'mentions', label: '@ Mentions', description: 'Accounts mentioning your handle' },
    { id: 'trending', label: '🔥 Trending', description: 'Trending topics in your niche' },
    { id: 'following', label: '👥 Following', description: 'Cross-Instagram follower overlap' },
    { id: 'insights', label: '💡 Insights', description: 'Top performing threads and content themes' },
    { id: 'search', label: '🔍 Search', description: 'Threads search and keyword monitoring' },
  ],
  tumblr: [
    { id: 'posts', label: '📝 Posts', description: 'All post types — text, photo, video, audio, quote, link, chat' },
    { id: 'reblogs', label: '🔁 Reblogs', description: 'Reblog chains and original post reach' },
    { id: 'tags', label: '🏷 Tags', description: 'Tag performance and tag-based discovery' },
    { id: 'queue', label: '⏰ Queue', description: 'Scheduled posts in queue' },
    { id: 'analytics', label: '📊 Analytics', description: 'Notes count, followers, blog views, post performance' },
    { id: 'blogs', label: '📰 Blogs', description: 'Multiple blog management' },
    { id: 'asks', label: '❓ Asks', description: 'Ask inbox — received and answered asks' },
    { id: 'communities', label: '🏘 Communities', description: 'Tumblr Community engagement' },
  ],
  yelp: [
    { id: 'reviews', label: '⭐ Reviews', description: 'Customer reviews — respond, flag, thank' },
    { id: 'photos', label: '🖼 Photos', description: 'Business photos added by owner and customers' },
    { id: 'profile', label: '📋 Profile', description: 'Business info — hours, address, categories, attributes' },
    { id: 'analytics', label: '📊 Analytics', description: 'Page views, customer leads, direction requests, calls' },
    { id: 'ads', label: '🎯 Yelp Ads', description: 'Yelp Ads campaigns and leads generated' },
    { id: 'check-ins', label: '✅ Check-ins', description: 'Customer check-in count and offers' },
    { id: 'messages', label: '💬 Messages', description: 'Customer messages via Yelp' },
    { id: 'competitors', label: '🏆 Competitors', description: 'Nearby competitor rating comparison' },
  ],
  tripadvisor: [
    { id: 'reviews', label: '⭐ Reviews', description: 'Traveler reviews — respond, flag, thank' },
    { id: 'photos', label: '🖼 Photos', description: 'Property and traveler photos' },
    { id: 'profile', label: '📋 Profile', description: 'Business info, amenities, description' },
    { id: 'analytics', label: '📊 Analytics', description: 'Review count, rating trend, ranking in category' },
    { id: 'ranking', label: '🏆 Ranking', description: 'Position in destination category and trend' },
    { id: 'q-and-a', label: '❓ Q&A', description: 'Traveler questions and owner answers' },
    { id: 'experiences', label: '🎭 Experiences', description: 'Tours, activities, and experiences listed' },
    { id: 'awards', label: '🥇 Awards', description: "Travelers' Choice and other award badges" },
  ],
  quora_manual: [
    { id: 'answers', label: '💡 Answers', description: 'Answers posted — views, upvotes, shares' },
    { id: 'questions', label: '❓ Questions', description: 'Questions asked and followed' },
    { id: 'spaces', label: '🏘 Spaces', description: 'Quora Spaces posts and follower count' },
    { id: 'analytics', label: '📊 Analytics', description: 'Answer views, upvotes, credentials, follower growth' },
    { id: 'profile', label: '👤 Profile', description: 'Profile completeness, credentials, bio, topics' },
    { id: 'following', label: '📚 Topics', description: 'Topics followed and expertise areas' },
    { id: 'ads', label: '🎯 Quora Ads', description: 'Question-targeted ad campaigns' },
    { id: 'digest', label: '📧 Digest', description: 'Quora email digest performance for followed topics' },
  ],
  stack_overflow: [
    { id: 'answers', label: '💡 Answers', description: 'Answers posted — votes, accepted status, views' },
    { id: 'questions', label: '❓ Questions', description: 'Questions asked — views, votes, answers' },
    { id: 'reputation', label: '⭐ Reputation', description: 'Reputation score trend and badge history' },
    { id: 'tags', label: '🏷 Tags', description: 'Top tags answered and expertise score' },
    { id: 'analytics', label: '📊 Analytics', description: 'Profile views, question views, answer acceptance rate' },
    { id: 'teams', label: '👥 Teams', description: 'Stack Overflow for Teams private Q&A' },
    { id: 'jobs', label: '💼 Jobs', description: 'Stack Overflow Jobs listing performance' },
    { id: 'collectives', label: '🏘 Collectives', description: 'Collective membership and recognized member status' },
  ],
  dailymotion: [
    { id: 'videos', label: '🎬 Videos', description: 'Uploaded videos — views, likes, comments, embeds' },
    { id: 'playlists', label: '📋 Playlists', description: 'Video playlists and collections' },
    { id: 'analytics', label: '📊 Analytics', description: 'Views, watch time, bandwidth, geography' },
    { id: 'live', label: '🔴 Live', description: 'Live streams — concurrent viewers, total views' },
    { id: 'embed', label: '📤 Embed', description: 'Embedded player stats and top embedding sites' },
    { id: 'monetization', label: '💰 Monetization', description: 'Ad revenue from Dailymotion ad network' },
    { id: 'channel', label: '📺 Channel', description: 'Channel customization and subscriber count' },
    { id: 'subtitles', label: '📝 Subtitles', description: 'Subtitle/caption tracks per video' },
  ],
  telegram: [
    { id: 'posts', label: '📣 Posts', description: 'Channel posts — views, forwards, reactions' },
    { id: 'members', label: '👥 Members', description: 'Member count trend and join/leave rate' },
    { id: 'broadcasts', label: '📡 Broadcasts', description: 'Broadcast messages sent to channel' },
    { id: 'bots', label: '🤖 Bots', description: 'Bot interactions, commands, user flows' },
    { id: 'analytics', label: '📊 Analytics', description: 'Post views, reach, forwards, link clicks' },
    { id: 'polls', label: '📊 Polls', description: 'Polls and quiz results' },
    { id: 'files', label: '📁 Files', description: 'Media and document sharing history' },
    { id: 'groups', label: '👥 Groups', description: 'Group chats and supergroup management' },
  ],
  slack: [
    { id: 'channels', label: '📢 Channels', description: 'Workspace channels — messages, members, activity' },
    { id: 'messages', label: '💬 Messages', description: 'Messages sent, threads, reactions' },
    { id: 'apps', label: '🔌 Apps', description: 'Installed Slack apps and integrations' },
    { id: 'workflows', label: '⚙️ Workflows', description: 'Automated workflows and triggers' },
    { id: 'analytics', label: '📊 Analytics', description: 'Active users, messages per day, channel growth' },
    { id: 'files', label: '📁 Files', description: 'Shared files and storage usage' },
    { id: 'huddles', label: '🎙 Huddles', description: 'Audio/video huddle usage' },
    { id: 'members', label: '👥 Members', description: 'Workspace member count and activity' },
  ],
  dribbble: [
    { id: 'shots', label: '🎨 Shots', description: 'Design shots — views, likes, saves, comments' },
    { id: 'projects', label: '📁 Projects', description: 'Project collections and portfolios' },
    { id: 'analytics', label: '📊 Analytics', description: 'Profile views, shot views, follower growth' },
    { id: 'followers', label: '👥 Followers', description: 'Follower/following network' },
    { id: 'collections', label: '📋 Collections', description: 'Curated design collections' },
    { id: 'jobs', label: '💼 Jobs', description: 'Design jobs listed on Dribbble' },
    { id: 'tags', label: '🏷 Tags', description: 'Tag-based discovery and trending tags' },
    { id: 'pro', label: '⭐ Pro', description: 'Dribbble Pro features and analytics' },
  ],
  kijiji: [
    { id: 'ads', label: '🏷️ Ads', description: 'Active classified ads — views, replies, favorites' },
    { id: 'messages', label: '💬 Messages', description: 'Messages from interested buyers/renters' },
    { id: 'profile', label: '👤 Profile', description: 'Seller profile, ratings, verified status' },
    { id: 'analytics', label: '📊 Analytics', description: 'Ad views, reply rate, listing performance' },
    { id: 'categories', label: '📑 Categories', description: 'Ad categories — buy/sell, services, housing, jobs' },
    { id: 'featured', label: '⭐ Featured', description: 'Featured/top ad promotions' },
    { id: 'local', label: '📍 Local', description: 'Local area targeting and search radius' },
    { id: 'history', label: '📋 History', description: 'Past and expired ads archive' },
  ],
};

// Ordered list of all platform keys covered by this config
export const ALL_PLATFORM_KEYS: string[] = Object.keys(PLATFORM_SPECIFIC_TABS);

// Helper: derive a display-friendly label from a platform key
export function platformDisplayName(key: string): string {
  const reg = PLATFORM_REGISTRY[key];
  if (reg) return reg.displayName;
  // Fallback for keys not in registry
  const overrides: Record<string, string> = {
    x_twitter: 'X / Twitter',
    whatsapp_business: 'WhatsApp Business',
    google_business: 'Google Business',
    apple_podcasts: 'Apple Podcasts',
    quora_manual: 'Quora',
    stack_overflow: 'Stack Overflow',
  };
  return overrides[key] ?? key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g, ' ');
}

// Lightweight hub metadata derived from PLATFORM_REGISTRY for backward compatibility
export const PLATFORM_META: PlatformHubMeta[] = Object.values(PLATFORM_REGISTRY).map(p => ({
  key: p.key,
  displayName: p.displayName,
  emoji: p.emoji,
  priority: p.priority,
  connector: p.connector === 'postiz' ? 'Postiz' : p.connector === 'custom_connector' ? 'Custom' : 'Manual',
  contentTypes: p.supportedContentTypes,
}));
