// PLATFORM_REGISTRY — canonical metadata for all 36 social/content platforms.
// Pure data — no React, no fetch, no database.

import type { PlatformMeta, PlatformKey, Priority, ConnectorType } from './types';

export const PLATFORM_REGISTRY: Record<string, PlatformMeta> = {
  facebook: {
    key: 'facebook',
    displayName: 'Facebook',
    emoji: '📘',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'B2C/B2B brand awareness',
    contentStrength: 'Text/image/video/stories',
    manualPrerequisite: 'Page + developer app',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'story', 'reel', 'carousel', 'poll'],
    maxChars: 63206,
    supportsScheduling: true,
    developerPortalUrl: 'https://developers.facebook.com',
  },
  instagram: {
    key: 'instagram',
    displayName: 'Instagram',
    emoji: '📸',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'Visual brand/discovery',
    contentStrength: 'Images/reels/stories',
    manualPrerequisite: 'Business account + developer app',
    supportedContentTypes: ['image_post', 'video_post', 'reel', 'story', 'carousel'],
    maxChars: 2200,
    supportsScheduling: true,
    developerPortalUrl: 'https://developers.facebook.com/docs/instagram',
  },
  linkedin: {
    key: 'linkedin',
    displayName: 'LinkedIn',
    emoji: '💼',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'B2B/professional',
    contentStrength: 'Articles/posts/documents',
    manualPrerequisite: 'Account + developer app',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'article', 'document_post', 'newsletter'],
    maxChars: 3000,
    supportsScheduling: true,
    developerPortalUrl: 'https://developer.linkedin.com',
  },
  x_twitter: {
    key: 'x_twitter',
    displayName: 'X / Twitter',
    emoji: '🐦',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'Real-time/viral/news',
    contentStrength: 'Short text/threads',
    manualPrerequisite: 'Account + developer app (paid tier for write)',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'poll', 'thread'],
    maxChars: 280,
    supportsScheduling: true,
    developerPortalUrl: 'https://developer.twitter.com',
  },
  youtube: {
    key: 'youtube',
    displayName: 'YouTube',
    emoji: '📺',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'Video marketing/education',
    contentStrength: 'Video/shorts/live',
    manualPrerequisite: 'Google account + Cloud project + YouTube API',
    supportedContentTypes: ['video_post', 'short', 'live', 'community_post', 'article'],
    maxChars: 5000,
    supportsScheduling: true,
    developerPortalUrl: 'https://developers.google.com/youtube',
  },
  tiktok: {
    key: 'tiktok',
    displayName: 'TikTok',
    emoji: '🎵',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'B2C awareness/viral',
    contentStrength: 'Short video/live',
    manualPrerequisite: 'Account + developer/OAuth',
    supportedContentTypes: ['video_post', 'story', 'live'],
    maxChars: 2200,
    supportsScheduling: true,
    developerPortalUrl: 'https://developers.tiktok.com',
  },
  whatsapp_business: {
    key: 'whatsapp_business',
    displayName: 'WhatsApp Business',
    emoji: '💬',
    connector: 'custom_connector',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'Customer communication',
    contentStrength: 'Message/media',
    manualPrerequisite: 'Business/number verification',
    supportedContentTypes: ['message', 'template_message', 'broadcast'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developers.facebook.com/docs/whatsapp',
  },
  google_business: {
    key: 'google_business',
    displayName: 'Google Business',
    emoji: '🗺️',
    connector: 'custom_connector',
    priority: 'high',
    automationPotential: 'medium',
    businessUse: 'Local SEO/reviews/discovery',
    contentStrength: 'Posts/reviews/photos',
    manualPrerequisite: 'Verified business + GCP project',
    supportedContentTypes: ['text_post', 'image_post', 'review_response', 'review_invitation'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developers.google.com/my-business',
  },
  pinterest: {
    key: 'pinterest',
    displayName: 'Pinterest',
    emoji: '📌',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'high',
    businessUse: 'Retail/lifestyle/discovery',
    contentStrength: 'Images/pins/video',
    manualPrerequisite: 'Business + developer access',
    supportedContentTypes: ['pin', 'idea_pin', 'video_post'],
    maxChars: 500,
    supportsScheduling: true,
    developerPortalUrl: 'https://developers.pinterest.com',
  },
  reddit: {
    key: 'reddit',
    displayName: 'Reddit',
    emoji: '🤖',
    connector: 'postiz',
    priority: 'high',
    automationPotential: 'medium',
    businessUse: 'Community/research',
    contentStrength: 'Discussion/text',
    manualPrerequisite: 'Account + API authorization',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'poll'],
    maxChars: 40000,
    supportsScheduling: true,
    developerPortalUrl: 'https://www.reddit.com/prefs/apps',
  },
  telegram: {
    key: 'telegram',
    displayName: 'Telegram',
    emoji: '✈️',
    connector: 'custom_connector',
    priority: 'high',
    automationPotential: 'very_high',
    businessUse: 'Community/broadcast',
    contentStrength: 'Text/media/bots',
    manualPrerequisite: 'Account + bot/channel setup',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'broadcast'],
    maxChars: 4096,
    supportsScheduling: true,
    developerPortalUrl: 'https://core.telegram.org/bots',
  },
  threads: {
    key: 'threads',
    displayName: 'Threads',
    emoji: '🧵',
    connector: 'postiz',
    priority: 'medium',
    automationPotential: 'high',
    businessUse: 'Brand/conversation',
    contentStrength: 'Short text/images',
    manualPrerequisite: 'Meta/Threads setup',
    supportedContentTypes: ['text_post', 'image_post', 'video_post', 'thread'],
    maxChars: 500,
    supportsScheduling: true,
  },
  snapchat: {
    key: 'snapchat',
    displayName: 'Snapchat',
    emoji: '👻',
    connector: 'manual_only',
    priority: 'medium',
    automationPotential: 'medium',
    businessUse: 'Younger consumer audiences',
    contentStrength: 'Short visual/video',
    manualPrerequisite: 'Business/developer setup',
    supportedContentTypes: ['story', 'video_post'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developers.snap.com',
  },
  discord: {
    key: 'discord',
    displayName: 'Discord',
    emoji: '🎮',
    connector: 'custom_connector',
    priority: 'medium',
    automationPotential: 'very_high',
    businessUse: 'Community/product',
    contentStrength: 'Chat/events/bots',
    manualPrerequisite: 'Server + bot authorization',
    supportedContentTypes: ['text_post', 'image_post', 'video_post'],
    maxChars: 2000,
    supportsScheduling: false,
    developerPortalUrl: 'https://discord.com/developers',
  },
  twitch: {
    key: 'twitch',
    displayName: 'Twitch',
    emoji: '🎮',
    connector: 'postiz',
    priority: 'medium',
    automationPotential: 'high',
    businessUse: 'Gaming/live/community',
    contentStrength: 'Live/video',
    manualPrerequisite: 'Account + developer OAuth',
    supportedContentTypes: ['live', 'video_post'],
    supportsScheduling: true,
    developerPortalUrl: 'https://dev.twitch.tv',
  },
  medium: {
    key: 'medium',
    displayName: 'Medium',
    emoji: '📰',
    connector: 'postiz',
    priority: 'medium',
    automationPotential: 'medium',
    businessUse: 'Thought leadership',
    contentStrength: 'Long-form articles',
    manualPrerequisite: 'Publication/account setup',
    supportedContentTypes: ['article', 'text_post'],
    maxChars: 100000,
    supportsScheduling: false,
    developerPortalUrl: 'https://developers.medium.com',
  },
  substack: {
    key: 'substack',
    displayName: 'Substack',
    emoji: '📬',
    connector: 'manual_only',
    priority: 'medium',
    automationPotential: 'low',
    businessUse: 'Newsletter/subscription',
    contentStrength: 'Newsletter/podcast',
    manualPrerequisite: 'Substack publication setup',
    supportedContentTypes: ['newsletter', 'podcast_episode', 'text_post'],
    supportsScheduling: true,
  },
  tumblr: {
    key: 'tumblr',
    displayName: 'Tumblr',
    emoji: '📓',
    connector: 'postiz',
    priority: 'low',
    automationPotential: 'medium',
    businessUse: 'Creative/niche communities',
    contentStrength: 'Multi-format posts',
    manualPrerequisite: 'Account + API app registration',
    supportedContentTypes: ['text_post', 'image_post', 'video_post'],
    maxChars: 4096,
    supportsScheduling: true,
    developerPortalUrl: 'https://www.tumblr.com/oauth/apps',
  },
  github: {
    key: 'github',
    displayName: 'GitHub',
    emoji: '🐙',
    connector: 'custom_connector',
    priority: 'medium',
    automationPotential: 'high',
    businessUse: 'Developer community/OSS',
    contentStrength: 'Repos/releases/discussions',
    manualPrerequisite: 'GitHub account + PAT or OAuth app',
    supportedContentTypes: ['release', 'discussion', 'gist'],
    supportsScheduling: false,
    developerPortalUrl: 'https://docs.github.com/en/rest',
  },
  gitlab: {
    key: 'gitlab',
    displayName: 'GitLab',
    emoji: '🦊',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'medium',
    businessUse: 'DevOps/developer community',
    contentStrength: 'Projects/releases/snippets',
    manualPrerequisite: 'GitLab account + PAT',
    supportedContentTypes: ['release', 'discussion'],
    supportsScheduling: false,
    developerPortalUrl: 'https://docs.gitlab.com/ee/api/',
  },
  trustpilot: {
    key: 'trustpilot',
    displayName: 'Trustpilot',
    emoji: '⭐',
    connector: 'custom_connector',
    priority: 'medium',
    automationPotential: 'high',
    businessUse: 'Online reputation/trust',
    contentStrength: 'Reviews/invitations/responses',
    manualPrerequisite: 'Business account + API key',
    supportedContentTypes: ['review_response', 'review_invitation'],
    supportsScheduling: false,
    developerPortalUrl: 'https://support.trustpilot.com/hc/en-us/articles/115005180285',
  },
  vimeo: {
    key: 'vimeo',
    displayName: 'Vimeo',
    emoji: '🎬',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'medium',
    businessUse: 'Professional video hosting',
    contentStrength: 'High-quality video',
    manualPrerequisite: 'Vimeo account + access token',
    supportedContentTypes: ['video_upload', 'live'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developer.vimeo.com',
  },
  soundcloud: {
    key: 'soundcloud',
    displayName: 'SoundCloud',
    emoji: '🎶',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'low',
    businessUse: 'Audio/music community',
    contentStrength: 'Tracks/playlists',
    manualPrerequisite: 'SoundCloud account + OAuth',
    supportedContentTypes: ['track_upload'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developers.soundcloud.com',
  },
  dailymotion: {
    key: 'dailymotion',
    displayName: 'Dailymotion',
    emoji: '📹',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'low',
    businessUse: 'Video distribution/Europe',
    contentStrength: 'Video/live',
    manualPrerequisite: 'Partner account + API key',
    supportedContentTypes: ['video_upload', 'live'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developer.dailymotion.com',
  },
  spotify: {
    key: 'spotify',
    displayName: 'Spotify',
    emoji: '🎧',
    connector: 'manual_only',
    priority: 'medium',
    automationPotential: 'medium',
    businessUse: 'Podcast distribution/audio',
    contentStrength: 'Podcast episodes/shows',
    manualPrerequisite: 'Spotify for Podcasters + distribution via RSS or Anchor',
    supportedContentTypes: ['podcast_episode'],
    supportsScheduling: false,
    developerPortalUrl: 'https://developer.spotify.com',
  },
  apple_podcasts: {
    key: 'apple_podcasts',
    displayName: 'Apple Podcasts',
    emoji: '🍎',
    connector: 'manual_only',
    priority: 'medium',
    automationPotential: 'low',
    businessUse: 'Podcast distribution/iOS',
    contentStrength: 'Podcast episodes',
    manualPrerequisite: 'Apple ID + Podcasts Connect + RSS',
    supportedContentTypes: ['podcast_episode'],
    supportsScheduling: false,
    developerPortalUrl: 'https://podcastsconnect.apple.com',
  },
  patreon: {
    key: 'patreon',
    displayName: 'Patreon',
    emoji: '🎨',
    connector: 'custom_connector',
    priority: 'low',
    automationPotential: 'medium',
    businessUse: 'Creator monetization/membership',
    contentStrength: 'Creator posts/tiers/benefits',
    manualPrerequisite: 'Creator account + API client',
    supportedContentTypes: ['creator_post'],
    supportsScheduling: false,
    developerPortalUrl: 'https://docs.patreon.com',
  },
  quora_manual: {
    key: 'quora_manual',
    displayName: 'Quora',
    emoji: '❓',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'none',
    businessUse: 'Thought leadership/Q&A',
    contentStrength: 'Answers/spaces',
    manualPrerequisite: 'Account setup — no public write API',
    supportedContentTypes: ['text_post'],
    maxChars: 10000,
    supportsScheduling: false,
  },
  stack_overflow: {
    key: 'stack_overflow',
    displayName: 'Stack Overflow',
    emoji: '🔧',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'none',
    businessUse: 'Developer community/Q&A',
    contentStrength: 'Answers/questions',
    manualPrerequisite: 'Account — read-only public API only',
    supportedContentTypes: ['text_post'],
    supportsScheduling: false,
    developerPortalUrl: 'https://api.stackexchange.com',
  },
  bluesky: {
    key: 'bluesky',
    displayName: 'Bluesky',
    emoji: '🦋',
    connector: 'postiz',
    priority: 'low',
    automationPotential: 'high',
    businessUse: 'Decentralized social/early adopters',
    contentStrength: 'Short posts/threads',
    manualPrerequisite: 'Account + app password',
    supportedContentTypes: ['text_post', 'image_post', 'thread'],
    maxChars: 300,
    supportsScheduling: true,
  },
  mastodon: {
    key: 'mastodon',
    displayName: 'Mastodon',
    emoji: '🐘',
    connector: 'postiz',
    priority: 'low',
    automationPotential: 'high',
    businessUse: 'Decentralized social/niche',
    contentStrength: 'Text/images/toots',
    manualPrerequisite: 'Instance account + OAuth app',
    supportedContentTypes: ['text_post', 'image_post'],
    maxChars: 500,
    supportsScheduling: true,
  },
  yelp: {
    key: 'yelp',
    displayName: 'Yelp',
    emoji: '⭐',
    connector: 'custom_connector',
    priority: 'medium',
    automationPotential: 'medium',
    businessUse: 'Local reviews/discovery',
    contentStrength: 'Reviews/photos/profile',
    manualPrerequisite: 'Business account + API key (read-mostly)',
    supportedContentTypes: ['review_response'],
    supportsScheduling: false,
    developerPortalUrl: 'https://www.yelp.com/developers',
  },
  tripadvisor: {
    key: 'tripadvisor',
    displayName: 'TripAdvisor',
    emoji: '✈️',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'low',
    businessUse: 'Travel/hospitality reviews',
    contentStrength: 'Reviews/experiences',
    manualPrerequisite: 'Business listing — limited API',
    supportedContentTypes: ['review_response'],
    supportsScheduling: false,
    developerPortalUrl: 'https://tripadvisor-content-api.readme.io',
  },
  slack: {
    key: 'slack',
    displayName: 'Slack',
    emoji: '💬',
    connector: 'custom_connector',
    priority: 'medium',
    automationPotential: 'very_high',
    businessUse: 'Internal communications/community',
    contentStrength: 'Messages/bots/automation',
    manualPrerequisite: 'Workspace + Slack app',
    supportedContentTypes: ['message', 'broadcast'],
    maxChars: 40000,
    supportsScheduling: false,
    developerPortalUrl: 'https://api.slack.com',
  },
  dribbble: {
    key: 'dribbble',
    displayName: 'Dribbble',
    emoji: '🏀',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'low',
    businessUse: 'Design portfolio/community',
    contentStrength: 'Design shots/projects',
    manualPrerequisite: 'Account + API application',
    supportedContentTypes: ['image_post'],
    supportsScheduling: false,
    developerPortalUrl: 'https://dribbble.com/api',
  },
  kijiji: {
    key: 'kijiji',
    displayName: 'Kijiji',
    emoji: '🏷️',
    connector: 'manual_only',
    priority: 'low',
    automationPotential: 'none',
    businessUse: 'Canadian classifieds/local ads',
    contentStrength: 'Classified ads',
    manualPrerequisite: 'Account — no public API',
    supportedContentTypes: ['text_post', 'image_post'],
    supportsScheduling: false,
  },
};

export function getPlatformsByPriority(priority: Priority): PlatformMeta[] {
  return Object.values(PLATFORM_REGISTRY).filter(p => p.priority === priority);
}

export function getPlatformsByConnector(connector: ConnectorType): PlatformMeta[] {
  return Object.values(PLATFORM_REGISTRY).filter(p => p.connector === connector);
}

export function getPlatformsWithAutomation(): PlatformMeta[] {
  return Object.values(PLATFORM_REGISTRY).filter(
    p => p.automationPotential === 'high' || p.automationPotential === 'very_high'
  );
}

export function getAllPlatformKeys(): string[] {
  return Object.keys(PLATFORM_REGISTRY);
}
