-- Second cataloging batch, 2026-08-31: Booking, Wellness, E-commerce.
-- All findings from a real code/schema audit (grep-verified: no INSERT path
-- exists for booking or sales_order from any customer-facing code; wellness
-- admin page is fully mock). Nothing here is a guess.

INSERT INTO module_registry (app, module_key, name, description, built_status,
  user_flow, admin_flow, data_flow, flowchart, user_story, input_desc, process_desc, output_desc, final_outcome,
  job_name, report_location, dashboard_location, schema_tables, demo_use_cases, integration_platforms, missing_items,
  source_doc, last_verified_at, verified_by)
VALUES
('sohamyoga-frontend', 'booking', 'Class Booking',
 'Class session scheduling, student bookings, waitlist, no-show tracking.', 'partial',
 'NOT REAL TODAY: /booking and /booking/[classId] render a hardcoded CLASS_DATA object and a fake setTimeout(800ms) "booking" with no network call — a customer cannot actually book a class end-to-end.',
 'Admin views Overview/Today/Upcoming/Waitlist/No-shows/Rules/Reports tabs (all real, API-backed), checks students in or cancels a booking, monitors no-show strikes (suspension at 3).',
 'Nothing populates `booking` today (grep-confirmed: no INSERT INTO booking anywhere) — admin tabs read real tables but those tables are empty in practice until a real customer booking path is built.',
 '[NOT BUILT] Customer picks class -> books -> booking row created -> class_session fills -> admin checks in / no-show tracked -> waitlist promotes on cancellation',
 'As a student, I want to book a real class session and see my booking confirmed, so I actually have a seat reserved — not built yet.',
 'Class session + student identity (once real).',
 'Admin-side moderation (check-in/cancel) is real; the actual booking-creation process does not exist.',
 'Real admin visibility into (currently empty) booking data.',
 'A confirmed, checked-in, or honestly no-show-tracked booking — not achievable today since bookings are never created.',
 NULL, '/admin/booking -> Reports tab', '/admin/booking -> Overview tab',
 ARRAY['class_session','booking','waitlist_entry'],
 '[]'::jsonb, '[]'::jsonb,
 'The core gap: no real customer-facing booking-creation flow exists. /booking and /booking/[classId] are mock UI only. Until that''s built, this module cannot demo end-to-end.',
 'live code/schema audit 2026-08-31 (grep-verified no INSERT INTO booking anywhere)', now(), 'claude-session-339c0b70'),

('sohamyoga-frontend', 'wellness', 'Wellness Tracking',
 'Health profile, body metrics, daily wellness log, wearable sync.', 'not_built',
 'No real end-user surface exists for this domain.',
 '/admin/wellness page is entirely mock — every KPI/tab is a hardcoded JS constant, zero fetch() calls to any API.',
 'None — health_profile/body_metrics/daily_wellness_log/wearable_sync/wearable_data_point/wellness_audit tables have zero API routes anywhere in the app.',
 '[NOT BUILT] No real data flow exists for this schema at all.',
 'As a student, I want my wellness metrics tracked over time, so I can see my progress — not built.',
 'N/A — no input path exists.',
 'N/A.',
 'N/A.',
 'N/A — this module is schema-only.',
 NULL, NULL, '/admin/wellness (mock only, not wired to any API)',
 ARRAY['health_profile','body_metrics','daily_wellness_log','wearable_sync','wearable_data_point','wellness_audit'],
 '[]'::jsonb, '[]'::jsonb,
 'Everything: no API routes for this schema exist at all, and the admin page is pure mock data (commented "// -- Mock data --" in the source). Note: the real "wellness-scoring" cron job does NOT touch this schema — it scores a different domain entirely (student.practice_journal), which is itself never populated by any app code either.',
 'live code/schema audit 2026-08-31', now(), 'claude-session-339c0b70'),

('sohamyoga-frontend', 'ecommerce', 'E-commerce',
 'Product catalog, inventory, vendors, orders, shipments, payments, abandoned-cart recovery.', 'partial',
 'NOT REAL TODAY: no shop/storefront page exists; /catalog is a hardcoded yoga-class catalog unrelated to product_master. A customer cannot browse or purchase a real product.',
 'Admin reviews revenue/order/stock KPIs, creates/edits products (real INSERT), approves/suspends vendors, views Ollama-ranked product recommendations, marks abandoned-cart recovery drafts as sent.',
 'Admin creates product_master rows -> (no real order-creation path exists) -> abandoned-cart-recovery job looks for stuck sales_order rows but finds none in practice since nothing creates them.',
 '[PARTIAL] Admin creates product -> [MISSING: customer browses/buys] -> sales_order+order_item -> abandoned-cart-recovery drafts a message if stuck 2h+ -> staff sends manually -> shipment/payment',
 'As a customer, I want to buy a product from a real store, so I receive a real order and shipment — not built yet; admin can manage inventory/vendors in the meantime.',
 'Product data (real, admin-entered) + (missing) a customer purchase action.',
 'Admin-side product/vendor/inventory CRUD is real and DB-backed; order-creation has no real trigger.',
 'Real product/vendor records; KPI dashboards computed from (empty-in-practice) sales_order/inventory joins.',
 'A real order with payment and shipment — not achievable today since no code path ever creates a sales_order.',
 'abandoned-cart-recovery', '/admin/ecommerce -> dashboard KPIs', '/admin/ecommerce',
 ARRAY['category','product_master','product_variant','product_image','warehouse','inventory','stock_movement','supplier','purchase_order','sales_order','order_item','shipment','payment','wallet','wallet_transaction','vendor','commission','abandoned_cart_recovery'],
 '[]'::jsonb, '[]'::jsonb,
 'The core gap: no real storefront/checkout flow exists, so sales_order is never populated by real customer action (grep-confirmed: no INSERT INTO sales_order anywhere) — the abandoned-cart-recovery job has no live input in practice despite being real code.',
 'live code/schema audit 2026-08-31 (grep-verified no INSERT INTO sales_order anywhere)', now(), 'claude-session-339c0b70')
ON CONFLICT (app, module_key) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, built_status = EXCLUDED.built_status,
  user_flow = EXCLUDED.user_flow, admin_flow = EXCLUDED.admin_flow, data_flow = EXCLUDED.data_flow,
  flowchart = EXCLUDED.flowchart, user_story = EXCLUDED.user_story, input_desc = EXCLUDED.input_desc,
  process_desc = EXCLUDED.process_desc, output_desc = EXCLUDED.output_desc, final_outcome = EXCLUDED.final_outcome,
  job_name = EXCLUDED.job_name, report_location = EXCLUDED.report_location, dashboard_location = EXCLUDED.dashboard_location,
  schema_tables = EXCLUDED.schema_tables, demo_use_cases = EXCLUDED.demo_use_cases, integration_platforms = EXCLUDED.integration_platforms,
  missing_items = EXCLUDED.missing_items, source_doc = EXCLUDED.source_doc, last_verified_at = EXCLUDED.last_verified_at,
  verified_by = EXCLUDED.verified_by, updated_at = now();
