import { NextRequest } from 'next/server';
import { videoWorkspace } from '@/domain/video/workspaceApi';
import { safeMediaUrl, validateTracks } from '@/domain/video/workspaceValidation';
import { getCustomerPrincipal } from '@/lib/customer-auth';
import { getAdminPrincipal } from '@/lib/admin-auth';
import { query, transaction } from '@/lib/postgres';
jest.mock('@/lib/customer-auth',()=>({getCustomerPrincipal:jest.fn()}));
jest.mock('@/lib/admin-auth',()=>({getAdminPrincipal:jest.fn()}));
jest.mock('@/lib/postgres',()=>({databaseConfigured:()=>true,query:jest.fn(),transaction:jest.fn()}));
jest.mock('@/domain/ingestion/Connector',()=>({getPrimaryTenantId:async()=>'tenant-1'}));
const id='11111111-1111-4111-8111-111111111111';
const req=(method='GET',body?:unknown)=>new NextRequest('http://localhost/api/customer/video-workspace',{method,...(body?{body:JSON.stringify(body)}:{})});
beforeEach(()=>{jest.resetAllMocks();jest.mocked(getCustomerPrincipal).mockResolvedValue({principal:{id,roles:[]}});jest.mocked(getAdminPrincipal).mockResolvedValue({principal:{id,roles:['Editor']}});});
it('rejects unauthenticated customers before database access',async()=>{jest.mocked(getCustomerPrincipal).mockResolvedValue({denied:Response.json({error:'unauthorized'},{status:401})});expect((await videoWorkspace(req(),false)).status).toBe(401);expect(query).not.toHaveBeenCalled();});
it('scopes the project list to the authenticated customer and tenant',async()=>{jest.mocked(query).mockResolvedValueOnce({rows:[{id:'customer-1',tenant_id:'tenant-1'}]} as never).mockResolvedValueOnce({rows:[]} as never);expect((await videoWorkspace(req(),false)).status).toBe(200);expect(query).toHaveBeenLastCalledWith(expect.stringContaining('tenant_id=$1 AND customer_id=$2'),['tenant-1','customer-1']);});
it('does not expose another customer project',async()=>{jest.mocked(query).mockResolvedValueOnce({rows:[{id:'customer-1',tenant_id:'tenant-1'}]} as never).mockResolvedValueOnce({rows:[]} as never);expect((await videoWorkspace(new NextRequest(`http://localhost/api/customer/video-workspace?id=${id}`),false)).status).toBe(404);});
it('rejects customer delivery mutations even for an owned project',async()=>{jest.mocked(query).mockResolvedValue({rows:[{id:'customer-1',tenant_id:'tenant-1'}]} as never);const client={query:jest.fn().mockResolvedValue({rows:[{id,status:'draft'}]})};jest.mocked(transaction).mockImplementation(async fn=>fn(client as never));expect((await videoWorkspace(req('PATCH',{id,action:'delivery',url:'https://example.org/video.mp4'}),false)).status).toBe(403);expect(client.query).toHaveBeenCalledTimes(1);});
it('rejects approval without a review delivery',async()=>{const client={query:jest.fn().mockResolvedValue({rows:[{id,status:'draft'}]})};jest.mocked(transaction).mockImplementation(async fn=>fn(client as never));expect((await videoWorkspace(req('PATCH',{id,action:'approve'}),true)).status).toBe(409);expect(client.query).toHaveBeenCalledTimes(1);});
it('rejects unauthenticated internal users',async()=>{jest.mocked(getAdminPrincipal).mockResolvedValue({denied:Response.json({},{status:403})});expect((await videoWorkspace(req(),true)).status).toBe(403);});
it.each(['javascript:alert(1)','//evil.test/video.mp4','http://example.org/video.mp4','https://user:password@example.org/video.mp4'])('rejects unsafe delivery %s',url=>expect(safeMediaUrl(url)).toBe(false));
it('accepts the rendered sample URL',()=>expect(safeMediaUrl('/samples/soham-introduction.mp4')).toBe(true));
const track=(patch={})=>[{name:'Video',track_type:'video',muted:false,clips:[{start_ms:0,end_ms:5000,source_in_ms:0,asset_uri:'',properties:{},...patch}]}];
it('rejects invalid clip timing',()=>{expect(()=>validateTracks(track({end_ms:0}))).toThrow();expect(()=>validateTracks(track({start_ms:NaN}))).toThrow();expect(()=>validateTracks(track({source_in_ms:-1}))).toThrow();});
it('rejects out-of-range volume',()=>expect(()=>validateTracks(track({properties:{volume:2}}))).toThrow());
it('normalizes a valid timeline',()=>expect(validateTracks(track())[0].clips[0].properties.volume).toBe(1));
