export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextRequest } from 'next/server';
import { requireAdmin } from '@/lib/admin-auth';

export async function POST(req: NextRequest): Promise<Response> {
  const denied = await requireAdmin(req);
  if (denied) return denied;

  let body: { values?: Record<string, string> } = {};
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const values = body.values ?? {};
  if (typeof values !== 'object' || Array.isArray(values)) {
    return Response.json({ error: 'values must be an object' }, { status: 400 });
  }

  const timestamp = new Date().toISOString();
  const lines: string[] = [
    `# Generated by Setup Wizard — ${timestamp}`,
    '# Add these lines to your .env.local file and restart the dev server',
    '# WARNING: Never commit .env.local to git — this file contains secrets.',
    '',
  ];

  for (const [key, value] of Object.entries(values)) {
    if (typeof key === 'string' && key.trim()) {
      // Basic sanitization: strip newlines from key/value to prevent injection
      const safeKey = key.replace(/[\r\n]/g, '');
      const safeVal = String(value ?? '').replace(/[\r\n]/g, '');
      lines.push(`${safeKey}=${safeVal}`);
    }
  }

  const envContent = lines.join('\n') + '\n';
  return Response.json({ content: envContent, timestamp });
}
